### PR TITLE
Fix dvc add -o issue #7357

### PR DESCRIPTION
**Pull request by eggqq007**
* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by karajan1001** [comment]
I guess a test case is needed for this?

**Comment by dtrifiro** [comment]
Hey @eggqq007, would you be interested in adding a test for this?

**Comment by eggqq007** [comment]
> 

Sorry, I am working on other stuff. I will add testcases in a few days

**Comment by eggqq007** [comment]
testcase was added

**Review by daavoo — APPROVED** [review]

**Review by dtrifiro — APPROVED** [review]

**Comment by dtrifiro** [comment]
Thanks a lot for contributing!

**Pull request merged**
