### PR TITLE
exp run: --reset no longer implies --force

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Will fix https://github.com/iterative/dvc/issues/5628

Docs PR: https://github.com/iterative/dvc.org/pull/2348

### CODE REVIEW

**Comment by dberenbaum** [comment]
To summarize, `--reset` only implies `--force` if there is also a checkpoint out for any stage?

Assuming that's correct:
* What's the behavior of running `--reset` without checkpoint? Should this be allowed?
* If I have a stage with a checkpoint that is downstream of stages without checkpoints that were previously committed (by `dvc repro`), can I reset without having to run all of those upstream stages?

**Comment by pmrowla** [comment]
> To summarize, `--reset` only implies `--force` if there is also a checkpoint out for any stage?

`--reset` no longer implies `--force` at all regardless of whether or not a stage contains `checkpoint` outs. Previously it implied `--force` all the time

> * What's the behavior of running `--reset` without checkpoint? Should this be allowed?

Specifying `--reset` for a stage without checkpoint outs now does nothing (the option is just silently ignored). Previously, this would cause the unexpected behavior of running non-checkpoint stages with `--force`.

> * If I have a stage with a checkpoint that is downstream of stages without checkpoints that were previously committed (by `dvc repro`), can I reset without having to run all of those upstream stages?

In this case, the `--reset` flag will be applied to all of your upstream stages. On `dvc exp run --reset <target>`, we do the equivalent of `dvc checkout --with-deps <target>`, and the `--reset` behavior (to drop existing checkpoint outs if they exist in dvc.lock) happens during this internal checkout step.

There is not currently a way to only `--reset` one specific stage. Doing so, would probably require some kind of separate `--reset-targets/--reset-all` flags, but I think that would be for a separate discussion/feature request.

**Comment by dberenbaum** [comment]
> There is not currently a way to only `--reset` one specific stage

Does `--reset` force execution of non-checkpoint stages upstream of the checkpoint out?

**Comment by pmrowla** [comment]
> Does `--reset` force execution of non-checkpoint stages upstream of the checkpoint out?

No, nothing will be changed for non-checkpoint stages so they will not be rerun (unless there is a checkpoint stage further upstream in the pipeline)

**Review by dberenbaum — APPROVED** [review]
LGTM

**Pull request merged**
