### PR TITLE
repo: don't create .dvc in read-only repos

### PR DESCRIPTION
**Pull request by efiop**
Still a semi-hacky approach that is a pre-requisite for using this in external repos as well.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hi. What's a read-only repo?

**Comment by jorgeorpinel** [comment]
> pre-requisite for using this in external repos as well

Also not sure what external repos are. Are we talking about DVC repos? Or just Git repos. Thanks

**Comment by efiop** [comment]
> Hi. What's a read-only repo?

Repo in which we literally don't write anything. E.g. we don't `dvc add`, we don't write cache, etc. Again, this is more of an internal thing, maybe don't focus on it too much for now.

> Also not sure what external repos are. Are we talking about DVC repos? Or just Git repos. Thanks

This is an internal terminology for dvc/git repos that we clone for things like `dvc import/get` and some api.

**Comment by jorgeorpinel** [comment]
Sure, just curious. Thanks for the info.

**Pull request merged**
