### PR TITLE
ui: disable colorama on write_json when highlighting is disabled

### PR DESCRIPTION
**Pull request by skshetry**
On a large json output (say ~300MB), this saves about ~6 seconds of time.

### CODE REVIEW

**Comment by pmrowla** [comment]
This causes duplicate output to get written when using redirected output

```
$ dvc metrics show --json > test.json
$ cat test.json
{"": {"data": {"eval/live/metrics.json": {"data": {"avg_prec": {"train": 0.9803075050031435, "test": 0.9346081332365263}, "roc_auc": {"train": 0.9905635010414422, "test": 0.9532231738362307}}}}}}
{"": {"data": {"eval/live/metrics.json": {"data": {"avg_prec": {"train": 0.9803075050031435, "test": 0.9346081332365263}, "roc_auc": {"train": 0.9905635010414422, "test": 0.9532231738362307}}}}}}
```

Looks like we just need to make sure stdout/stderr are flushed before we re-enable colorama with `colorama.reinit()`

**Comment by skshetry** [comment]
Ahh right, because the JSON is minified and hence does not get flushed.

**Comment by skshetry** [comment]
I am still trying to understand why it's printing twice.

**Comment by skshetry** [comment]
Okay, I was able to figure out what's happening. This is because of the `os.fork()`.

Running with `DVC_NO_ANALYTICS=1` does not duplicate output. Looks like we should always do `stream.flush()` before we fork.

**Pull request merged**
