### PR TITLE
tests: replace several unittest.mock usages with mocker

### PR DESCRIPTION
**Pull request by nik123**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

Yes, I did.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

No documentation updates are required.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Part of #1819

### CODE REVIEW

**Comment by nik123** [comment]
I guess I'll need a little of help here - have no clue what happened with windows tests

**Comment by skshetry** [comment]
@nik123, could you please try rebasing/merging on top of latest commits in master?

**Comment by pared** [comment]
Failing windows build seems unrelated, we are having problems with the timeout on this version. Retriggering...

**Review by pared — APPROVED** [review]

**Comment by efiop** [comment]
@nik123 Thank you! 🙏

**Pull request merged**
