### PR TITLE
fix ncols_desc=0

### LINKED ISSUE #2598: Issue with dvc push to AWS s3 remote
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

DVC: 0.62.1
Mac: Mojave 10.13
Install with pip

issue with `dvc push`

image

### PR DESCRIPTION
**Pull request by casperdcl**
- fixes #2598 progress errors on narrow terminals/wide descriptions

### CODE REVIEW

**Comment by casperdcl** [comment]
FYI after this fix there would still likely be progress bars printing on new lines each iteration (due to overflow) but at least that's better than crashing. Could open a new issue for this but it's probably similar to https://github.com/tqdm/tqdm/issues/690 (technically though the problem here is even empty descriptions leave a progress bar which is wider than the console).

**Comment by efiop** [comment]
@casperdcl We are talking about extreme cases of tiny terminals, right? Or could that happen in a regular workflow?

**Comment by casperdcl** [comment]
@efiop just tiny terminals

**Comment by efiop** [comment]
@casperdcl In that case, I wouldn't bother overengineering, to be honest. For example, things like `wget` overflow too if you use an unreasonably tiny terminal.

**Pull request merged**
