### PR TITLE
daemon: use Popen on Mac

### LINKED ISSUE #4294: macOS: analytics daemon crashes due to fork related error
After the daemon changes introduced in #4262 (f799e1e3), DVC on macOS crashes when we try to spawn the analytics daemon.

```
dvc git:f799e1e3 ✩  py:dvc ❯ dvc version
WARNING: Unable to detect supported link types, as cache directory '.dvc/cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 1.1.11+f799e1
Python version: 3.8.5
Platform: macOS-10.15.6-x86_64-i386-64bit
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
objc[34576]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[34576]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
Screen Shot 2020-07-28 at 4 37 51 PM

Disabling analytics avoids the crash
```
dvc git:f799e1e3 ✩  py:dvc ❯ dvc config --local core.analytics false
dvc git:f799e1e3 ✩  py:dvc ❯ dvc version
WARNING: Unable to detect supported link types, as cache directory '.dvc/cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 1.1.11+f799e1
Python version: 3.8.5
Platform: macOS-10.15.6-x86_64-i386-64bit
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

This problem appears to be related to `fork` being unsafe in macOS 

See related Python issue: https://bugs.python.org/issue33725 and Python 3.8 [multiprocessing docs](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)

### PR DESCRIPTION
**Pull request by efiop**
Turns out macs are not happy with double-forks without exec.

Fixes #4294

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by efiop** [comment]
@pmrowla Could you give this one a try, please? Just to make sure.

**Comment by dtrifiro** [comment]
> @pmrowla Could you give this one a try, please? Just to make sure.

The crashes are gone

**Comment by efiop** [comment]
@dtrifiro Thank you so much! Releasing new version ASAP.

**Comment by pmrowla** [comment]
confirming that it works for me
```
Python version: 3.8.5
Platform: macOS-10.15.6-x86_64-i386-64bit
```

**Pull request merged**
