### PR TITLE
remote: adds support for s3.list_objects

### PR DESCRIPTION
**Pull request by bwalsh**
Optionally use list_objects, useful for ceph and other s3 emulators
fixes: #1476 

Note:  difficulties locating a useful test to extend for this use case?

### CODE REVIEW

**Comment by bwalsh** [comment]
Running into an issue with the cli

**Comment by efiop** [comment]
@bwalsh looks like it is a bug in our analytics worker. It has spawned an older dvc(that you currently have installed)and it tried to read your config and failed. Your patch itself works great for me.

**Comment by bwalsh** [comment]
* Added extra configuration section so that cli works. https://github.com/bwalsh/dvc/blob/s3-list-objects-v1/dvc/config.py#L206
* Created sibling pr for docs https://github.com/iterative/dvc.org/pull/202
* Smoke tested on our system

**Comment by efiop** [comment]
@bwalsh This was released in 0.31.1, please feel free to upgrade :)

**Pull request merged**
