### PR TITLE
Experiments: allow setting of list parameters

### LINKED ISSUE #4768: Experiments: Modifying parameters in lists
## Description of requested functionality
One of the things I do in my project is define a neural network model as a list of layers in params.yaml. I'm thinking it would be useful to `dvc exp run` and tweak different aspects of the model. However, accessing parameters inside lists is currently not supported. For example:
```yaml
train:
  model:
    hidden_layers:
      - BatchNormalization
      - LSTM:
          units: 32
```
Let's say I want to change the number of LSTM units. I think I should be able to do that with `train.model.hidden_layers.1.units=64`. This currently does not work, and throws an error instead.

I know lists can be tricky, but I will also now open a preliminary PR with a very naïve change that at least allows the command to run. I'm sure more changes and tests will be needed, but I wanted to get the ball rolling :smile_cat: 

## Error Logs
```
2020-10-21 16:59:00,192 ERROR: unexpected error - 'CommentedSeq' object has no attribute 'get'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/usr/local/lib/python3.8/dist-packages/dvc/command/experiments.py", line 419, in run
    self.repo.experiments.run(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 801, in run
    return run(self.repo, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/run.py", line 62, in run
    return repo.experiments.reproduce_one(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 345, in reproduce_one
    stash_rev = self.new(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 38, in wrapper
    return f(exp, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 407, in new
    stash_rev = self._stash_exp(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 265, in _stash_exp
    self._update_params(params)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 309, in _update_params
    _update(data, params[params_fname])
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 299, in _update
    dict_[key] = _update(dict_.get(key, {}), value)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 299, in _update
    dict_[key] = _update(dict_.get(key, {}), value)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 299, in _update
    dict_[key] = _update(dict_.get(key, {}), value)
  [Previous line repeated 1 more time]
AttributeError: 'CommentedSeq' object has no attribute 'get'
------------------------------------------------------------
2020-10-21 16:59:00,284 DEBUG: Version info for developers:
DVC version: 1.8.4 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-5.4.0-51-generic-x86_64-with-glibc2.27
Supports: http, https, s3
Cache types: hardlink, symlink
Repo: dvc, git
```

### PR DESCRIPTION
**Pull request by sjawhar**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Will close #4768

As stated in the issue, I'm sure more work will be needed, but this little tweak was enough to at least allow the experiment to run. Some more work would be required to get parameter diffs to show up nicely in `dvc exp show` (screenshot of current display is included below, see the change in activation function), but that might be out of scope for this issue.

image

If there are no major objections, I can go ahead and write up some tests and finish this PR off proper-like.

### CODE REVIEW

**Comment by pmrowla** [comment]
@sjawhar thanks for identifying this issue and for the PR! This looks like a great start, and worked for me in a test project.

Don't worry about cleaning up the `exp show` display for this PR, we can consider how to address that in the future. For now, lists and dicts being displayed in the string `[..., {..}]` format is at least consistent with other DVC commands (`params diff`/`metrics diff`/etc).

For a test case, a modified version of 
https://github.com/iterative/dvc/blob/33ece011fb1356245605e66d344ccdfd120a73c6/tests/func/experiments/test_experiments.py#L46
should work.

Your test case will just need to generate a `params.yaml` file containing a small list, and when running the stage it would look something like
```
dvc.experiments.run(stage.addressing, params=["foo.<list_index>...=some_value"])
```

**Comment by sjawhar** [comment]
OK, test added. Thanks for pointing me to the right spot, that made it super easy for me :pray:

**Comment by sjawhar** [comment]
I've been thinking about this and wondering if there's an opportunity to simplify things and delete a bunch of code by using something like https://github.com/fabiocaccamo/python-benedict. If the existing project params were instantiated as a benedict instance, then you could do stuff like `params['foo.bar[0].bar'] = 1` with no fuss:
```python
>>> from benedict import benedict
>>> params = benedict({'foo': { 'bar': [{'baz': 3}, 2]}})
>>> params['foo.bar[0].baz']=1
>>> params
{'foo': {'bar': [{'baz': 1}, 2]}}
```

**Review by pmrowla — APPROVED** [review]

**Comment by pmrowla** [comment]
Thanks for the PR! 🙏 

The suggestion regarding benedict is interesting and we could potentially consider using something like that in the future. If you'd like to file a separate feature request for it that would be great

**Pull request merged**
