### PR TITLE
exp queue: implement `dvc queue logs`

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Related to https://github.com/iterative/dvc/issues/7854, https://github.com/iterative/dvc/issues/7590

* Adds `dvc queue logs [-f/--follow]` command
* Removes `dvc queue attach`

[asciicast](https://asciinema.org/a/PA8Y8fyjlcVDSdO1aPiIiBIM2)

### CODE REVIEW

**Comment by dberenbaum** [comment]
This isn't a blocker, but we should provide a more helpful error when trying to get the logs for an experiment still in the queue:

```console
$ dvc exp show
 ──────────────────────────────────────────────────────────────────────────────────────>
  Experiment                Created        State    avg_prec   roc_auc   prepare.split >
 ──────────────────────────────────────────────────────────────────────────────────────>
  workspace                 -              -           0.925   0.94602   0.2           >
  10-bigrams-experiment     May 19, 2022   -           0.925   0.94602   0.2           >
  ├── 3911349 [exp-cb6ca]   02:48 PM       -         0.91243    0.9372   0.35          >
  ├── deef20c [exp-94dbd]   02:47 PM       -         0.91856   0.94113   0.25          >
  ├── 0f98f46 [exp-78733]   02:47 PM       -         0.92968   0.95151   0.15          >
  ├── 2620d5b [exp-8a4db]   02:47 PM       -         0.92664   0.94595   0.05          >
  ├── bdaac35               02:48 PM       Queued          -         -   0.55          >
  ├── eeca4d6               02:48 PM       Queued          -         -   0.65          >
  └── 4e2927f               02:48 PM       Queued          -         -   0.45          >
 ──────────────────────────────────────────────────────────────────────────────────────>
$ dvc queue start
Start 1 queue worker to process the queue tasks
$ dvc queue logs 4e2927f
ERROR: '4e2927f' are not valid queued experiment names
```

**Comment by dberenbaum** [comment]
Is there any way to indicate how to safely exit (besides in help/docs)? It feels scary to interrupt if you are in the middle of a long-running experiment.

**Comment by dberenbaum** [comment]
Should we remove `dvc queue attach` as part of this PR?

**Comment by dberenbaum** [comment]
Like https://github.com/iterative/dvc/issues/7591#issuecomment-1149211215, it doesn't accept assigned experiment names for checkpoint experiments:

```console
$ dvc exp show
 ──────────────────────────────────────────────────────────────────────────────────────>
  Experiment                Created        State     Executor    step      loss   accur>
 ──────────────────────────────────────────────────────────────────────────────────────>
  workspace                 -              Running   workspace      -         -        >
  dvc                       May 27, 2022   -         -              -         -        >
  ├── 24747fc [exp-10cc0]   03:25 PM       Running   temp           0    1.3277     0.7>
...
$ dvc queue logs -f exp-10cc0
ERROR: 'exp-10cc0' are not valid queued experiment names
```

**Comment by pmrowla** [comment]
> This isn't a blocker, but we should provide a more helpful error when trying to get the logs for an experiment still in the queue:

We now generate a better message:

```
$ dvc queue logs 6acd74
ERROR: Experiment '6acd74' is in queue but has not been started
```

> Is there any way to indicate how to safely exit (besides in help/docs) from `dvc queue logs -f`? It feels scary to interrupt if you are in the middle of a long-running experiment.

When using `-f` we now output a message telling the user they can safely Ctrl+C

```
$ dvc queue start
$ dvc queue logs -f 6acd74
Following logs for experiment '{rev}'. Use Ctrl+C to stop following logs (experiment execution will continue).

'data/data.xml.dvc' didn't change, skipping
Stage 'prepare' didn't change, skipping
Running stage 'featurize':
> python src/featurization.py data/prepared data/features
The input data frame data/prepared/train.tsv size is (20017, 3)
^C 
```

**Review by karajan1001 — APPROVED** [review]

**Review by dberenbaum — APPROVED** [review]

**Pull request merged**
