### PR TITLE
checkout: delete output if we can't create it fully

### LINKED ISSUE #9618: `dvc checkout` creates empty directories
After #9444, `index.checkout` creates empty directories that were not created with `hashfile.checkout`.

This is causing that after a `dvc checkout`, dependencies previously reported as `deleted` are being reported as `modified`

Reproduction with https://github.com/iterative/example-get-started-experiments:

- Before #9444

```console
$ dvc exp run
Reproducing experiment 'myoid-lich'                                   
Verifying data sources in stage: 'data/pool_data.dvc'                                                                                               
ERROR: failed to reproduce 'data/pool_data.dvc': missing data 'source': data/pool_data
```

- After #9444

```console
$  dvc exp run
Reproducing experiment 'peart-gest'                                   
Verifying data sources in stage: 'data/pool_data.dvc'                                                                                               
WARNING: 'data/pool_data' is empty.                                                                                                                 
WARNING: 'data/pool_data' is empty.     
Running stage 'data_split':                                                                                                                         
```

We should not try to run `data_split`, which depending on the user code might fail or continue silently when having an empty dir as dependency

### PR DESCRIPTION
**Pull request by efiop**
Matches previous behaviour before migrating to `index.checkout`. Previously we would validate cache and not create the output at all. Now we try to create what we can, but if we fail for any reason (might be anything from missing cache, being out of free space, etc) we just delete the output to revert the changes and not make it look like it is supposed to be partial.

Fixes #9618

### CODE REVIEW

**Comment by dberenbaum** [comment]
Thanks for the quick fix @efiop! What happens on `dvc pull --allow-missing`?

**Comment by efiop** [comment]
@dberenbaum Same as before. If we don't have complete cache - we don't create the output and `--allow-missing` just means that we will not error-out.

**Comment by dberenbaum** [comment]
I can open a separate issue, but I'm seeing that I still get an error with `--allow-missing`. I also thought it was supposed to keep as much as possible if there's partial data. FWIW, the behavior now matches the behavior when it was released in https://github.com/iterative/dvc/pull/9071 (cc @daavoo). Am I missing something? 

```
$ dvc pull --allow-missing
ERROR: failed to transfer '00af61152b631a3cbcc1cf0e6d5023f6' - [Errno 2] No such file or directory
ERROR: failed to transfer '006413da232322e4b67f453543140eec' - [Errno 2] No such file or directory
ERROR: failed to pull data from the cloud - 3 files failed to download

$ echo $?
1

$ dvc doctor
DVC version: 3.1.1.dev14+ge99549209.d20230622
---------------------------------------------
Platform: Python 3.11.4 on macOS-13.4-arm64-arm-64bit
Subprojects:
        dvc_data = 2.3.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3.dev0+g635eaff.d20230621
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        azure (adlfs = 2023.4.0, knack = 0.10.1, azure-identity = 1.13.0),
        gdrive (pydrive2 = 1.15.4),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 12.0.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76),
        ssh (sshfs = 2023.4.1),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: /Users/dave/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/6414c2ff59800d13bb7dc40946807396
```

**Comment by efiop** [comment]
@dberenbaum That logic wasn't changed as part of checkout (we just pass allow_missing straight to checkout in pull), but maybe something changed in fetch in the way we handle errors. I can't reproduce your particular case (seems like it is failing during fetch, but FileNotFounderror shouldn't happen as it is supposed to be caught during comparison of cache and remote). Mind showing verbose log, please?

**Pull request merged**
