### PR TITLE
exp: Update `--rev` to support `append` action.

### LINKED ISSUE #9390: Being able to call  `exp show` with multiple branches (`--rev`) and a number of commits (`-n`)
In the VS Code extension, we would like to show multiple branches at the same time in the table. Each with its own number of commits. We're currently doing this by calling `exp show` once per branch (`dvc exp show --rev main -n 5`, `dvc exp show --rev other-branch -n 3`...). We'd like to be able to do this in one call only (something like `dvc exp show --rev main -n 5 --rev other-branch -n 3...`). Would it be possible?

### PR DESCRIPTION
**Pull request by daavoo**
Closes #9390

### CODE REVIEW

**Comment by daavoo** [comment]
> Would it be possible to specify the number of commits for each rev also?

To you mean separately? You can specify `--num` but the same value will be applied to all the passed `rev`

**Comment by sroy3** [comment]
> > Would it be possible to specify the number of commits for each rev also?
> 
> Do you mean separately? You can specify `--num` but the same value will be applied to all the passed `rev`

Yes, separately (ex.: only 1 for a branch and 5 for the other one)

**Comment by daavoo** [comment]
> > > Would it be possible to specify the number of commits for each rev also?
> > 
> > 
> > Do you mean separately? You can specify `--num` but the same value will be applied to all the passed `rev`
> 
> Yes, separately (ex.: only 1 for a branch and 5 for the other one)

That would require additional work both on the CLI level and the internal API level

**Comment by daavoo** [comment]
> Yes, separately (ex.: only 1 for a branch and 5 for the other one)

BTW, it would require you to build a more convoluted set of args, but with this P.R. you could achieve that behavior using git suffixes, like:

```console
$ dvc exp show \
--rev main --rev main~1 \
--rev other-branch --rev other-branch~1 --rev other-branch~2 ...
```

**Comment by sroy3** [comment]
> > Yes, separately (ex.: only 1 for a branch and 5 for the other one)
> 
> BTW @sroy3 , it would require you to build a more convoluted set of args, but with this P.R. you could achieve that behavior using git suffixes, like:
> 
> ```
> $ dvc exp show \
> --rev main --rev main~1 \
> --rev other-branch --rev other-branch~1 --rev other-branch~2 ...
> ```

It's not doing quite the same thing. It's showing the nth previous commit instead of show n previous commits.

**Review by sroy3 — APPROVED** [review]

**Review by pmrowla — APPROVED** [review]

**Pull request merged**
