### PR TITLE
build_deb: Issue #2800

### PR DESCRIPTION
**Pull request by Abrosimov-a-a**
Debian packaging system. Issue Issue #2800

* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [x] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by Abrosimov-a-a** [comment]
@efiop Sure! As you wish.

**Comment by efiop** [comment]
@Abrosimov-a-a Great! Let's move it there then. Could you please submit a PR to https://github.com/iterative/dvc-s3-repo ? As a first iteration, you could simply move your code there, then we could merge it and then work on top of it to tie it all together.

**Comment by Abrosimov-a-a** [comment]
@efiop Will you fix your scripts in dvc-s3-repo yourself?

**Comment by efiop** [comment]
@Abrosimov-a-a Would definitely appreciate some help there if you have time and feel like working on that 🙂Btw, do you have any experience with rpm packing by any chance?

Closing this PR for now, since dvc-s3-repo one got merged.

**Pull request closed without merging**
