### PR TITLE
status: --quiet reflects changes on its exit code

### LINKED ISSUE #1519: status: consider using return code for state indication in a quiet mode
As suggested by @robogeek

```
The dvc status --quiet option.  As expected it does not produce output for a workspace that has changed files.  I had expected the exit status of the command would be non-zero, but the exit status is zero.

That is::

$ dvc status
matrix-train.p.dvc
    deps
        changed:  code/featurization.py

$ dvc status --quiet
$ echo $?
0


So... what does --quiet do other than suppress output?

It is common in other tools for a --quiet option to indicate something via the exit status.
```

```
If dvc status -q set its exit status, then a shell script (or equivalent) could do 

if dvc status -a; then
     do something like dvc repro
fi

I'm not understanding the purpose of the -q option if there's no silent way to learn the status
```

Currently `dvc status` behaves as `git status`, in that it doesn't change its return code depending on the state of the project. But it would indeed be very helpful for scripts to have an ability to use dvc exit code to easilly determine if there are any unsaved changes. Maybe we could do something similar to `git diff` which has `--exit-code` option, and `-q` option implies `--exit-code`.

### PR DESCRIPTION
**Pull request by mroutis**
Fix #1519

### CODE REVIEW

**Comment by efiop** [comment]
Thank you!

**Comment by efiop** [comment]
@mroutis Forgot about one more thing. We should mention this behaviour in a help message as well as update docs at https://dvc.org/doc/commands-reference/status . Could you please send patches for that?

**Comment by robogeek** [comment]
@efiop I am about to update the status documentation, so if you explain the details I can put it in the documentation.  Currently I've written this explanation:

```
* `-q`, `--quiet` suppresses all output.
```

**Comment by efiop** [comment]
@robogeek Now `-q` will also make `dvc status` return non-zero return code if repo is not up-to-date. Same as you've originally suggested on discord. Thanks a lot for all of your great suggestions by the way :)

**Comment by mroutis** [comment]
Sorry, @efiop , @robogeek ; I updated the docs directly (without any PR), here's the commit:
https://github.com/iterative/dvc.org/commit/07a40e26c6f8ac99d44c93d0a9ead343ff166e01

I'll send a patch to add the same description to the `--help` message

**Comment by efiop** [comment]
@mroutis No worries :) Thank you!

**Pull request merged**
