### PR TITLE
gha: don't build binary packages

### PR DESCRIPTION
**Pull request by efiop**
The build process is much more stable these days and there is no reason to keep building these packages here. Instead every package has itsown building process (dvc-osxpkg, dvc-exe, dvc-s3-repo) and knows best how to build and sign correctly.

pyinstaller hooks need to go into a `__pyinstaller` later on.

### CODE REVIEW

**Comment by skshetry** [comment]
Let’s get rid of scripts directory altogether.

**Comment by efiop** [comment]
@skshetry That's the plan, but need to move hooks to `__pyinstaller` first. Nothing urgent, just didn't want to keep patching timeouts and stuff.

**Comment by 0xpablo** [comment]
Hi @efiop, the packages were super useful to us to reduce CI times. On macOS, installing DVC via brew takes over 4 minutes, whereas installing the package takes less than 10 seconds.
Is there any other alternative so that the install process is fast?

I was actually coming here to open a PR to generate the apple silicon package as well and was surprised to see the packages gone.

Thanks in advance!

**Comment by efiop** [comment]
@0xpablo Oh, sorry for the confusion. Those packages were really only meant for testing. We actually build proper packages that are signed and stuff in other repos and they are all available through https://dvc.org/ (see download button, it will give you links like `https://dvc.org/download/linux-deb/dvc-3.2.1` that you can use).

The apple package is created in https://github.com/iterative/dvc-osxpkg . Overall, here are the repos:

https://github.com/iterative/dvc-osxpkg
https://github.com/iterative/dvc-exe
https://github.com/iterative/dvc-s3-repo (for deb and rpm)

The first two are private as they have some sensitive keys for signing stuff and I was a bit overly cautious, but since there is demand and you are keen on contributing, I will make them public in a sec (just need to double check I didn't do anything stupid there).

**Comment by efiop** [comment]
Ugh, need a bit more time than a sec, will make them public in an hour or so.

**Comment by 0xpablo** [comment]
Thanks for the clarification and support @efiop. Once the macOS one is public I’ll see if I can add support for Apple Silicon. In the meantime I’ll switch to the public downloads and use Rosetta. 

Thank you!

**Comment by efiop** [comment]
@0xpablo All are public now. Regarding the build process, note that we still (temporarily) use scripts/pyinstaller/build.py to build the "binary" (it is a dir really) and you will likely need to run pyinstaller there in dvc-osxpkg directly because you'll need to specify --target-architecture in either cmdline args or the spec file. Just wanted to note that that is totally expected and no one will object that.

**Comment by efiop** [comment]
@0xpablo If you are still interested in contributing, note that pyinstaller related code is now in dvc-osxpkg https://github.com/iterative/dvc-osxpkg/blob/main/build_bin.py

**Pull request merged**
