### PR TITLE
pygit: force release of odb contexts after checkout/merge

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Will close https://github.com/iterative/dvc/issues/5641

### CODE REVIEW

**Comment by pmrowla** [comment]
@werthen @FredericoCoelhoNunes can you try installing from this PR to see if it resolves your issue w/`dvc exp run --temp` or `--queue`+`--run-all` on NFS mounts

It can be installed via pip with:
```
pip install git+https://github.com/iterative/dvc.git@refs/pull/5849/head
```

**Comment by FredericoCoelhoNunes** [comment]
Hi @pmrowla , it did indeed seem to fix the problem for me! Fantastic work.
`dvc exp show` fails with `ERROR: unexpected error - 'NoneType' object is not subscriptable` immediately afterwards `dvc exp run --run-all`, but I think that's addressed here: https://github.com/iterative/dvc/issues/3434 (doesn't appear to be related with the issue at hand, but I thought it would be worth mentioning just in case).

**Comment by werthen** [comment]
I will also test this tomorrow, have had little time to do so.

**Comment by efiop** [comment]
@pmrowla What's the status on this one?

**Comment by pmrowla** [comment]
> @pmrowla What's the status on this one?

@efiop 

Was waiting on @werthen's test since they filed the original review, but given that we've had several other people confirm the fix works in discord I think we can merge this

**Comment by werthen** [comment]
For what it's worth, I also performed a test and it seems to be working as intended now. Thanks!

**Pull request merged**
