### PR TITLE
introduce hyper parameters and config

### PR DESCRIPTION
**Pull request by elgehelge**
Part of #3393

### CODE REVIEW

**Comment by dmpetrov** [comment]
I did some basic testing. It looks really good! Thank you @elgehelge and @efiop!

Some issues that I was able to find:

1. Params list formatting should be human-readable like `Parameter lr1, dropout are missing ...`
```
$ dvc run -p lr1 -M metrics.json -f Dvcfile python train.py
Running command:
	python train.py
ERROR: failed to run command - Parameters '{'lr1'}' are missing from 'params.yaml'.
```

2. How to define nested params `train.lr`?
```
$ cat params.yaml
train:
    lr: 0.0041
    layers: 9
    dropout: 0.21

processing:
    th: 0.98
    bow: 7000

$ dvc run -p train.lr -M metrics.json -f Dvcfile python train.py
Running command:
	python train.py
ERROR: failed to run command - Parameters '{'train.lr'}' are missing from 'params.yaml'.
```

3. Can I redefine the params file name (or not in this change)?

**Comment by efiop** [comment]
> Params list formatting should be human-readable like Parameter lr1, dropout are missing

Formatting issue, fixed.

> How to define nested params train.lr?

Added support for basic `a.b.c` params support. Wildcards and more advanced things will be introduced later.

> Can I redefine the params file name (or not in this change)?

Yes, `-p path/to/params:param1,param2`.

**Comment by efiop** [comment]
Thank you @elgehelge ! :pray:

**Comment by shcheklein** [comment]
@elgehelge @efiop do we have docs coming for this?

**Comment by efiop** [comment]
@shcheklein Not yet, this was just the first step. Docs will be later.

**Comment by jorgeorpinel** [comment]
Hi. So this is a hidden feature for now?

**Comment by efiop** [comment]
@jorgeorpinel Just unfinished and undocumented on dvc.org. Not hidden.

**Pull request merged**
