### PR TITLE
docs: add some docstrings about computing status

### PR DESCRIPTION
**Pull request by mroutis**
Splitting #2044 in two PR's, one for the docstrings and the other for the actual implementation.

### CODE REVIEW

**Comment by shcheklein** [comment]
I'm totally fine with docs 👍  On the other hand, in my experience if code is written well you don't need that much docs. Usually, you need some comments in some really advanced cases. So, if it was very hard for you to read and understand the existing code then I would say it smells and I would try to think what exactly was clear and how we can improve it - rename functions, split them, introduce classes or remove classes etc. It's not a suggestion for changing this specific PR, neither I'm trying to discourage you writing them.

**Comment by shcheklein** [comment]
another thing to keep in mind - comments must be supported like the code itself, if we have a lot them we will be spending time on each refactoring managing them

**Comment by mroutis** [comment]
@shcheklein, can't agree more with you, but even to refactor something you first need to understand what's going on, I'd say that this is a good step to further make the intention crystal clear :smiley:

**Comment by shcheklein** [comment]
@mroutis sure! but ideally code itself should serve as documentation :) (and sometimes tests should help to see that you haven't broken anything along the way)

**Pull request merged**
