### PR TITLE
ssh: add gss_auth option

### PR DESCRIPTION
**Pull request by JoshuaPostel**
This is my proposed implementation of #2327.

If the user has a valid kerberos ticket (generated with [`kinit`](https://web.mit.edu/kerberos/krb5-1.12/doc/user/user_commands/kinit.html)), this feature allows `dvc` to interact with the remote machine without asking the user to type in their password or hard code their password in `.dvc/conf`.

After reading a bit more about kerberos, passing the keytab file no longer made sense to me.  I did not include the `gss_kex` option for paramiko, as I imagine users will trust the server they specify and I did not deem it necessary.  However, I do not fully understand GSS-API key exchange and someone with more knowledge may know better.  

I included a simple unit test, however, it is not clear to me how to write a functional test for this feature.  If details about my manual testing are needed, please let me know. 

Associated documentation PR: [#578](https://github.com/iterative/dvc.org/pull/578)

### CODE REVIEW

**Comment by efiop** [comment]
Hi @JoshuaPostel ! Thank you so much for this PR! Could you confirm that it works for you in a real-world scenario, please? It isn't very clear from the PR description :slightly_smiling_face:

**Comment by efiop** [comment]
@JoshuaPostel Btw, looks like your commits have an email jpostel1@ford.com that is not listed in your github profile, so it is not able to link it properly to your profile. Please go to your profile settings -> Emails and add jpostel1@ford.com to the list. :slightly_smiling_face:

**Comment by JoshuaPostel** [comment]
@efiop Yes, this works in my real world scenario.  Difficult to make a reproducible test though.

Ill have to reconcile the email address.  I would prefer it point to my personal email, sorry about that.

**Comment by efiop** [comment]
@JoshuaPostel Thank you! No need for reproducible test in this case. Unit test and your real-world confirmation are enough.

> Ill have to reconcile the email address. I would prefer it point to my personal email, sorry about that.

So you want to adjust it and force-push the PR, right? If so, please ping me when you are done with it, so I could merge this. :slightly_smiling_face:

**Comment by JoshuaPostel** [comment]
@efiop I've decided to add jpostel1@ford.com to my github account.  Feel free to merge.

**Comment by efiop** [comment]
@JoshuaPostel Thank you! :tada:

**Comment by efiop** [comment]
@JoshuaPostel 0.57.0 with your patch is out. Please feel free to upgrade :slightly_smiling_face:

**Comment by JoshuaPostel** [comment]
Thanks for all the help @efiop!  

One thing that I should have realized/mentioned earlier is that [the change in `setup.py`](https://github.com/iterative/dvc/blob/86c3cb785cdfc893eb09b46450217bbb56730de5/setup.py#L78) adds [`gssapi`](https://pypi.org/project/gssapi/) as a requirement, which in turn requires:
>   A working implementation of GSSAPI (such as from MIT Kerberos) which includes header files

**Consequences:**
* Linux
  This can lead to errors when running `pip install dvc[ssh]` such as `ERROR: /bin/sh: 1: krb5-config: not found`.  [Others have experienced](https://stackoverflow.com/questions/30896343/how-to-install-gssapi-python-module) this when running `pip install gssapi` and the answer it pretty straight forward: `apt-get install libkrb5-dev`. 
* Mac OS
  I do not have access to a Mac to test this, however, I think it should be fine since it looks like [Mac's come with kerberos installed](http://computing.help.inf.ed.ac.uk/kerberos-mac-os-x).
* Windows 
  I tested `pip install[ssh]` on a windows 10 machine and it worked, however, I would want to test it on more machines first

I wanted to make you aware of this incurred dependency, and I understand if you would prefer not to add it to `dvc[ssh]`.  Sorry about discovering this after the merge.

**Comment by efiop** [comment]
@JoshuaPostel Indeed, I was thinking it would at least not fail while installing :slightly_frowning_face: We could simply make it optional though. With something like `pip install dvc[ssh,gssapi]` or `pip install dvc[ssh_gssapi]` or `pip install dvc[gssapi]`(this one might be a bit too generic, since hdfs also will support it, right?). I guess `ssh_gssapi` is the best one. What do you think?

**Comment by efiop** [comment]
Btw, @JoshuaPostel we've started using pyarrow for our hdfs remotes, which seems to support kerberos. I remember you've been asking about it, maybe you would be interested in taking a look at implementing that? Should be pretty straightforward, especially since you've already implemented the config option in this PR :wink:

**Comment by shcheklein** [comment]
@efiop we should think about the conda package as well. We include all dependencies now into the package.

btw, does this error mean that there are no wheels for some library?

A workaround can be to do the same trick as with ps-utils and detect it independently?

**Comment by JoshuaPostel** [comment]
@efiop I like `dvc[ssh,gssapi]` and `dvc[ssh_gssapi]`, but ill leave that up to you.

Awesome to hear about pyarrow!  Ill look into it, but Ill be out of town next week, so it wont be right away.

**Comment by efiop** [comment]
@shcheklein Our conda package depends on paramiko conda package, which doesn't include gssapi at all https://github.com/conda-forge/paramiko-feedstock/blob/master/recipe/meta.yaml , so it simply won't work. Not sure if paramiko throws a meaningful error when there is no gssapi installed and someone tries to use it, @JoshuaPostel , maybe you could check how the error looks like? On our side there are no actions required in the conda package itself, but we definitely need to document that.

> btw, does this error mean that there are no wheels for some library?

Yes, there are no linux or mac wheels https://pypi.org/project/gssapi/#files

> A workaround can be to do the same trick as with ps-utils and detect it independently?

Yes, that would work as well, but this time it makes sense to just make it a regular optional dependency.

So for now, gssapi will only be accessible as an option through pip package(and probably brew formula), we definitely won't be able to include it into our binary packages or core dependencies until there are wheels for every platform.

**Comment by efiop** [comment]
Alright, after a bit more thinking, it makes sense to just indeed it optional like psutil, just like @shcheklein suggested, so we don't rush with creating unneeded installation options for dvc. So to enable it, you will have to `pip install 'dvc[ssh] gssapi`. Created https://github.com/iterative/dvc/pull/2429

**Comment by efiop** [comment]
Jumped the gun on that one :) Looks like dependencies for paramiko[gssapi] are not that trivial https://github.com/paramiko/paramiko/blob/master/setup.py#L78 , so instructions would look more like
```
pip install 'dvc[ssh]' paramiko[gssapi]
```
which isn't bad, but at that point
```
pip install 'dvc[ssh_gssapi]'
```
feels better. Also, an interesting detail is that gssapi package is not even listed as a dependency in paramiko[gssapi] on windows https://github.com/paramiko/paramiko/blob/master/setup.py#L80 . Not quite sure why, but I guess we'll have to figure that one out along the way later.

**Comment by JoshuaPostel** [comment]
>  Not sure if paramiko throws a meaningful error when there is no gssapi installed and someone tries to use it, @JoshuaPostel , maybe you could check how the error looks like?

```
$ python test_ssh.py
Unknown exception: Unable to import a GSS-API / SSPI module!
Traceback (most recent call last):
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/auth_handler.py", line 304, in _parse_service_accept
    sshgss = GSSAuth(self.auth_method, self.gss_deleg_creds)
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/ssh_gss.py", line 107, in GSSAuth
    raise ImportError("Unable to import a GSS-API / SSPI module!")
ImportError: Unable to import a GSS-API / SSPI module!

Traceback (most recent call last):
  File "test_ssh.py", line 8, in <module>
    gss_auth = True)
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "/home/jpostel1/envs/base/lib/python3.6/site-packages/paramiko/transport.py", line 1570, in auth_publickey
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

**Comment by efiop** [comment]
Thanks @JoshuaPostel ! We could add a wrapper on top of it, but unfortunately, it is raising a generic exception with no good way to detect the real cause, so it would be a lot of hustle trying to guess it. We have it listed in docs, so it should do for now.

**Comment by JoshuaPostel** [comment]
Looks like the proper solution to me.  Thanks a bunch for the extra work getting this to integrate properly.

**Pull request merged**
