### PR TITLE
pydantic model for dvc.yaml

### PR DESCRIPTION
**Pull request by skshetry**
Can be useful on comparing with voluptuous schema. Is compatible with pydantic both v1 and v2.

For now, it's only for playing around, and does not replace voluptuous based schema or dvcyaml-schema that is used in vscode. 

cc @aguschin

### CODE REVIEW

**Comment by efiop** [comment]
@skshetry Is this intended to be ready for review? What's the purpose/user for adding this on the side as dead code?

**Comment by skshetry** [comment]
> Is this intended to be ready for review? What's the purpose/user for adding this on the side as dead code?

Eventually, I want this to be a foundation for parsing `dvc.yaml`/`dvc.lock`/`.dvc` files.
voluptuous based schema is getting complicated to maintain and is very hard to understand.
And that whole code is just for validation. We still need separate data structures, parsing logic, etc.

We also have some needs in parametrization, where we want to know the type of some fields at runtime, which is not possible today. And we are already maintaining something like this in `dvcyaml-schema`.

That's a lot of things, which pydantic may or may not be able to fulfil, but I wanted to at least experiment. Also wanted to test pydantic2 and compare performance with voluptuous based schema. 

> Is this intended to be ready for review

This is more or less ready for review. The validation errors may be confusing, but that's not the point of this PR.

**Comment by efiop** [comment]
@skshetry Can we just add this once we actually are going to use it? I'm really hesitant to add such a dead code without any purpose. Seems like you can do the testing that you want without merging this into the upstream.

**Comment by skshetry** [comment]
> Can we just add this once we actually are going to use it? I'm really hesitant to add such a dead code without any purpose. Seems like you can do the testing that you want without merging this into the upstream. Or do you need it in upstream specifically?

If it's not going to get merged here, this is going nowhere, and will have the same fate as https://github.com/iterative/dvc/pull/5531. This is experimental for now, and the changes that are needed are too many that it is hard to keep up in my own fork. Neither we will be able to convince spending time on something that is not upstream (it's already hard to do that in upstream).

It is easy to keep parity between two schema for the time being. I won't make any promises here, and if it ends up going nowhere, it'll definitely be a replacment for `dvcyaml-schema`.

**Comment by dberenbaum** [comment]
I see positive reactions from @aguschin and @daavoo here. Any thoughts from you or the rest of @iterative/dvc on this one?

I'm adding it to items to discuss in refinement in case it doesn't get resolved by then so it doesn't get stuck in limbo.

**Comment by skshetry** [comment]
> No one except for you will probably even remember to update it for parity. Overall feels like dead code

Tbh I have been the de-facto maintainer of the file parsing in dvc and in dvcyaml-schema, which should not be this way, but unfortunately that is the case.

I don't quite understand the "dead code" argument, I think I have been honest with that this being experimental, and the direction I want the subsystem to take in.

A lot of things that needs to be solved here are technical. If it was a solved problem, I would have come with a giant PR. Also, we have a lot of complexity and UI requirements (think of nicer error messages that we return today) that it is not possible to do in one shot. I am being conservative here.

It'll gradually be worked on. (Isn't everything a dead code that is in an active development? 😄 

I'm happy to discuss on this on technical merits.

**Comment by efiop** [comment]
@skshetry Your work is appreciated, it really is. I'm just trying to understand the plan for this, as I have no idea where this is going to go. Can you lay down a plan in an issue or something with purpose and steps to achieve it? (the steps could be vague, that's fine). If you only want to migrate from voluptuous to pydantic, shouldn't that be doable reasonably fast, as it is just swapping one library for another? Or am I not understanding the complexity or scope or other changes?

**Comment by SoyGema** [comment]
Under a context that is not relevant to this conversation and without being aware of this specific initiative , maybe worth citing that found  that [voluptuous](https://pypi.org/project/voluptuous/) is no longer actively maintained and failing with [pip-rating](https://github.com/Nekmo/pip-rating) . This could nudge the decision beyond any DVC functionality and add a maintenance dimension to the  discussion. 


Captura de pantalla 2023-10-20 a las 16 41 26

**Comment by dacbd** [comment]
FTR, I'm also in favor of consolidating validation tooling around pydantic.

**Pull request closed without merging**
