### PR TITLE
perf: lazy imports

### PR DESCRIPTION
**Pull request by Suor**
This saves on startup time. And some things will never be loaded at all.

### CODE REVIEW

**Comment by efiop** [comment]
Expected, but bad news are that pyinstaller is not able to see these lazy imports: e.g. there is no hook-google* in https://travis-ci.com/iterative/dvc/jobs/234880098 but there is in https://travis-ci.com/iterative/dvc/jobs/234872528#L628 . So our pyinstaller binaries will be broken. One obvious way to workaround that is to write hook-dvc that will include these hidden imports, which will make it even harder to maintain. 🙁 

@Suor Do I remember correctly, that is speedup only applies to source packages, and wheels are not affected? Or was it about entry_points patch?

**Comment by Suor** [comment]
This was about fast entry points only.

**Comment by Suor** [comment]
What if we add 
```Python
if False:
    import google.cloud.storage
```

**Comment by efiop** [comment]
@Suor That might work, but that is an awful hack 😄 If choosing between this and writing hook-dvc and listing these there, I would much rather choose the former.

**Comment by efiop** [comment]
@Suor And if we are going `if` route, then we could simply dynamically import what we need without lazy_import. That would be the simplest way to achieve the same with minimal maintenance hustle.

**Comment by Suor** [comment]
I would say this is better than a hook. If you need to duplicate things at least keep them close, this way you won't forget to update/remove them in sync.

**Comment by efiop** [comment]
@Suor One will forget. Using lazy_import and `if False` and string in `_get`(like you've suggested), is a lot to keep in mind. With dynamic import, you import it once in the body of the Remote class, which is really simple and really simple to check.

**Comment by efiop** [comment]
@Suor I think you are overcomplicating things here. The use case is really simple, and we should try  the approach that we've discussed initially: dynamically importing packages. As far as I see, the only obstruction to doing that in Remote is _get function in `dvc/remote/__init__.py`, which relies on `Remote.supported()` (for which we always need to try and import every dep), but that could be solved by simply migrating to relying on url schema to do initial filtering and only then checking if needed deps exist.

**Comment by Suor** [comment]
How do we use dynamic imports here? Those things imported are used in class definition in `REQUIRES`, so it's either lazy import or strings and a string import later. Unless you want to add something like to each class:
```python
@staticmethod
def requires():
    try:
        import pyarrow
        return True
    except ImportError:
        return False
```
If you add `if False` next to lazy import:

```python
pyarrow = lazy_import('pyarrow', silent=True)
if False:
    import pyarrow
```

Then it's hard to break a coordinated change or removal unlike with hooks. 

On `_get()` you will need either lazy imports or string imports, unless you are propsing something like:
```python
if scheme == 's3':
    from dvc.remote.s3 import RemoteS3 as RemoteCls
elif scheme == 'gs':
    from dvc.remote.gs import RemoteGS as RemoteCls
elif scheme == 'ssh':
    from dvc.remote.ssh import RemoteSSH as RemoteCls
elif ...
```

**Comment by Suor** [comment]
Using string imports in all `_get()`s and leaving things unchanged for `dvc.remote.*py` files may work. This is not ideal though, since we have code like `dvc.api.get_url()` that requires remote instantiation, but doesn't require backend lib.

**Comment by Suor** [comment]
**P.S.** Looks like backend lib will be loaded on remote instantiation anyway during `REQUIRES` check. We might want to delay that to actual usage.

**Comment by efiop** [comment]
@Suor Sorry for the delay. That sounds like it would work in a simple way. If backend lib is loaded already and no one noticed it on get_url, then maybe just it leave like that for now too. So we could try those dynamic imports, right?

**Comment by Suor** [comment]
@efiop we don't know whether anyone noticed. And dynamic imports are not the option unless you want something like:
```python
@staticmethod
def requires():
    try:
        import pyarrow
        return True
    except ImportError:
        return False
```
So it's either lazy imports or string imports. 
- lazy imports: how it is done in this PR
- string imports: revert lazy imports, use string imports in all `_get()`s.

**Comment by efiop** [comment]
@Suor Ok, so with string imports, everything will stay the same, except `_get` will use strings to import things, right? Unlike with lazy imports, pyinstaller should still work ok. Also there will be no special constructions required except strings in _get, and remote.py files will look and feel normal. Correct? Or am I missing something?

**Comment by Suor** [comment]
@efiop Correct, we should be careful though not to import remote files unless we need them, so this would be easier to break. Should not be a big issue if we only use them via dicts next to `_get()`s.

**Comment by efiop** [comment]
@Suor Sounds good.

**Comment by Suor** [comment]
So strings imports strategy won't work:
- one sometimes need to import things to only use class attributes
- outputs subclass each other, e.g. `class OutputGS(OutputS3)`, which means if we use GS we will load both GS and S3 libs.

**Comment by Suor** [comment]
So we are back to lazy imports.

**Comment by efiop** [comment]
@Suor 
> one sometimes need to import things to only use class attributes

Could you elaborate, please?

> outputs subclass each other, e.g. class OutputGS(OutputS3), which means if we use GS we will load both GS and S3 libs.

It is because output/s3.py loads RemoteS3 for OutputS3.REMOTE? Couldn't we make that a property so it loads dynamically?

**Comment by Suor** [comment]
> Could you elaborate, please?

Like here https://github.com/iterative/dvc/blob/70efa6c52acc087750ab80c2e3ff0e06a290b766/dvc/stage.py#L402

> It is because output/s3.py loads RemoteS3 for OutputS3.REMOTE? Couldn't we make that a property so it loads dynamically?

It's a class attribute, so we will need a class property, which is doable, but not something Python provides by default.

Overall these are many more complications than lazy imports. The alternative to lazy imports which I see is strings requires plus dynamic imports. Which is compared to lazy imports:
cons:
    - things are mentioned in 2-3 not connected places in a remote definition
    - no general way to use for non-remotes like lazy imports (dynamic imports will work part of the time)
pros:
    - no `if False` hack
    - `REQUIRES` becomes a simple list of string names of required modules

**Comment by Suor** [comment]
BTW, we should still get rid of `Remote*.supported()` loop.

**Comment by Suor** [comment]
Another thing with string imports strategy is that is incredibly fragile, since you can import some output, dep or remote class implicitly very easily. I didn't realize it when I started, but now I see that it is done all over the code.

**Comment by efiop** [comment]
@Suor Btw, Remote.supported() doesn't really import anything, it only checks schema.

I've created a quick patch https://github.com/iterative/dvc/pull/2526 , that doesn't do anything exotic and speeds up from 1.4sec to 0.3sec only touching a deps in remotes. Travis didn't finish running it yet, so I'm not yet sure if pyinstaller will see those import or not.

**Comment by Suor** [comment]
This is close to what I referred as during requirements and dynamic imports

**Comment by efiop** [comment]
@Suor Oh, sorry, there was a miscommunication on my side :(

The issue with that patch that pyinstaller will probably not find hooks too, as I'm using strings in that patch. Let me see...

**Comment by efiop** [comment]
@Suor https://github.com/iterative/dvc/pull/2526 works, pyinstaller sees all the imports and we don't have to add anything exotic. Is there anything I'm missing? Could that approach be used to optimize other modules?

**Comment by Suor** [comment]
@efiop The main limitation is the same as for dynamic imports - can't be used at declare time, i.e. class attributes. The other thing is that indirection, which complicates code comprehension, especially in local context.

**Comment by efiop** [comment]
> class attributes.

Doesn't seem like we really need that.

> The other thing is that indirection, which complicates code comprehension, especially in local context.

The indirection that was in that PR was removed.

**Comment by Suor** [comment]
@efiop The question was about are we able to use that approach to optimize other imports, so class attributes matter and we have them. Say we don't want importing `OutputS3` cause `RemoteS3` import, then in absence of lazy imports we will need to say:
```python
class OutputS3(OutputBase):
    REMOTE = "dvc.remote.s3.RemoteS3"  # Use string ref
```

And then add some code handling this string to `RemoteBASE`, in contrast when using lazy imports the changes are local to `dvc/output/s3.py`.

**Comment by efiop** [comment]
@Suor But does loading RemoteS3 take that much time now, after boto3 is loaded dynamically? Could you re-run the import time check to see how everything is looking right now?

**Comment by Suor** [comment]
That was an example, saying that lazy imports are more universal.

**Comment by efiop** [comment]
@Suor They are, I'm not arguing with that. I'm just saying that they are more complex (new black box that you need to deal with, and new contributors will need to know when to use it) and break things like pyinstaller, which requires more maintenance effort.

Let's reevaluate the situation once more, to see how things are looking right now after dynamic imports PR was merged, please.

**Comment by efiop** [comment]
@Suor That being said, I do like these lazy_imports implementation and I do have a feeling that we might endup having no choice but to use them at some point in the future, maybe even not in dvc, but still. And I hate really wasting this :slightly_frowning_face: Would you at least move this implementation to funcy? :slightly_smiling_face:

**Comment by Suor** [comment]
The code will stay in branch. These are not generic enough to include into funcy, and funcy is not a collection of everything), so I don't think these belong there.

Besides we might want approach lazy imports differently next time. E.g.:

```python
@lazy_import
def storage():
    from google.cloud import storage
    return storage
```

More verbose, but more flexible and no need to use improtlib nor hack pyinstaller.

**Comment by efiop** [comment]
Btw, please, don't forget to link related issues: https://github.com/iterative/dvc/issues/2445

**Comment by efiop** [comment]
> The code will stay in branch. These are not generic enough to include into funcy, and funcy is not a collection of everything), so I don't think these belong there.

@Suor Alright, as you wish :slightly_smiling_face: Should we close this then?

**Pull request closed without merging**
