### PR TITLE
Remote: Add remote as an additional parameter

### LINKED ISSUE #9352: specify remote when adding file to dvc repo
Currently, one can add a file to dvc via `dvc add some.file` which will create a tracking file `some.file.dvc`. In this tracking file, one can add `remote: some_remote` to the fields, to tell dvc which remote to synchronize with (cf. [docs](https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries)). I would like to be able to do that from the command line per some argument to `dvc add`. The command already has argument `-r/--remote` (although currently only allowed in combination with `--to-remote`. It'd be great if it could be used for this purpose.

What I'm suggesting in code:
`dvc add test.txt --remote foo` should yield a file with this content
```yaml
outs:
- md5: <SOME_HASH>
  size: <SOME_SIZE>
  path: test.txt
  remote: foo

### PR DESCRIPTION
**Pull request by kshitiz305**
Fix #9352

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by dberenbaum** [comment]
@kshitiz305 Thanks for the PR! Is it a work in progress? I don't see that the remote gets passed down as mentioned in https://github.com/iterative/dvc/issues/9352#issuecomment-1516699392. Also, would you be able to add tests for the behavior?

**Comment by kshitiz305** [comment]
when I am trying to test the code it is giving me an error 

```
ks@W10BYBH3J3:~/dvc$ python3 -m tests tests/func/test_add.py::test_add_preserve_fields
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --dist -n=logical tests/func/test_add.py::test_add_preserve_fields
  inifile: /home/ks/dvc/pyproject.toml
  rootdir: /home/ks/dvc
```

**Comment by pmrowla** [comment]
@kshitiz305 just checking in, are you planning on following up on this PR?

**Comment by kshitiz305** [comment]
> @kshitiz305 just checking in, are you planning on following up on this PR?

yes I am working on it

**Pull request closed without merging**
