### PR TITLE
Add DVC shell completion for Bash and Zsh

### PR DESCRIPTION
**Pull request by mroutis**
### To-Do
- [x] Bash
- [x] Zsh
- [ ] Include them to the package builds

### Test
Copy the `dvc.zsh` file into a directory included `$fpath`, the file should be named `_dvc`.

```bash
docker run --rm -ti alpine

# Inside docker
apk update && apk add  zsh

# Change the URL depending on the commit
wget https://raw.githubusercontent.com/iterative/dvc/31b7a5766fcde68c32aae2b8f0e7d841ecb0dfd6/scripts/completion/dvc.zsh

mv dvc.zsh /usr/share/zsh/site-functions/_dvc

zsh

# Inside zsh
autoload -U compinit && compinit

# Now type dvc, and you can start testing the autocomplete

# For example, dvc[tab] run [tab] -f[tab]...
```

_NOTE: it looks great if you add the following to your Zsh_

```zsh
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes
```

You can also check this references for more context:
   - https://github.com/zsh-users/zsh-completions
   - http://zsh.sourceforge.net/Doc/Release/Completion-System.html
   - https://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html
   - http://www.linux-mag.com/id/1106/

### CODE REVIEW

**Comment by efiop** [comment]
Looks great! Thank you! Judging by [WIP] and tick boxes, you are not ready to merge this PR yet, right?

**Comment by mroutis** [comment]
that's right, @efiop, I will keep working on this branch

**Comment by mroutis** [comment]
@efiop, I was planning to use something like the following script to provide the completion functions:

```bash
  install -Dm644 scripts/completion/dvc.bash \
    "$pkgdir/etc/bash_completion.d/$pkgname"

  install -Dm644 scripts/completion/dvc.zsh \
    "$pkgdir/usr/share/zsh/site-functions/_$pkgname"
```

However, I couldn't figure out your packaging process, could you give me a walkthrough?

Other option is to provide information on the README about how to install command-line completion, as `docker-compose` does it: https://docs.docker.com/compose/completion/

**Comment by efiop** [comment]
Hi @mroutis !

Wow, amazing work!

We have two methods of distribution:
1) pip package; In this case we can utilize `data_files` in `setup.py` https://docs.python.org/2/distutils/setupscript.html#installing-package-data.

2) dep/rpm/pkg/exe; These packages are build by two scrips: `scripts/build_posix.sh` for linux mac and `scripts/build_windows.cmd` for windows.

For posix packages, take a look at `build_dvc`(https://github.com/iterative/dvc/blob/master/scripts/build_posix.sh#L81) function. Here is where we use pyinstaller to create a single executable file from dvc package and put in into $BIN_DIR(which is `$BUILD_DIR/$INSTALL_DIR/bin`). So according to your `install` command from above, you will need to add `dvc.bash` to `$BUILD_DIR/$INSTALL_DIR/etc/bash_completion.d/` and `dvc.zsh` to `$BUILD_DIR/$INSTALL_DIR//usr/share/zsh/site-functions/`.

I guess for windows package we should not add any of those completion files. Maybe `powershell` one if we will get to creating it in the future :)

Thanks,
Ruslan

**Comment by mroutis** [comment]
@efiop, I was reading other projects' source code to see how shell completion is provided, both, [django](https://github.com/django/django/blob/master/extras/django_bash_completion) and [docker-compose](https://github.com/docker/compose/blob/1.1.0/docs/completion.md) doesn't install them by default (with the package), neither [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-command-completion.html).

I'm not sure about the benefits of including shell completion functions in the package.

We could add `dvc`'s zsh completion here: https://github.com/zsh-users/zsh-completions/tree/master/src

What do you think, should we close this issue without including them in the package?

**Comment by efiop** [comment]
Hi @mroutis !

That sounds very reasonable to me! Please remove `[WIP]` prefix if you are ready and I'll merge this right away.

Thanks,
Ruslan

**Comment by mroutis** [comment]
All set, @efiop!

**Comment by efiop** [comment]
Great! Thank you so much! Merged.

**Pull request merged**
