### PR TITLE
cli: status: remove unused code

### PR DESCRIPTION
**Pull request by efiop**
This is the first iteration to improve our code coverage and make it persistent. This PR increases code coverage for `dvc/command*` files to 100% and enables a check for it on our travis.

Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

### CODE REVIEW

**Comment by shcheklein** [comment]
I love the intention overall! I don't like the way it's achieved though - running the commands w/o actually testing the logic - outputs, files structure, cache structure, etc (sorry, if I'm missing something). It's easy to keep it 100% I'm not sure it can be considered as a real number, it's better to keep it 70% with actual high quality tests instead and slowly improving it. For example if the intention is to just test argparser, then I would stub the actual implementation so that this test does not affect the coverage that much.

**Comment by efiop** [comment]
@shcheklein Agreed, let me improve these. Marking as WIP. Thanks for the feedback!

**Comment by efiop** [comment]
@shcheklein Ok, I've updated this PR to just remove an unused piece of code for now. Will prepare a stubber for CLI tests later.

**Comment by shcheklein** [comment]
LTGM! 👍

**Pull request merged**
