### PR TITLE
import-url: make version-aware and to-remote exclusive

### PR DESCRIPTION
**Pull request by dberenbaum**
See https://github.com/iterative/dvc.org/pull/4468

### CODE REVIEW

**Comment by efiop** [comment]
Seems like there is no reason why this can't work. This is probably more of an "undefined behaviour" type of case, since we just never really tested/QA'd it.

**Comment by dberenbaum** [comment]
`import-url --version-aware` never pushes anything to the remote, so what would `--to-remote` do?

**Comment by efiop** [comment]
@dberenbaum Sorry, I should've clarified that I mean it in the "backup" scenario, when we would push. Obviously not applicable right now, but could be in the future.

`push: False` for version-aware and similar behaviour in `dvc import` is getting extra confusing now, but that's an old story 😅

**Review by efiop — APPROVED** [review]

**Comment by efiop** [comment]
Thank you! 🙏

**Pull request merged**
