### PR TITLE
add contrib avatars

### PR DESCRIPTION
**Pull request by casperdcl**
Replaces the old https://github.com/sourcerer-io/sourcerer-app/issues/632

preview: https://github.com/iterative/dvc/pull/6552/files?short_path=7b3ed02#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f or https://github.com/casperdcl/dvc/tree/contrib-avatars#contributing

/CC @jendefig

### CODE REVIEW

**Comment by shcheklein** [comment]
( can we update the dvc.org as well? I think its README also has sourcerer still)

**Review by shcheklein — APPROVED** [review]

**Comment by skshetry** [comment]
Do we need this these days? since there is a Contributor section in the right hand side in Github now.

**Comment by casperdcl** [comment]
> Do we need this these days?

as @jendefig noted, would make a difference at https://pypi.org/project/dvc etc.

**Comment by jendefig** [comment]
> Do we need this these days? since there is a Contributors section in the right hand side in Github now.

When someone goes to PyPi.org it's good for people to see how many contributors. Builds community, encourages contribution, shows how many people are behind the project which provide a trust factor.

**Comment by jendefig** [comment]
Thanks @casperdcl!!!!! 🙏

**Review by skshetry — APPROVED** [review]

**Review by isidentical — APPROVED** [review]

**Pull request merged**
