### PR TITLE
yaml: serialize data with list offset size 2

### PR DESCRIPTION
**Pull request by sisp**
Just a minor esthetics change: I've updated the indentation settings for YAML serialization to align better with common formatting styles.

YAML is often formatted with a 2 spaces offset for lists. For instance, Prettier formats it like this, and `dvc.yaml` file examples in the DVC docs also use this formatting style.

```diff
 k:
-- 1
+  - 1
-- 2
+  - 2
```

Also, `ruamel.yaml`'s documentation states:

> The above example with the often seen `yaml.indent(mapping=2, sequence=4, offset=2)` indentation:
>
> ```yaml
> x:
>   y:
>     - b: 1
>     - 2
> ```
>
> &mdash; https://yaml.readthedocs.io/en/latest/detail/#indentation-of-block-sequences

---

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

### CODE REVIEW

**Comment by dberenbaum** [comment]
@sisp I personally find offset 2 more readable, but I'm hesitant to approve this for a couple reasons:
1. I think we would rather avoid deviating from the `ruamel.yaml` defaults. Maybe it is something you could take up with them?
2. I think it will be surprising if a minor update reformats `dvc.yaml` files.

**Comment by sisp** [comment]
Thanks for your feedback, @dberenbaum! :pray:

I could raise this topic upstream, but if they agree than the result for DVC will be the same – a reformatting of YAML(-like) files but potentially even unrelated to any DVC release since `ruamel.yaml`'s version is only lower-bounded (which is good!):

https://github.com/iterative/dvc/blob/dd2b515c97a6757c6c3522329d6259e0e86592df/pyproject.toml#L67

**Comment by shcheklein** [comment]
I agree with Dave here. I would not change the format w/o a very strong reason (some other tool defaults probably is not strong enough imo). 

Also - should it be configurable (we won't be able to serve everyone), also should DVC try to preserve the existing formatting (this is probably not easy)?

**Comment by skshetry** [comment]
DVC already preserves formatting of yaml files. The stylistic choices are only applied when dvc creates a new file. In that case, you are better using pre-commit hooks.

I am -1 on adding any configuration.

**Comment by dberenbaum** [comment]
@sisp Thanks for the PR, but I am going to close this one since the team agrees this is not something we want to handle in dvc.

**Comment by sisp** [comment]
Fair enough, @dberenbaum.

**Pull request closed without merging**
