### PR TITLE
output: use strings instead of PathInfo for performance reasons

### LINKED ISSUE #3635: remote: loading dirs is exteremely slow because of PathInfo
This https://github.com/iterative/dvc/blob/0.93.0/dvc/remote/base.py#L290 takes ~50 seconds compared to ~0.4 for simple `replace()` that we used to have on our imagenet dataset.

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Partial fix for #3635.

### CODE REVIEW

**Comment by pmrowla** [comment]
The optimization in `OutputBase._collect_used_dir_cache` improves the `_cloud_status` runtime from `938s` to `337s` in cProfile, for an S3 remote with 2M files.

There are still several places we can improve in `RemoteBASE` and `RemoteLOCAL`, since `remote.checksum_to_path_info` is slow when dealing with large numbers of files. The issue here would be that it looks like it may end up being a fairly substantial refactoring, since optimizing where pathinfo is currently used in `RemoteLOCAL.status` ends up affecting several other places in the upload/download pipeline which currently expect pathinfos. In testing, I was able to get `_cloud_status` runtime down to `221s` (but with broken push/pull).

@efiop, should I continue with this or do we want to just leave it at only the used_dir_cache change for now?

**Comment by efiop** [comment]
@pmrowla Your call. I would be perfectly happy to merge this first though. Astonishing results!

**Comment by efiop** [comment]
@pmrowla About checksum_to_path_info. We used to have `checksum_to_path` not that long ago, so maybe we need to go back and just convert to PathInfo where we really need it. Or we could have both checksum_to_path and checksum_to_path_info and use where appropriate, not sure.

**Comment by pmrowla** [comment]
@efiop in that case, once I fix whatever is failing CI in windows I'll mark this PR as reviewable/mergeable. We can leave the original issue open and I'll keep looking into optimizing checksum_to_path_info

**Pull request merged**
