### PR TITLE
experimental: support connection strings for databases 

### PR DESCRIPTION
**Pull request by skshetry**
This adds an experimental support for connector strings using sqlalchemy.

User has to provide config for the connection strings with:

Example:
```console
dvc config db.pg.url postgres://localhost:5432/database
dvc config --local db.pg.username user
dvc config --local db.pg.password password
```

For security reasons, it is recommended to set `db.<name>.url` without password, and configure `username`/`password` separately.

And then, they can import using:
```console
dvc import-db --sql 'select * from table' --conn pg
```

### CODE REVIEW

**Comment by dberenbaum** [comment]
I know the choice of backend isn't the point @skshetry, but it doesn't look to me like connector-x is actively maintained

**Comment by skshetry** [comment]
Yeah, it was easy to implement with `connectorx` directly to test connection strings, but it does not solve our other problems. I'm experimenting with `sqlalchemy` now.

**Comment by skshetry** [comment]
Discussed with Jon about security issues here. We'll have to warn user to use read-only access here. Otherwise, DVC can easily run DDL/DML statements.

**Comment by skshetry** [comment]
Another thing to mention here, downloading a large table (say 100M rows) into a CSV file creates a giant file (~15GB). Is that normal, how would you work with that kind of a dataset?

Or, would you partition that into smaller files? cc @dberenbaum, you probably have good ideas here.

I find `dvc import-db` to be not smart-enough in this case.

**Comment by dberenbaum** [comment]
I would probably use parquet for a table that size. I think having a parquet output format with automatic partitioning would be plenty for now (no need to support different partition schemas or other options). However, a CSV already can get us pretty far, so I would also be fine to wait on parquet support.

**Pull request merged**
