### PR TITLE
py3: remove code related to py2 limitations

### PR DESCRIPTION
**Pull request by mroutis**
Related: #1818

### CODE REVIEW

**Comment by efiop** [comment]
@mroutis Tests failing 🙁

**Comment by mroutis** [comment]
thanks for the notice, @efiop :+1:

**Comment by efiop** [comment]
@mroutis ?

**Comment by mroutis** [comment]
@efiop , got distracted with other PR's, I'll address this today

**Comment by mroutis** [comment]
@efiop , tests are passing :)

**Pull request merged**
