### PR TITLE
packages: build binary pkgs with Python 3.10

### PR DESCRIPTION
**Pull request by cclauss**
Python “3.10” MUST be quoted in yaml.
https://dev.to/hugovk/the-python-3-1-problem-85g

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by efiop** [comment]
@cclauss any particular reason to switch to 3.10 now? We are being a little cautious with python version for building packages, as it depends on stability of other tools like pyinstaller, and it is better to upgrade slowly.

**Comment by cclauss** [comment]
> Any particular reason to switch to 3.10 now?

https://github.com/Homebrew/homebrew-core/labels/python-3.10-migration is blocked because `protobuf` is failing on a handful of packages this is one of them.

**Comment by efiop** [comment]
@cclauss Not sure I follow. dvc's homebrew package is built from pypi package, which works with 3.10 just fine, because it is a pure-python package.

**Comment by cclauss** [comment]
Understood.  Thanks.

**Pull request closed without merging**
