### PR TITLE
get/import: updates output strings, et al.

### PR DESCRIPTION
**Pull request by jorgeorpinel**
> Continuation of #3277

* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [x] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
This just matches existing published docs as well as the upcoming `metrics diff` docs PR (iterative/dvc.org/pull/933).

**Comment by pared** [comment]
No that is part of this change, but maybe we should change `version`-> `revision` in `diff`'s descriptions? From discussion under (#3245) it seems that `revision` is the general term used in code. Also, both in `dvc diff` and `dvc metrics diff` positional arguments suggest `rev`. Also, that seems to be the term in docs. `version` on the other hand is mentioned only in `dvc version`.

**Comment by jorgeorpinel** [comment]
> maybe we should change version-> revision in diff's descriptions... that seems to be the term in docs

We prefer version when possible, its more user friendly. See https://github.com/iterative/dvc/issues/3245#issuecomment-580383614. It's still in docs bc the iterative/dvc.org/pull/933 PR is not merged yet.

> both in dvc diff and dvc metrics diff positional arguments suggest rev

Thanks, I updated the autocomplete scripts now.

**Comment by jorgeorpinel** [comment]
NOTE: Please don't merge this yet, just in case there are more related changes in #933. Will ping you when ready, Pawel and Ruslan.

**Comment by jorgeorpinel** [comment]
Ready for final review @pared @efiop! Thanks

**Pull request merged**
