### PR TITLE
Reduce verbosity of `dvc add`

### LINKED ISSUE #2565: dvc add is too verbose
```
$ dvc -V
0.60.1+39104a

$ vi sea_ice.csv # Modify a data file

$ dvc add sea_ice.csv # Update the data file
WARNING: Output 'sea_ice.csv' of 'sea_ice.csv.dvc' changed because it is 'modified'
Saving 'sea_ice.csv' to '.dvc/cache/c9/3f5350dae07d4fbbbade828c805f93'.
Saving information to 'sea_ice.csv.dvc'.

To track the changes with git, run:

	git add sea_ice.csv.dvc
```

3 lines - it is too much. At least the 2nd line (about cache) is not needed.

### PR DESCRIPTION
**Pull request by algomaster99**
* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [ ] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at least
 opened an issue for it? If so, please add a link to it.

-----

Related #2565 

I think there can be one documentation change here:
Screenshot from 2019-10-14 13-58-28

`Saving 'data.xml' to cache '.dvc/cache'.` might not be required here.

### CODE REVIEW

**Comment by efiop** [comment]
@algomaster99 Could you grep through `dvc.org` repo and remove these lines too, please?

**Comment by algomaster99** [comment]
@efiop This can be merged now :tada:

**Comment by jorgeorpinel** [comment]
Did this fix #2565 @algomaster99, @pared? Thanks

**Comment by jorgeorpinel** [comment]
Unrelated: Interesting, I was wondering what `research` was used for. What's the difference with https://github.com/iterative/dvc/labels/question?

**Comment by algomaster99** [comment]
@jorgeorpinel the issue contains two subtasks.
- reduce verbosity
- make `dvc add` stage files to git.

Only the above is solved. Hence, the issue is still open.

**Comment by algomaster99** [comment]
@jorgeorpinel I think `research` is used for signifying the experiments we, as contributors have to do for a pull request or an issue. What is written in the issue or submitted in a PR is clear and can be understood by a reviewer. For example, making some code changes and analysing which output is best for the user.
Whereas `question` is generally used for tagging issue or PRs which are ambiguous and needs more information.

**Pull request merged**
