### PR TITLE
exp rename: verify exp name follows ref format

### PR DESCRIPTION
**Pull request by BradyJ27**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Fixes: https://github.com/iterative/dvc/pull/9812#discussion_r1342192386

Not sure why the commit history is so messy... Sorry about that

### CODE REVIEW

**Review by dberenbaum — APPROVED** [review]

**Comment by dberenbaum** [comment]
@BradyJ27 Thanks for the quick fix! Could you please resolve the conflicts when you have a chance?

**Comment by BradyJ27** [comment]
> @BradyJ27 Thanks for the quick fix! Could you please resolve the conflicts when you have a chance?

I'm not quite sure what is going on with this PR. There are no code conflicts at all, and I think all of the branches have the right permissions. I'm seeing "the base branch restricts merging to authorized users." Is it possible some permission has changed within the DVC repo?

**Comment by pmrowla** [comment]
The issue is that the PR derives from your fork's `main` branch which is diverged from `iterative/dvc` main. It looks like you have been doing `git merge`ing the `iterative/dvc` main branch into your fork's `main`, but the `iterative/dvc` repo is configured to only prefer rebase workflows (and reject merge commits on `iterative/main`).

**Comment by pmrowla** [comment]
You can see the actual conflicts github gets if you try doing `git rebase upstream/main` (where `upstream` is whatever your git remote name for `iterative/dvc` is in your local repo).

Rather than try to resolve all of the conflicts, it will probably be easier to just hard reset/force push your fork's `main` to be the same as `iterative/dvc` main and then just create a new branch + new PR with the final changes from this one.

**Pull request closed without merging**
