### PR TITLE
test: add pytest-clarity

### PR DESCRIPTION
**Pull request by danihodovic**
A plugin to improve diff output. Especially useful for nested diffs.

https://github.com/darrenburns/pytest-clarity

Without pytest-clarity: https://asciinema.org/a/bU003VjjytSbNjUMKuMKPGCdT

With pytest-clarity: https://asciinema.org/a/93hdcOzbsOc4WOgNQoGeR7ieg

* [ ] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [ ] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [ ] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addresses. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
@danihodovic these is some problem in Travis with this?

**Comment by danihodovic** [comment]
Seems like it's failing with py2.7. I'll have a closer look why

**Comment by danihodovic** [comment]
I've realized that there are some issues when running pytest-clarity on this project as opposed to my smaller toy projects.

It's currently failing on py2.7 on CI for all platforms. The error message is vague and I'd have to reproduce it locally to inspect what's going on.

It seems to conflict with pytest-xdist, although we don't have that problem for py3.
https://github.com/darrenburns/pytest-clarity/issues/7

It changes the verbosity level by default which results in huge outputs which is annoying when inspecting CI logs. For example: https://travis-ci.com/iterative/dvc/jobs/259806601.
https://github.com/darrenburns/pytest-clarity/issues/8

I see the value in using this plugin locally when running single tests, but it's not worth the added complexity for CI runs. The ideal scenario for me is to be able to plug this in for local development when I need it for better assertion diffs, but to disable it otherwise. 

The plugin can be disabled on CI with `pytest -p no:clarity`

WDYT?

**Comment by shcheklein** [comment]
@danihodovic I think considering that we gonna drop Python 2 support soon it sounds reasonable. Could you please share some screenshots to better feel what this plugin is doing?

**Comment by danihodovic** [comment]
@shcheklein See the asciienma recordings in the PR description for individual test diff examples.

For general test output it's quite verbose :/ 
image

vs.

image

Maybe it's possible to disable verbose output for passing tests https://github.com/darrenburns/pytest-clarity/issues/8#issuecomment-557837002

**Comment by Suor** [comment]
> Maybe it's possible to disable verbose output for passing tests darrenburns/pytest-clarity#8 (comment)

The author already answered that he doesn't think it's possible. So you need to to go to pytest with this. This is not a big issue for us though, since we use verbose output by default anyway, see `tests/__main__.py`.

Overall, I am not sure we have much need in this. We rarely (ever?) compare complex data structures in tests. So I am `-0` here, let the rest of the team decide whether they want this or not.

**Comment by shcheklein** [comment]
@danihodovic I like the output better! So, if we decide to debug some tests on Py2 we will have to provide `no:clarity` via command line? Not very convenient since I still run some tests via PyCharm (to simplify debugging) and it would require passing this option somehow. I'm not even sure if it's possible. I suggest we wait Py2 EOL and merge or find a way to fix this to not overcomplicate Py2 flow for no reason.

**Comment by danihodovic** [comment]
:+1:

**Comment by jorgeorpinel** [comment]
If the intention is to merge it when Python 2 retires, leave it open maybe 😋. Not much longer:

image

**Pull request closed without merging**
