### PR TITLE
plots: find metric data in yaml dictionary

### LINKED ISSUE #3970: plots: support yaml
DVC supports JSON and YAML for metrics, but not for plots.

Details: https://github.com/iterative/dvc.org/pull/1382#discussion_r434967192

---
UPDATE by Jorge:

- [ ] Let's remember to update docs when this is figured out 🙂 Either in iterative/dvc.org/pull/1382 or in it's own PR on top of those changes.

### PR DESCRIPTION
**Pull request by pared**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Fixes #3970

### CODE REVIEW

**Comment by pared** [comment]
Build faild for Snap, seems like unrelated issue

**Comment by efiop** [comment]
@pared What about docs? Could you suggest an edit to https://github.com/iterative/dvc.org/pull/1382 ?

**Comment by pared** [comment]
@efiop done

**Comment by efiop** [comment]
Thank you @pared ! :pray:

**Comment by jorgeorpinel** [comment]
Thanks for your suggestion in https://github.com/iterative/dvc.org/pull/1382#discussion_r437424901 @pared.

It would be great to get a quick YAML example for `plots show` too. Would that be possible? What I plan to do is just convert the JSON example to YAML as a "new example" but that's kind of lame :P

**Comment by jorgeorpinel** [comment]
Never mind actually. I'm not sure it's needed. I'll comment in the docs PR.

**Comment by jorgeorpinel** [comment]
For the record, here are the full docs changes per this: https://github.com/iterative/dvc.org/pull/1382/commits/ae1d911615ea89a277323ed1d844405b7fa4e821

Thanks!

**Comment by jorgeorpinel** [comment]
Thanks!

**Pull request merged**
