### PR TITLE
import: don't forget to set cache.dir

### LINKED ISSUE #9385: dvc import ignores cache and downloads from remote
# Bug Report

dvc import ignores cache and downloads from remote

## Description

I'm using `dvc import` to import some files that I know are already in an external shared cache (which is also the cache directory for the current project).

dvc downloads the imported files rather than simply sym-linking to the cache

### Reproduce

1. create external cache directory
2. create project that uses this external directory as its cache directory
3. `git push` the config
4. `dvc import`  some data from a registry but don't `git push` the resulting `.dvc` files
5. delete the project directory but not the external cache
6. recreate the project directory by recloning a new instances (this will include the config from 3 above)
7. `dvc import` the same data again

### Expected

Expected dvc to create symlinks to the external cache when the files were already there.

### Environment information

Observed this bug with dvc 2.53 and 2.55.
dvc 2.39 works as expected

### PR DESCRIPTION
**Pull request by efiop**
Fixes #9385

### CODE REVIEW

**Comment by shcheklein** [comment]
Thanks a lot for fixing it so quick. My 2cs - we should have a test for this since it was an unpleasant regression after refactoring. Interfaces are not obvious internally (via kwargs and layers of abstractions).

**Comment by efiop** [comment]
@shcheklein I disagree, this should work by design. This is the only place for DVCFileSystem. A test would be complex and highly specific, that is a bad kind of test.

**Comment by shcheklein** [comment]
I didn't say anything about how that test should look like. 

- Tests are here to insure that things "by design" keep working as designed.
- `this should work by design` - but it wasn't
- `This is the only place for DVCFileSystem` - that's fine. If it's tested there, here it can be as simple as:

```
def test_that_we_enable_cache():
    # this is needed for the underlying DataFs try cache first
    assert cache is passed to DVCFs
```

+ a similar one for repo.

Any combination like this already solves 80% of the intention:

- It provides a documentation
- It declares the expectation on behavior, etc

In this specific situation, I think it's wort having a functional/integration test still, or there should be a benchmark that detects this. Bottom line- we should not be testing this on users.

> I agree that dvcfs could have the args cleaned up to make it more obvious.

It might be better now. I was merely saying that the way it's written now looks fragile enough to break it next time.

**Comment by efiop** [comment]
@shcheklein https://github.com/iterative/dvc/pull/9417

**Pull request merged**
