### PR TITLE
remove unnecessary arguments in state methods

### PR DESCRIPTION
**Pull request by pared**
* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [x] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

### CODE REVIEW

**Comment by Suor** [comment]
:+1: There are more there )

**Comment by Suor** [comment]
E.g. `dvc.repo.gc._load_all_used_cache()` - `target` and `active` are not used.

**Comment by efiop** [comment]
@Suor please feel free to fix it or submit an issue. This change is about state, not gc.

**Comment by pared** [comment]
@Suor thanks for pointing out!

**Comment by efiop** [comment]
@Suor added https://github.com/iterative/dvc/issues/2046 so we don't lose it.

**Pull request merged**
