### PR TITLE
`check-ignore` show sub-repo patterns

### LINKED ISSUE #4555: check-ignore: should ignore subrepos
Subrepos are a part of dvcignore now (e.g. https://github.com/iterative/dvc/blob/7fa90e425d1c3f2b1771b541ccca4ac788d1abf9/dvc/ignore.py#L296 ) so this test https://github.com/iterative/dvc/blob/7fa90e425d1c3f2b1771b541ccca4ac788d1abf9/tests/func/test_check_ignore.py#L91 should be backwards.

### PR DESCRIPTION
**Pull request by karajan1001**
fix #4555
1. Sub-repo pattern now would be considered in `check-ignore` command.
2. New outputs for sub-repo patterns in a `detail`
3. Related tests.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Review by efiop — APPROVED** [review]
Looks great! Btw, looks like we can now use
```
return self.check_ignore(path).match
```
in `DvcIgnoreFilter.is_ignored()`.

Btw, can we assume that the performance of `check_ignore` on par with `is_ignore_dir/file`?

**Comment by karajan1001** [comment]
@efiop

1. Currently `_is_ignored` is returns `False` for files in some default ignored paths ('.dvc', '.git', '/hg'), but `_is_ignored` don't. This follows the result and logic of `git check-ignore`, also the return value of the `dvc check-ignore` which returns whether there is any pattern matches the target, not whether the target is ignored or not. 

Maybe we can do it in our own ways.

2. Yes, their algo complexity is the same.

**Comment by efiop** [comment]
@karajan1001 Ah, I think there is a misunderstanding here. I meant `is_ignored` https://github.com/iterative/dvc/blob/bc5611968f44979016bf87904e0abc2d35a046c2/dvc/ignore.py#L337 , not `_is_ignored`

**Comment by karajan1001** [comment]
> @karajan1001 Ah, I think there is a misunderstanding here. I meant `is_ignored`
> 
> https://github.com/iterative/dvc/blob/bc5611968f44979016bf87904e0abc2d35a046c2/dvc/ignore.py#L337
> 
> , not `_is_ignored`

Oh, I see now, but the conclusion is the same. Currently `check_ignore` only examines the matches of the patterns disregarding the type of the matched pattern, excluded one or included one. This follows the logic from Git, maybe it is the time to change it now.

**Comment by efiop** [comment]
@karajan1001 ah, got it. Current behaviour makes total sense. Thank you for clarifying!

**Comment by efiop** [comment]
@karajan1001 Than you so much for contributing! :pray: 

As I sign of gratitude and trust, we've sent you an invitation to join this repo as a collaborator, which means that you will now have rights to review PRs, etc](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) if you so choose :slightly_smiling_face:

**Pull request merged**
