### PR TITLE
output: base: don't forget to return empty cache

### PR DESCRIPTION
**Pull request by efiop**
CC @Suor

Fixes https://gist.github.com/leimbernon/21924e02a998e3f1604990f8a7824c37

Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [x] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

### CODE REVIEW

**Comment by efiop** [comment]
> No need for ret. Simply return NamedCache()

I disagree, we are using NamedCache() later, reusing is better.

**Comment by efiop** [comment]
@shcheklein Yes, looking into it.

**Comment by Suor** [comment]
@efiop you are reusing same var for two purposes and lengthening its visibility space. This way you increase the probability that one part of the code will affect another one. Var should be used as tight as possibly and be discarded, ideally there should not be any var. The old code followed this rule, by simply `return []`, the new code should do the same - `return NamedCache()`.

**Comment by efiop** [comment]
@Suor The old code did `return cache`, not `return []`. It was reusing the `ret = []` defined above.

**Comment by efiop** [comment]
@Suor The purpose is to have the same value reused for all returns, which helps avoid such bugs as fixed in this PR. And the approach you are talking about was the one that has caused this bug.

**Comment by Suor** [comment]
@efiop by adding a possibility for much nastier bugs.

**Pull request merged**
