### PR TITLE
cli: add allow-missing flag to commit command

### LINKED ISSUE #10524: Add `--allow-missing` for `dvc commit`
Sometimes it's necessary to update pipeline hashes and params without downloading large datasets. Currently I can't run `dvc commit` on machine without data even if I'd like to update my source code machine.

It would be great to have similar to `dvc repro` flag providing a way to ignore files that are not inside cache.

### PR DESCRIPTION
**Pull request by anunayasri**
Fixes #10524

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by anunayasri** [comment]
@skshetry Could you review this please, especially `--allow-missing` description. If it looks fine, I will update the docs repo as well and raise the PR.

**Comment by shcheklein** [comment]
@anunayasri It would be great to have a test for this. Also, could you confirm its semantics - that it keeps `md5s` of the missing dirs / files / deps as-is?

**Comment by skshetry** [comment]
Looks like we don't have tests for `allow_missing` flag for `commit`. We don't write tests for CLI, as they are thin wrapper over Repo API. But since we are now going to depend on it, we need a test for it.

Do you mind adding a test for this API? 

PTAL https://github.com/iterative/dvc/blob/main/tests/func/test_commit.py, which might help you how to write tests. If you have any questions, please feel free to ask here on in discord.

**Comment by anunayasri** [comment]
@shcheklein There were no tests for cli commands, hence I had not added tests. It seems tests need to be added for the `allow_missing` logic in `Repo.commit()`. Will do so.

@skshetry Thanks. I will look into it.

**Comment by shcheklein** [comment]
@anunayasri hey, are there any updates on this? do you need some help on this? (thanks for the PR btw!)

**Comment by anunayasri** [comment]
Hi. I need help with writing the test case for` dvc commit`  usecase for a pipeline. I tried checking the existing test case like `dvc repro` but I am not clear about few things. Could you help or point me to a code piece/doc.

1. In the test case, generate a `dvc.yaml` file. It should have a dep on data file that is missing from the repo. How to generate this setup? I was trying out `allow-missing`  through the example project `example-get-started`.
2. `dvc commit --allow-missing dataset` should do nothing. I believe `allow-missing` is relevant to commit of pipelines.
3. Could you explain the diff between `stage.save()` and `stage.commit(`).

cc: @skshetry @shcheklein

**Pull request closed without merging**
