### PR TITLE
remote: local: try to reflink before copying

### LINKED ISSUE #2057: Support reflinks for local remotes
DVC uses reflinks for the cache, but it does not seem to use reflinks for local remotes. In the following example, I will create a large file, add it to DVC, and push it to a local remote. Disk space is consumed twice: when the file is created and when it is pushed to a local remote. When I remove the content of the local remote and manually reflink the content of the cache to the local remote, the disk space is reclaimed:

```sh
$ dvc --version
0.40.2
$ mkdir test remote_cache
$ cd test
$ dvc init --no-scm
```
```sh
$ df -h
/dev/sdb6                               932G  756G  172G  82% /home
$ dd if=/dev/zero of=file.txt count=$((10*1024)) bs=1048576
$ ls -lh file.txt
-rw-r--r-- 1 witiko witiko 10G May 27 19:03 file.txt
$ df -h
/dev/sdb6                               932G  766G  162G  83% /home
```
```sh
$ df -h
/dev/sdb6                               932G  766G  162G  83% /home
$ dvc add file.txt
$ df -h
/dev/sdb6                               932G  766G  162G  83% /home
```
```sh
$ df -h
/dev/sdb6                               932G  766G  162G  83% /home
$ dvc remote add -d local ../remote_cache
$ dvc push
$ df -h
/dev/sdb6                               932G  776G  152G  84% /home
```
```sh
$ df -h
/dev/sdb6                               932G  776G  152G  84% /home
$ rm -rf ../remote_cache/*
$ cp -r --reflink=always .dvc/cache/* ../remote_cache
$ df -h
/dev/sdb6                               932G  766G  162G  83% /home
```

I can circumvent the issue by [setting `cache.dir` to `../../remote_cache`](https://dvc.org/doc/commands-reference/config#cache), but that will affect users who download Git repositories with my experiments. Therefore, my preferred workaround is to symlink `.dvc/cache` to `../../remote_cache`:
```sh
$ cd .dvc
$ rm -rf cache
$ ln -s ../../remote_cache cache
```
However, this workaround does not work when you have several local remotes, in which case you would need to symlink in the other direction (from the local remotes to `.dvc/cache`). The workaround also makes it impossible to defer publishing the latest changes in your cache.

In conclusion, it would be useful if the local remotes supported reflinks, like the cache does.

### PR DESCRIPTION
**Pull request by Witiko**
* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [x] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

@efiop: Fixes #2057

### CODE REVIEW

**Comment by Witiko** [comment]
Just a minor thing: I noticed that you try to defer importing modules until they are needed. Should I move `from dvc.system import System` from line 6 to line 119?

**Comment by efiop** [comment]
@Witiko Yes, that would be great!

**Comment by Witiko** [comment]
Done. 🙂

**Comment by efiop** [comment]
Thank you @Witiko ! :tada: I'll release a new version later today.

**Pull request merged**
