### PR TITLE
dvcfile: preserve 'remote' on add and commit

### LINKED ISSUE #7356: add / commit: overwrites per-output remote
# Bug Report

## Description

When a .dvc has had a value set for `remote:` (under `out:`) and the actual file content is changed, then `dvc add` and `dvc commit` remove the `remote` value

### Reproduce

 1. `dvc remote add --default storage_2 /tmp/dvcstore_alt`
 2. Add a file like `cp ~/Downloads/example.tsv ./example.tsv`
 3. `dvc add example.tsv`
 4. Edit `example.tsv.dvc` to include a `remote: storage_2

```
outs:
- md5: 0f473951d64d6dd73e07965da6b2758b
  size: 4393
  path: example.tsv
  remote: storage_2

```

 5. git commit and dvc push
 6. Edit `example.tsv`
 7. `dvc add example.tsv`
 8. See that `example.tsv.dvc` has removed the `remote:` value

```diff
diff --git a/example.tsv.dvc b/example.tsv.dvc
index c39daf5..70654ae 100644
--- a/example.tsv.dvc
+++ b/example.tsv.dvc
@@ -1,5 +1,4 @@
 outs:
-- md5: 0f473951d64d6dd73e07965da6b2758b
-  size: 4393
+- md5: f18353455728c7d54aafac4d6087cd9f
+  size: 4511
   path: example.tsv
-  remote: storage_2

```

### Expected

add and commit should leave `remote` if present in a .dvc file

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.3 (brew)
---------------------------------
Platform: Python 3.9.10 on macOS-11.6.2-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2021.11.1),
	webhdfs (fsspec = 2021.11.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.1, boto3 = 1.19.8),
	ssh (sshfs = 2021.11.2),
	webdav (webdav4 = 0.9.3),
	webdavs (webdav4 = 0.9.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: local, local
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

```

**Additional Information (if any):**

This feature looks relatively new/experimental from https://github.com/iterative/dvc/pull/6486 although it's in the docs at https://dvc.org/doc/user-guide/project-structure/dvc-files#output-entries

### PR DESCRIPTION
**Pull request by SamKnightGit**
Fixes partially #7356 -- `dvc move` doesn't preserve many fields (description, remote, comments) but looks like a more involved change.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Review by karajan1001 — APPROVED** [review]
LGTM

**Review by pared — COMMENTED** [review]
LGTM, @skshetry should we wait for your review?

**Comment by SamKnightGit** [comment]
Any idea if/when we can get this change bundled into a release? It's currently blocking my team's use case for dvc (multiple remotes). Thanks guys

**Review by daavoo — APPROVED** [review]

**Review by skshetry — APPROVED** [review]

**Comment by skshetry** [comment]
Thankyou @SamKnightGit.

**Pull request merged**
