### PR TITLE
site_cache_dir: use .dvc/tmp/btime and fallback to st_birthtime

### PR DESCRIPTION
**Pull request by efiop**
This will ensure that we won't be using index cache if you delete your repo and start/clone fresh.

On Linux python is lacking behind and doesn't expose an easy way to get stx_btime or statx results generally, so it will require some work to support it. See [1] and [2]

[1] https://github.com/torvalds/linux/blob/master/samples/vfs/test-statx.c
[2] https://github.com/ckarageorgkaneen/pystatx/blob/master/statx/__init__.py

### CODE REVIEW

**Comment by efiop** [comment]
Will do a salt/key/etc file instead.

**Comment by skshetry** [comment]
@efiop, Could you please elaborate what you are trying to fix? What happens at the moment if you delete the repo and freshly clone at the same path?

**Comment by efiop** [comment]
@skshetry If you delete your repo and clone again into the same location - we will reuse site_cache_dir for it. This is trying to avoid that.

**Comment by efiop** [comment]
@skshetry Ah, sorry, didn't get your question initially.

If something goes wrong, natural instinct is to nuke your repo and since we are having some index cache mishaps it is better to invalidate it, kinda emulating old behaviour when it was in .dvc/tmp.

**Comment by skshetry** [comment]
> If something goes wrong, natural instinct is to nuke your repo and since we are having some index cache mishaps it is better to invalidate it, kinda emulating old behaviour when it was in .dvc/tmp.

In a way, it makes sense. But I am worried that this will make us miss important issues that'll manifest in other forms. I'd rather see us work on making `Index` resilient, and handle cache invalidation properly in the db.

I don't see it as any different from checking out an old git revision. I'd expect DVC to still work in that case.

**Comment by efiop** [comment]
@skshetry I totally understand you and I feel the same way, but these things are not mutually exclusive, this just gives you an easy way to start over without implicit behavior.

**Pull request merged**
