### PR TITLE
dvc: some minor optimizations

### PR DESCRIPTION
**Pull request by Suor**
Some gc-related optimizations.

### CODE REVIEW

**Comment by efiop** [comment]
@Suor Any context/explanations on why you are introducing these particular changes?

**Comment by Suor** [comment]
Just stumbled upon these while investigation gc code. Do we need context to change things?

**Comment by efiop** [comment]
@Suor Need to understand why you are changing those lines like that, it is not obvious.

**Comment by Suor** [comment]
In first hunk `used` is used in `checksum in used` test later, which is inefficient against list, so I changed that to set. Second is just to avoid recreating and copying list.

**Comment by efiop** [comment]
@Suor Thanks, that is the comment that I was looking for.

**Pull request merged**
