### PR TITLE
Migrate to pytest

### PR DESCRIPTION
**Pull request by shcheklein**
*Few comments:*

- Had to use `--timeout_method=thread` due to this issue https://bitbucket.org/pytest-dev/pytest-timeout/issues/8/pytest-xdist-interop-signal-only-works-in
- Progress object is global and we do not have a cleanup logic. Had to introduce a hard reset into one methods. In the future we should use a context for progress or something else to make sure we clean it up after use.

### CODE REVIEW

**Comment by efiop** [comment]
Updated docs in https://github.com/iterative/dvc.org/commit/49e8da9f6f949001bba866b720c8c642ba8121fb

**Comment by mroutis** [comment]
@shcheklein , @efiop , are we going to use the `unittest` syntax or we will be moving progressively to an `assert` "pytest-like" approach?

**Comment by shcheklein** [comment]
@mroutis I don't have any strong preferences yet, I haven't tried using `assert` style. I would thought prefer to agree on on single style and gradually migrate if needed.

I wonder, if there Is there a quick guide how to translate all common uninttest asserts into pytest's. Especially to compare dicts, lists, etc.

I definitely plan to start using things like fixtures soon (hopefully).

**Comment by shcheklein** [comment]
@efiop thank you for updating the guide!

**Comment by mroutis** [comment]
@shcheklein , here's how will it looks like: https://github.com/iterative/dvc/pull/1745

**Comment by efiop** [comment]
@mroutis What I like about unittest's asserts is that they actually show values if they don't match. With #1745 it seems like regular "assert"s are used, which don't provide any additional info like unittest's assert* do. Or am I missing something?

**Comment by mroutis** [comment]
@efiop , they provide useful outputs, it is just the syntax that changes, here are some examples of how `pytest` present errors: https://docs.pytest.org/en/latest/example/reportingdemo.html#tbreportdemo

**Comment by shcheklein** [comment]
@mroutis it looks great actually!

**Comment by efiop** [comment]
@mroutis Nice! Why did you close your PR though? 🙂If it works, mind reopening it again?

**Comment by mroutis** [comment]
@efiop , the PR was just an example of how it would look like, I'll open a WIP to move from unittest to pytest :)

**Pull request merged**
