### PR TITLE
checkout: Prompt when deleting files from working dir

### LINKED ISSUE #1328: checkout: add confirmation prompt
I.e. dvc should check if there are unsaved changes and ask user if he is sure he wants to overwrite them. Similar to what we have in gc,remove, etc commands. Also need to add a `-f|--force` option for it to disable the prompt.

### PR DESCRIPTION
**Pull request by mroutis**
Close #1328

### CODE REVIEW

**Comment by efiop** [comment]
Maybe it is worth adding the same check for not only new, but also changed files? What do you think?

**Comment by mroutis** [comment]
The tests should now pass, @efiop , but I'm wondering if this line should be _forced_ too:

https://github.com/mroutis/dvc/blob/2906a31b66bebd536e15ac3db14d40c8bf470c3e/dvc/project.py#L773

I think it shouldn't, but I'm not sure.

**Comment by efiop** [comment]
> The tests should now pass, @efiop , but I'm wondering if this line should be _forced_ too:
> 
> https://github.com/mroutis/dvc/blob/2906a31b66bebd536e15ac3db14d40c8bf470c3e/dvc/project.py#L773
> 
> I think it shouldn't, but I'm not sure. Maybe introducing `git pull --force` could be a good idea

It should. Could you please add it?

**Comment by mroutis** [comment]
> It should. Could you please add it?

With the `--force` flag? or just add the `force=True` option at checkout?

**Comment by efiop** [comment]
Thank you! :slightly_smiling_face:

**Pull request merged**
