### PR TITLE
run: use -f/--force to overwrite, fix msg

### LINKED ISSUE #4003: run: improve stage exists error message to hint how to overwrite (edit) it
Running `dvc run` again to edit an existing stage in the `dvc.yaml` is a very common case:

Would be nice to put a hint along with the error message that prints:

`ERROR: Stage 'prepare' already exists in 'dvc.yaml'. Add `--overwrite` option to edit the existing stage.`

instead of:

`ERROR: Stage 'prepare' already exists in 'dvc.yaml'.`

that it prints now.

### PR DESCRIPTION
**Pull request by skshetry**
Also, makes fixes for `--overwrite` rename to `--force`
and also remove `remove_with_prompt` which was only being
used with `force=True` anyway.

Fix #4003

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).
I'll suggest this on `dvc.org`'s WIP PR.

https://github.com/iterative/dvc.org/issues/1255

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hi, how is this expressed in #1255 ? I'm not seeing it, thanks.

**Comment by jorgeorpinel** [comment]
p.s. probably best to open an individual docs issue. That epic is for very specific 1.0 discrepancies. Let's try to keep the same process as always.

**Comment by skshetry** [comment]
@jorgeorpinel, many of the commands were changed for 1.0. And, this is a very 1.0 discrepancy. And, it's not too important for `get-started`.

**Comment by efiop** [comment]
@jorgeorpinel Same as with my `-f` change, there are too many conflicting docs to edit, so added a checkbox to that epic.

**Comment by jorgeorpinel** [comment]
I don't see a checkbox for this in the epic actually. But can we please follow the regular process 🙏 sorry if the epic was confusing.

For this one I will just incorporate in iterative/dvc.org/pull/1420 since I'm just getting started. Thanks

**Comment by shcheklein** [comment]
> For this one I will just incorporate in iterative/dvc.org/pull/1420

not a good idea I think, let's try to keep iterative/dvc.org/pull/1420 focused on `dvc run` only and do it faster, wdyt?

**Comment by jorgeorpinel** [comment]
Sure. But this PR is now part of 1.0 pre-release `dvc run` and I'm just getting started with updating that cmd ref description and examples, so this behavior will already be included as I use the cmd to confirm everything. That's why it should be covered already in iterative/dvc.org/pull/1420

**Comment by efiop** [comment]
> I don't see a checkbox for this in the epic actually.

There was: ` get rid of -f in add/run/import(-url) per iterative/dvc#4004 and iterative/dvc#4011`, you can see it in the history. Look like you've removed it in the past two days.

**Comment by jorgeorpinel** [comment]
I extracted that other one you added into its own issue but it wasn't for this, unless I don't understand how "get rid of -f in run" per #4004 = "run: use -f/--force to overwrite" per this PR.

**Pull request merged**
