### PR TITLE
Add more tests according to gitignore

### LINKED ISSUE #4103: .dvcignore is broken on negation when blacklisting all
### Please provide information about your setup

I am not sure how far this extends to, but a lot of trials for `.dvcignore` failed when I blacklisted all and tried to whitelist some:

```
*
!scripts
```

```
*
!/scripts
```

```
/*
!/scripts/
```

```
/*
!/scripts/*
```

```
/*
!/scripts/**
```

```
/*
!scripts/
```

### What worked:
```
/*
!/scripts
```

Why do I feel suddenly the spelling of `scripts` is wrong? :smile:

### PR DESCRIPTION
**Pull request by karajan1001**
fix #4103

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by karajan1001** [comment]
Two issues.

1. Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.

> This is an issue of `PathSpec`.

2. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.
> Because path didn't distinguish with files in `dvcignore`. And `dir/` can't match pathname `dir`.

**Comment by efiop** [comment]
@karajan1001 Sorry for the delay. This is outstanding work! Thank you so much for looking into this! 

> Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.

Should we report it to pathspec and wait for the solution on their side? Or how do you think we should tackle it?

> It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

>  Because paths didn't distinguish with files in dvcignore. So dir/ can't match pathname dir.

Nice catch! So that one is solved and we are doing it the same way gitignore does it, right?

**Comment by pared** [comment]
Seems like builds are failing.

**Comment by karajan1001** [comment]
> Should we report it to pathspec and wait for the solution on their side? Or how do you think we should tackle it?
> 
> >
@efiop 
I'd like to report it to `PathSpec` and fix it myself, but only after work could I do it.

> Nice catch! So that one is solved and we are doing it the same way gitignore does it, right?
Yes, I had tested with git If the pattern format description is complex or not clear.
image
image
image
 

> Seems like builds are failing.
@pared  A bug from `pathspec` is waiting for fixing.

**Comment by efiop** [comment]
> I'd like to report it to PathSpec and fix it myself, but only after work could I do it.

@karajan1001 Sounds great! :pray: So maybe let's remove or comment-out that particular test case for now, so we could merge?

**Comment by karajan1001** [comment]
> > I'd like to report it to PathSpec and fix it myself, but only after work could I do it.
> 
> @karajan1001 Sounds great! 🙏 So maybe let's remove or comment-out that particular test case for now, so we could merge?

There is still something wrong with triple asterisks,  According to the document.

> Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.

What the result from my computer shows that triple asterisks act like double ones.

image
image
image

And I found another problem.`data/*` can match `data/1/2` just like `data/**`. 

Seems that `Git`, the documents of `gitignore`, and `Pathspec` go different ways. 

I don't know which is the standard ones now.

**Comment by pared** [comment]
Checked latest git master (2.26.0-rc1) and @karajan1001 is right, behavior of x/* is different that explicitly stated in gitignore docs. @karajan1001 that seems like a bug and potential contribution opportunity.

As to current build, I think we should comment out failing ones and wait till it gets done on PathSpec side. As to triple asterisk I would just leave it. If some will ever come to us with valid use case of triple asterisk other than 'match all', then we can consider it. There is no point in blindly following git docs.

**Pull request merged**
