### PR TITLE
plots: special chars handling for vega plots paths

### PR DESCRIPTION
**Pull request by pared**
Fixes: #6894

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Cannot test it for now. Marking as [WIP] until I can do that or get confirmation its working on windows.

### CODE REVIEW

**Comment by shcheklein** [comment]
Thanks @pared for addressing it quick! Is it WIP still? 

Also tests failing and probably we should add a test for this bug, wdyt?

**Comment by pared** [comment]
I don't have access to a Windows computer and won't have it for a few days, hence WIP. If you could confirm this fix works on windows too we could merge it faster. I will write a test.

**Comment by pared** [comment]
@shcheklein I created a simple temporary test, to make sure all the special characters get converted. We can merge this change, however, this issue is not over. To make sure we do not get more of such issues, we should introduce testing for our generated HTML. For the beginning, we should try to parse the HTML, extract `js` and verify that `err` log is empty when executed. That requires some research, that's why I would opt for merging this fix and continuing proper HTML testing in the new issue.

**Comment by skshetry** [comment]
For e2e tests, I'd suggest `playwright` for simple tests, it has nice integration with `pytest`. I have more experience on selenium, but playing with playwright, it looks really nice (this gist that I played with might be helpful: https://gist.github.com/skshetry/167b982372c522ad6f9e09973ecfc10b).

I'd prefer we run this on a nightly basis on a separate repository though, as we need to depend on some browsers and these tests may be flaky.

**Comment by pared** [comment]
> I'd prefer we run this on a nightly basis on a separate repository though, as we need to depend on some browsers and > these tests may be flaky.

Another reason to evict rendering out of DVC.

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
I've approved, @pared . Sorry never had intention to block this (I was satisfied with the answer-  In a sense I trust that you and the team could figure out the best).

**Comment by pared** [comment]
@Mergifyio rebase

**Review by daavoo — APPROVED** [review]

**Comment by JulianWgs** [comment]
Thanks for the fix. When will this be released? :)

**Comment by pared** [comment]
@JulianWgs It seems that draft release for `2.8.4` is already there. I hope that we can do that this week. I will check with other maintainers if there is anything blocking us/

**Comment by pared** [comment]
@JulianWgs Regretfully we were not able to release yet, we have few major inner changes coming and the release needs to wait until we are sure everything works as intended. Meanwhile, if your use case cannot wait, I would recommend installing from master, if it's possible on your side.

**Comment by pared** [comment]
@JulianWgs `2.9.0` containing this change has been released: https://github.com/iterative/dvc/releases/tag/2.9.0

**Comment by JulianWgs** [comment]
Great news. Thanks!

**Pull request merged**
