### PR TITLE
Bump networkx

### PR DESCRIPTION
**Pull request by faucct**
To avoid conflict with https://github.com/aws-cloudformation/cfn-python-lint

### CODE REVIEW

**Comment by pared** [comment]
@faucct so the problem here is that cfn uses at least `2.4`?

**Comment by faucct** [comment]
Yep.

**Comment by efiop** [comment]
Thanks!

**Comment by faucct** [comment]
Can this get a release, please?

**Comment by efiop** [comment]
@faucct Sure! We'll release a new version later today or tomorrow. We have some critical changes in the pipeline, so can't really release earlier. Thank you for the feedback!

**Comment by faucct** [comment]
Good!

**Pull request merged**
