### PR TITLE
Update Google Project credentials to run tests

### LINKED ISSUE #3157: test: GDrive tests are getting skipped.
As the title says, tests for GDrive are getting skipped on travis.

### PR DESCRIPTION
**Pull request by MaxRis**
Fixes #3157 

Secure env variable should be set by Travis before this PR is get merged.

### CODE REVIEW

**Comment by shcheklein** [comment]
@MaxRis why is it WIP?

**Comment by MaxRis** [comment]
@shcheklein I've put [WIP] only to ensure that GDrive tests on Travis are running now (env variable should be set), so this PR will able to close the Issue https://github.com/iterative/dvc/issues/3157 as well.

**Comment by efiop** [comment]
@MaxRis So is it still WIP? The env vars are only available for native branches as they are marked as secure ones, so this PR still shows that the tests are getting skipped. You could create a new PR from an upstream branch if you want to verify that tests are being ran before merging the PR.

**Comment by MaxRis** [comment]
@efiop thanks! I will check shortly. (Previously there was a bug or trick at GitHub that I can push branch with the same name to upstream and GitHub automatically will start treat this PR as from upstream's branch).

**Comment by MaxRis** [comment]
@efiop not sure how it works, but pushing of the same branch to upstream have restart Travis build automatically and secured variables are in place this time. Can see that gdrive tests are passing, so please merge this PR
```
[gw1] [ 19%] PASSED tests/func/test_data_cloud.py::TestRemoteGDrive::test 
[gw0] [ 20%] PASSED tests/func/test_data_cloud.py::TestRemoteGDriveCLI::test 
```

**Comment by efiop** [comment]
Thanks @MaxRis ! 🙏

**Pull request merged**
