### PR TITLE
dvc:Changes UP_TO_DATE_MSG in status.py

### LINKED ISSUE #2346: status: change nothing to reproduce message
If I use DVC only to version data/models and don't care about pipelines, this message:

`Pipelines are up to date. Nothing to reproduce.` 

looks really strange.

Let's change it to something more generic:

`Data and pipelines are up to date.` 

or something similar

### PR DESCRIPTION
**Pull request by SRITANU**
Fixes #2346

* [ ] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [ ] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

### CODE REVIEW

**Comment by efiop** [comment]
@SRITANU Thanks for the PR! Could you also contribute a PR for our docs to adjust this message there? E.g.
```
(3.7.0-dvc) ➜  dvc.org git:(master) grep "Nothing to reproduce" -R ./                         
./static/docs/commands-reference/repro.md:Pipelines are up to date. Nothing to reproduce.     
./static/docs/commands-reference/repro.md:Pipelines are up to date. Nothing to reproduce.     
./static/docs/commands-reference/install.md:Pipelines are up to date. Nothing to reproduce.   
./static/docs/commands-reference/install.md:Pipelines are up to date. Nothing to reproduce.   
./static/docs/commands-reference/install.md:Pipelines are up to date. Nothing to reproduce.   
./static/docs/commands-reference/commit.md:Pipelines are up to date. Nothing to reproduce.    
./static/docs/commands-reference/commit.md:Pipelines are up to date. Nothing to reproduce.    
./static/docs/commands-reference/import-url.md:Pipelines are up to date. Nothing to reproduce.
./static/docs/commands-reference/import-url.md:Pipelines are up to date. Nothing to reproduce.
./static/docs/commands-reference/push.md:Pipelines are up to date. Nothing to reproduce.      
./static/docs/commands-reference/push.md:Pipelines are up to date. Nothing to reproduce.      
./static/docs/commands-reference/status.md:Pipelines are up to date. Nothing to reproduce.    
./static/docs/commands-reference/status.md:Pipelines are up to date. Nothing to reproduce.    
./static/docs/user-guide/dvcignore.md:Pipelines are up to date. Nothing to reproduce.         
./static/docs/user-guide/dvcignore.md:Pipelines are up to date. Nothing to reproduce.         
./static/docs/user-guide/dvcignore.md:Pipelines are up to date. Nothing to reproduce.         
```
The docs repo is https://github.com/iterative/dvc.org

**Comment by SRITANU** [comment]
Sure, I'd do that.

**Comment by SRITANU** [comment]
@efiop  I have made the necessary changes in the docs. Here's the PR: https://github.com/iterative/dvc.org/pull/521

**Comment by efiop** [comment]
Thank you so much @SRITANU !

**Pull request merged**
