### PR TITLE
fix and test outdate check

### PR DESCRIPTION
**Pull request by pared**

### CODE REVIEW

**Comment by pared** [comment]
Thanks, wanted to inform you after builds. Did I mark WIP wrong?

**Comment by efiop** [comment]
No-no, you've marked it right. I've just decided to not wait with my comment :slightly_smiling_face: Thanks!

**Comment by efiop** [comment]
Can we remove WIP now and merge it? Or would you like to add something?

**Comment by pared** [comment]
We can merge

**Comment by efiop** [comment]
Nice! Thank you so much! Merged. :tada:

**Pull request merged**
