### PR TITLE
deps: temporarily limit dulwich to <0.20.46

### PR DESCRIPTION
**Pull request by efiop**
Looks like the new release broke some data status logic.

### CODE REVIEW

**Comment by efiop** [comment]
Merging for now to fix main branch tests.

@skshetry Could you take a quick look at data status, please, https://github.com/iterative/dvc/runs/8218020733?check_suite_focus=true ?

**Comment by efiop** [comment]
Turns out this is related to https://github.com/iterative/scmrepo/issues/120 cc @dtrifiro

**Comment by skshetry** [comment]
So where should we fix this? @dtrifiro @efiop

**Comment by efiop** [comment]
@skshetry Daniele said it should be in scmrepo.

**Pull request merged**
