### PR TITLE
plots: allow multiple outputs for --show-vega

### PR DESCRIPTION
**Pull request by pared**
* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by pared** [comment]
Well it seems there is no necessity for mapping now, but I think it would be safer to have one, it gives a lot of context what particular vega contains, so probably sooner or later we will need that.

**Comment by dberenbaum** [comment]
We will also start working on the experiments API in the future. We should think about what plots info will be useful to return in an API, which should probably resemble the outputs here.

**Comment by pared** [comment]
@Mergifyio rebase

**Comment by pared** [comment]
@rogermparent lets get back to this issue:

Initially, this PR was about allowing multiple targets for `--show-vega`, now after starting supporting images the scope starts to shift, and I started to think how to implement that, but after discussing a bit with @dberenbaum and @daavoo I start to wonder whether I am not too hastily getting into that.

How the results are going to be visualized in the extension? 
Wouldn't it make sense if both `dvc plots show` and extension results be similar? 
It seems to me that if we split the way we visualize our results, soon we will end up with different implementations. 
Do you think it would make sense, to, for example, embed HTML in the vscode? Would it be possible at all?

**Comment by rogermparent** [comment]
> Initially, this PR was about allowing multiple targets for `--show-vega`, now after starting supporting images the scope starts to shift, and I started to think how to implement that, but after discussing a bit with @dberenbaum and @daavoo I start to wonder whether I am not too hastily getting into that.

It's possible, but I'd say that's more of a question about the DVC codebase. VSCode will need both features, and preferably in one command, but we can absolutely make do with vega plots first and static plots in a later PR.

> How the results are going to be visualized in the extension? Wouldn't it make sense if both `dvc plots show` and extension results be similar? It seems to me that if we split the way we visualize our results, soon we will end up with different implementations. Do you think it would make sense, to, for example, embed HTML in the vscode? Would it be possible at all?

We currently have a design that's reminiscent of the `dvc plots show` HTML, but a little more ambitious with features like collapsing and search.

static plots design screenshot

While similar, the differences in this design mean we're already intending to make a different implementation than `dvc plots show`'s output which serves a different, simpler purpose. 

As far as using HTML goes, this vega plots UI is also slated to be part of a larger "visualizations" webview shared with live plots, and also VSCode requires webviews use [URLs with a special `resource:` protocol to load local data](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content) so using the HTML straight is out of the question.

Handling all of these considerations with `plots show` HTML would essentially require us to heavily pre-parse the given HTML and use the gathered data similarly to how we would use the JSON from `--show-vega`. While this is doable, we'd essentially be consuming the `plots show` HTML output as an API which would add friction in any changes to that HTML as we worry they could become breaking.

**Comment by pared** [comment]
@rogermparent makes sense, thanks for the clarifications. Seems like we will need to pack it all into `--show-json`. Need to think about how to do that. Writing files and providing URLs which we discussed, sounds a bit clunky, maybe we will come up with something better.

**Comment by dberenbaum** [comment]
Thanks @rogermparent and @pared!

Let me try to recap some of my questions and concerns from our discussion for @rogermparent (and probably useful for @shcheklein).

It seems like we are redoing the Python API as a JSON output. Do we want to do this? If so, it might clarify things and we can at least have consistency. On the other hand, it might be redundant and doesn't necessarily have a lot of general use unless others can't use Python.

> Handling all of these considerations with `plots show` HTML would essentially require us to heavily pre-parse the given HTML and use the gathered data similarly to how we would use the JSON from `--show-vega`. While this is doable, we'd essentially be consuming the `plots show` HTML output as an API which would add friction in any changes to that HTML as we worry they could become breaking.

This sounds ugly, but I'm not yet convinced it's much worse than the the current approach, and I'd rather start as simple as possible. My reasoning:
* The HTML already includes both the Vega and static plots. VS Code already has what they need, and no special output needs to be developed in DVC.
* VS Code can specify the output location and have all the data they need (the HTML and the static plot files). They can manage temporary directories and cleanup however they want.
* The HTML template is [configurable](https://dvc.org/doc/command-reference/plots#html-templates), so VS Code could use its own and have less risk of breaking changes.

**Comment by shcheklein** [comment]
> This sounds ugly

Yep :)

It sounds a bit too risky to use HTML (and maintain its backward compatibility). We'll have to go away from this for sure and it doesn't sound worth spending time on implementing HTML parser.

What was wrong with initial proposal - expand `--show-vega` to return multiple targets.

For images - I would add a separate API that generates a directory with a predefined structure.

**Comment by shcheklein** [comment]
> The HTML template is configurable, so VS Code could use its own and have less risk of breaking changes.

It doesn't help much unless `{plot_divs}` is extremely simple and we are 100% we won't be changing it in the future.

Again, just not sure what was so wrong with the initial proposed `--show-vega` with multiple targets and generating dir with images also doesn't sound that complicated.

**Comment by pared** [comment]
@shcheklein it is not about complexity, we started questioning the necessity of the existence of duplicated API (JSON one) when we already have one (unofficial and pythonic, but still). Anyway it seems that HTML will be too complicated to handle.

> For images - I would add a separate API that generates a directory with a predefined structure.

How would that look like? New option? `--show-images`?

**Comment by shcheklein** [comment]
> when we already have one

Yep, I get it. But we can't consume it now unless I'm missing something.

> How would that look like? New option? --show-images?

something like this, yep

**Comment by dberenbaum** [comment]
Sorry for the delay. I wanted to think about it a bit. Overall, I'm still wondering whether it makes sense to implement new functionality right now rather than go as far as possible with existing functionality first.

> It seems like we are redoing the Python API as a JSON output. Do we want to do this? If so, it might clarify things and we can at least have consistency. On the other hand, it might be redundant and doesn't necessarily have a lot of general use unless others can't use Python.

@shcheklein What do you think about this? Do you see the current direction as a long-term solution? If you feel confident that it has long-term benefits, then sure, let's spend the time to get them right. I want to make sure we aren't prematurely committing to a more time-consuming short-term solution.

> Again, just not sure what was so wrong with the initial proposed `--show-vega` with multiple targets and generating dir with images also doesn't sound that complicated.

@pared mentioned that it seems like we are duplicating an existing API, which I worry has little value outside of this use case and could extend to other features and commands. Even if each request is not that complicated, it creates an inefficient workflow. The VS Code team has to figure out requirements ahead of time, relay them to the DVC team, wait for the DVC team to implement them, validate that it meets their requirements, then possibly iterate to resolve discrepancies.

**Comment by rogermparent** [comment]
> it seems like we are duplicating an existing API, which I worry has little value outside of this use case and could extend to other features and commands.

While the CLI-as-API technique is ugly and comes with its own problems, we're certainly going to need some way to get these APIs into a non-Python format to encourage users to make DVC integrations that aren't locked to Python, and JSON is a pretty viable format for this considering JS is continuously engulfing all of software development and all other languages have some kind of JSON parser regardless.

Is there anywhere the Python plots API is documented? I don't see it in the dvc.org docs. I remember it being described in the last cross-team meeting as undocumented but internally used.

The VSCode team could use docs for the Python API to either create a small embedded Python script that translates it for us or use a fully-fledged Python->Node bridge like [boa](https://github.com/imgcook/boa) which @mattseddon has been experimenting with to minor success. This could be a good middle-ground where the duplicated API doesn't have to be in dvc itself, and the VSCode team can get it in quickly without putting possibly shoddy code in DVC itself, then we can work on it for a possible extraction and future public release for others in the "I want to use DVC API in Node" use case we find ourselves in.

Happy to continue discussion either here, in the cross-team meeting today, or both.

**Comment by pared** [comment]
> How would that look like? New option? --show-images?

@shcheklein I am not a fan of such solution, because in that case we start to separate the plots by their type. To me, it seems that more viable option would be just a generic `dvc plots show --show-json` where the json contains information depending on plot type. Eg:
`{"type": "vega", "data": {...}}` would mean that this is a vega plot and `data` is (for example) vega dict. `{"type": "image", "URL": {...}}` would mean binary data type that user needs to access via URL.

**Comment by shcheklein** [comment]
> would mean binary data type that user needs to access via URL.

@pared is it possible at all? Or do you want to generate the dir along the way?

**Comment by shcheklein** [comment]
> On the other hand, it might be redundant and doesn't necessarily have a lot of general use unless others can't use Python.

@dberenbaum to @rogermparent point I think `--json` is a very regular thing to have. Since it usually builds on top of some regular internal Python API it's not a problem in terms of redundancy. It's just a matter of what downstream tools could consume. In our case, unless I'm missing some options, we don't have a way to consume Python, so one way or another we'll need a non-Python interface to that API. 

> @pared mentioned that it seems like we are duplicating an existing API

It should be done in a way that it's not duplicating an API, but rather provides an alternative interface to that API. (regular CLI itself is another alternative interface that ideally should be built on top of API).

**Comment by pared** [comment]
> It should be done in a way that it's not duplicating an API, but rather provides an alternative interface to that API. (regular CLI itself is another alternative interface that ideally should be built on top of API) 

If we want to have an alternative UI to CLI then probably we would need to handle the images in a similar way as we do in a normal CLI call: we would need a dir to store the results of the visualization. That is also an option, though it will probably clutter the repo. But if default would be `.dvc/tmp` that might just do the trick.

**Comment by rogermparent** [comment]
> But if default would be `.dvc/tmp` that might just do the trick.

VSCode can can access `.dvc/tmp` pretty easily regardless of the project (unlike `.git`), so I think if that's a solution we can definitely run with.

**Comment by pared** [comment]
I have rebased this PR. We can merge it and I start working on more generic solution right away.

**Comment by pared** [comment]
After some discussion and consideration, it seems that we will introduce new generic option that will handle `image` type plots too. It seems that there is no need to merge this change, as it would break previously existing `--show-vega`. Closing for now, we can reconsider that if we see users demand for it.

**Pull request closed without merging**
