### PR TITLE
`run`: update `-h` message

### PR DESCRIPTION
**Pull request by kurianbenoy**
Fixes issue #6186 

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Review by jorgeorpinel — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
@kurianbenoy thanks for the update.

> If this PR requires documentation updates

Notice I unchecked that box. This will require an update in https://dvc.org/doc/command-reference/exp/run. Would you like to contribute that too?

**Comment by jorgeorpinel** [comment]
I wonder if we should still mention `dvc repro` thouogh, since it's still what `exp run` does... WDYT @shcheklein ?

**Comment by kurianbenoy** [comment]
Sure I will like to contribute to docs as well. Thanks @jorgeorpinel for approving

**Comment by kurianbenoy** [comment]
@jorgeorpinel for docs what are changes required? I see two changes only:

1. Run an experiment: reproduce a variation of a committed pipeline in a hidden project branch. change to `Run or Resume an experiment`
2. Remove statement : Similar to dvc repro but for experimentation.

**Comment by jorgeorpinel** [comment]
> 1. ... change to Run or Resume an experiment

Yep. Just keep the link to `dvc exp` please.

> 2. Remove statement...

I didn't understand this point.

**Comment by kurianbenoy** [comment]
> > 1. ... change to Run or Resume an experiment
> 
> Yep. Just keep the link to `dvc exp` please.
> 
> > 1. Remove statement...
> 
> I didn't understand this point.
> I wonder if we should still mention dvc repro thouogh, since it's still what exp run does... WDYT @shcheklein ?

You had asked this question previously right? That's why I asked should line mentioning dvc repro really needed now.

**Comment by jorgeorpinel** [comment]
Right @kurianbenoy. I think we can remove the top note about `repro` indeed. It's mentioned again early in the Description anyway.

**Comment by efiop** [comment]
Thanks @kurianbenoy and @jorgeorpinel ! :pray:

**Pull request merged**
