### PR TITLE
config/remote/cache: make --system/--global/--local mutually exclusive

### PR DESCRIPTION
**Pull request by efiop**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).

https://github.com/iterative/dvc.org/pull/1416

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by efiop** [comment]
Not a biggie or anything, just noticed while talking with a user.

**Comment by shcheklein** [comment]
add a test?

**Comment by efiop** [comment]
@shcheklein Was kinda resiting it, because it is declarative as is. But yeah, sure, will add one in a sec.

**Comment by efiop** [comment]
Actually, after giving it another thought - will pass on this one, as it will require testing all of those commands (which is excessive) or unit testing specific parser, but it is not really guaranteed to be used. It is declarative as is and the potential bugs are pretty much non-existent (it will just overwrite with the latest flag), so it is not really worth the time in this case.

**Pull request merged**
