### PR TITLE
Fix typo and grammar

### PR DESCRIPTION
**Pull request by skshetry**
* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [x] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addresses. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

This PR fixes:
- [x] typo in `data_cloud.py` docstring
- [x] grammar in PR template

### CODE REVIEW

**Comment by skshetry** [comment]
Grammarly is complaining about the PR template. Fixing it  ...

**Comment by casperdcl** [comment]
xD I wonder if there's a good spell check integration for code comments & markdown.

Grammar on the other hand is hard. Technically still incorrect even after this PR.

**Comment by skshetry** [comment]
@casperdcl, "Inspect Code" on PyCharm also looks through spellcheck on the codebase. I have a WIP branch, but I haven't been able to scan through everything. I'll make a PR sometime this week.

**Comment by efiop** [comment]
@casperdcl Had the same thoughts but I've done some research earlier and haven't been able to find any nice CLI tool to check that in the code 🙁In any case, nothing beats the perception of a native speaker, so if you see anything wrong with the wording, please let us know or, if you are feeling generous, even create a PR to fix it 🙂

**Comment by efiop** [comment]
@skshetry PyCharm is really making it tempting to switch to it, I might need to try it out once again 🙂

**Comment by casperdcl** [comment]
@efiop I was wondering about doing something hacky like comparing all words in a diff to a dictionary (with some trickery to find out if it's part of a code comment or markdown)

**Comment by mroutis** [comment]
> @skshetry PyCharm is really making it tempting to switch to it, I might need to try it out once again slightly_smiling_face

@efiop , @casperdcl  `:set spell` :slightly_smiling_face:

**Comment by mroutis** [comment]
Maybe we can enable https://github.com/languagetool-org/languagetool for the CI (btw. it is also available in Vim)

**Pull request merged**
