### PR TITLE
Handle filenames which has ":" 

### LINKED ISSUE #8773: add: Filenames containing the : character give an error.
# Bug Report

## Description

DVC doesn't recognise file paths containing the : character, and instead tries to treat them as URLs, giving the error (for the file filena:me):

```console
ERROR: config file error: Unsupported URL type filena:// 
```

### Reproduce

1. dvc init
2. touch filena:me
3. dvc add filena:me
### Expected

File should be added to the dvc repository.
### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.38.1 (conda)
---------------------------------
Platform: Python 3.11.0 on macOS-13.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.28.4
	dvc_objects = 0.14.0
	dvc_render = 0.0.15
	dvc_task = 0.1.8
	dvclive = 1.3.0
	scmrepo = 0.1.4
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	ssh (sshfs = 2022.6.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Additional Information (if any):**

### PR DESCRIPTION
**Pull request by karanjakhar**
fixes #8773 issue

* [ x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Review by daavoo — CHANGES_REQUESTED** [review]
Thanks for the contribution @karanjakhar 

Could you add a test for this? For example in https://github.com/iterative/dvc/blob/main/tests/func/test_add.py

**Comment by karanjakhar** [comment]
@daavoo  done.

**Review by daavoo — DISMISSED** [review]

**Comment by karanjakhar** [comment]
@daavoo Tests for Windows are failing. As it doesn't allow ":" in the filename. Should I make this test skip Windows?

**Review by daavoo — CHANGES_REQUESTED** [review]
@karanjakhar tests are failing on windows. 

Afaik,`:` is an invalid character for windows filenames, so we might just skip the test in windows

**Comment by karanjakhar** [comment]
@daavoo done :)

**Review by daavoo — APPROVED** [review]

**Pull request merged**
