### PR TITLE
dvcfs: add basic fsid

### LINKED ISSUE #9904: dvc import: imports the same file twice from 2 different repos
# Bug Report

## Description

`dvc import` is importing the same file twice, even though the repos are different
Basically I have 2 repos:
- git@gitlab.com:organization/path/my-model-1.git
- git@gitlab.com:organization/path/my-model-2.git
and each is a DVC repo that contains `params.yaml`
My goal is two combine the 2 models into an application, therefore I need their respective `params.yaml` files. However, `dvc import` somehow gets confused (probably because paths are the same in each repo?) and pulls the same file. Moreover, what's really weird is that hashes on these files are different and link to different locations in cache. Essentially, everything looks fine, but when reading or diff'ing the contents are the same.

`
(.venv) mzurad@workstation:~/code/pe-test/params$ dvc import -v -o my-model-1/params.yaml --rev mvp1 git@gitlab.com:organization/path/my-model-1.git params.yaml
`
```
2023-09-01 17:13:23,015 DEBUG: v3.16.0 (pip), CPython 3.8.10 on Linux-5.15.0-76-generic-x86_64-with-glibc2.29
2023-09-01 17:13:23,015 DEBUG: command: /home/mzurad/code/pe-test/.venv/bin/dvc import -v -o my-model-1/params.yaml --rev mvp1 git@gitlab.com:organization/path/my-model-1.git params.yaml
2023-09-01 17:13:23,192 DEBUG: Lockfile for '../dvc.yaml' not found   
2023-09-01 17:13:23,235 DEBUG: Removing output 'my-model-1/params.yaml' of stage: 'my-model-1/params.yaml.dvc'.
2023-09-01 17:13:23,235 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-1/params.yaml'
Importing 'params.yaml (git@gitlab.com:organization/path/my-model-1.git)' -> 'my-model-1/params.yaml'
2023-09-01 17:13:23,236 DEBUG: Computed stage: 'my-model-1/params.yaml.dvc' md5: '15fa312651a71503cb5d70f966ed6b93'
2023-09-01 17:13:23,236 DEBUG: 'md5' of stage: 'my-model-1/params.yaml.dvc' changed.
2023-09-01 17:13:23,237 DEBUG: Creating external repo git@gitlab.com:organization/path/my-model-1.git@mvp1
2023-09-01 17:13:23,237 DEBUG: erepo: git clone 'git@gitlab.com:organization/path/my-model-1.git' to a temporary dir
2023-09-01 17:13:54,198 DEBUG: Added '/home/mzurad/code/pe-test/params/my-model-1/params.yaml' to gitignore file.                                                                                                                                                            
2023-09-01 17:13:54,203 DEBUG: Computed stage: 'my-model-1/params.yaml.dvc' md5: '9a69e96782c14aaa4e52487c8b37ce3f'                                                                                                                                                          
2023-09-01 17:13:54,205 DEBUG: Preparing to transfer data from 'memory://dvc-staging-md5/b6b933eae94b5eb503e0ed377c47ba354b401e2e12939b51eee68cbec9214da7' to '/mnt/ssd2/.shared-dvc-cache/files/md5'                                                                              
2023-09-01 17:13:54,205 DEBUG: Preparing to collect status from '/mnt/ssd2/.shared-dvc-cache/files/md5'
2023-09-01 17:13:54,205 DEBUG: Collecting status from '/mnt/ssd2/.shared-dvc-cache/files/md5'
2023-09-01 17:13:54,206 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-1/.3UKsg3Bp6ZyCeLdTARmCcj.tmp'                                                                                                                                                            
2023-09-01 17:13:54,206 DEBUG: Removing '/mnt/ssd2/.shared-dvc-cache/files/md5/.j9wLPKuidEjA5cFkHqbcEf.tmp'
2023-09-01 17:13:54,207 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-1/params.yaml'                                                                                                                                                                            
2023-09-01 17:13:54,216 DEBUG: Saving information to 'my-model-1/params.yaml.dvc'.                                                                                                                                                                                           

To track the changes with git, run:

        git add my-model-1/params.yaml.dvc my-model-1/.gitignore

To enable auto staging, run:

        dvc config core.autostage true
2023-09-01 17:13:54,242 DEBUG: Analytics is disabled.
```

`
(.venv) mzurad@workstation:~/code/pe-test/params$ dvc import -v -o my-model-2/params.yaml --rev mvp1 git@gitlab.com:organization/path/my-model-2.git params.yaml
`
```
2023-09-01 17:14:38,752 DEBUG: v3.16.0 (pip), CPython 3.8.10 on Linux-5.15.0-76-generic-x86_64-with-glibc2.29
2023-09-01 17:14:38,752 DEBUG: command: /home/mzurad/code/pe-test/.venv/bin/dvc import -v -o my-model-2/params.yaml --rev mvp1 git@gitlab.com:organization/path/my-model-2.git params.yaml
2023-09-01 17:14:38,932 DEBUG: Lockfile for '../dvc.yaml' not found   
2023-09-01 17:14:38,976 DEBUG: Removing output 'my-model-2/params.yaml' of stage: 'my-model-2/params.yaml.dvc'.
2023-09-01 17:14:38,976 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-2/params.yaml'
Importing 'params.yaml (git@gitlab.com:organization/path/my-model-2.git)' -> 'my-model-2/params.yaml'
2023-09-01 17:14:38,977 DEBUG: Computed stage: 'my-model-2/params.yaml.dvc' md5: '9d0288dd444947e3619c29c13df172b3'
2023-09-01 17:14:38,977 DEBUG: 'md5' of stage: 'my-model-2/params.yaml.dvc' changed.
2023-09-01 17:14:38,978 DEBUG: Creating external repo git@gitlab.com:organization/path/my-model-2.git@mvp1
2023-09-01 17:14:38,978 DEBUG: erepo: git clone 'git@gitlab.com:organization/path/my-model-2.git' to a temporary dir
2023-09-01 17:14:40,915 DEBUG: Computed stage: 'my-model-2/params.yaml.dvc' md5: 'd7fec615a6cbc356c22decc92e3196a7'                                                                                                                                                       
2023-09-01 17:14:40,916 DEBUG: Preparing to transfer data from 'memory://dvc-staging-md5/b6b933eae94b5eb503e0ed377c47ba354b401e2e12939b51eee68cbec9214da7' to '/mnt/ssd2/.shared-dvc-cache/files/md5'                                                                              
2023-09-01 17:14:40,916 DEBUG: Preparing to collect status from '/mnt/ssd2/.shared-dvc-cache/files/md5'
2023-09-01 17:14:40,916 DEBUG: Collecting status from '/mnt/ssd2/.shared-dvc-cache/files/md5'
2023-09-01 17:14:40,917 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-2/.L5oNdGLoWLgLqSjjuZn2uv.tmp'                                                                                                                                                         
2023-09-01 17:14:40,917 DEBUG: Removing '/mnt/ssd2/.shared-dvc-cache/files/md5/.2Xb5Zy6mCsftwqz96Qr838.tmp'
2023-09-01 17:14:40,918 DEBUG: Removing '/home/mzurad/code/pe-test/params/my-model-2/params.yaml'                                                                                                                                                                         
2023-09-01 17:14:40,927 DEBUG: Saving information to 'my-model-2/params.yaml.dvc'.                                                                                                                                                                                        

To track the changes with git, run:

        git add my-model-2/params.yaml.dvc

To enable auto staging, run:

        dvc config core.autostage true
2023-09-01 17:14:40,934 DEBUG: Analytics is disabled.
```
`
(.venv) mzurad@workstation:~/code/pe-test/params$ tree
`
```
.
├── my-model-2
│   ├── params.yaml -> /mnt/ssd2/.shared-dvc-cache/files/md5/91/3affb56fb36f9bc9416cd569790a90
│   └── params.yaml.dvc
└── my-model-1
    ├── params.yaml -> /mnt/ssd2/.shared-dvc-cache/files/md5/ab/32d18a00bd85ffbcb2d78d927dbbb3
    └── params.yaml.dvc

2 directories, 4 files
```

`(.venv) mzurad@workstation:~/code/pe-test/params$ cat my-model-1/params.yaml.dvc `
```
d5: 9a69e96782c14aaa4e52487c8b37ce3f
frozen: true
deps:
- path: params.yaml
  repo:
    url: git@gitlab.com:organization/path/my-model-1.git
    rev: mvp1
    rev_lock: 21e10a81912609f8419522688fc51a92db1ed394
outs:
- md5: ab32d18a00bd85ffbcb2d78d927dbbb3
  size: 1560
  hash: md5
  path: params.yaml
```

`(.venv) mzurad@workstation:~/code/pe-test/params$ cat my-model-2/params.yaml.dvc `
```
md5: d7fec615a6cbc356c22decc92e3196a7
frozen: true
deps:
- path: params.yaml
  repo:
    url: git@gitlab.com:organization/path/my-model-2.git
    rev: mvp1
    rev_lock: 9840ae9b84c4f300d36da06b052e297a3a2e579e
outs:
- md5: 913affb56fb36f9bc9416cd569790a90
  size: 1335
  hash: md5
  path: params.yaml
```

```bash
(.venv) mzurad@workstation:~/code/pe-test/params$ diff my-model-2/params.yaml my-model-1/params.yaml
(.venv) mzurad@workstation:~/code/pe-test/params$ 
```

### Reproduce

I can't seem to reproduce this.

### Expected

Files should be correctly imported.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.16.0 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-5.15.0-76-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2023.7.0)
Config:
        Global: /home/mzurad/.config/dvc
        System: /etc/xdg/dvc
Cache types: symlink
Cache directory: ext4 on /dev/nvme0n1
Caches: local
Remotes: ssh, ssh
Workspace directory: ext4 on /dev/nvme1n1p2
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/a15a3498ef6bebff6bb2e7fb9e33e35e


```

**Additional Information (if any):**

### PR DESCRIPTION
**Pull request by efiop**
Implements fsspec's fsid https://github.com/fsspec/filesystem_spec/pull/1122

Note that this is not rigid and we can change it up as we go.

Depends on https://github.com/iterative/dvc-data/pull/436
Fixes #9904

### CODE REVIEW

**Comment by shcheklein** [comment]
Getting this here from Slack for visibility and to not mix conversations.

Curious if this can and should be tested.

**Comment by efiop** [comment]
@shcheklein If you are talking about the linked issue then no, this is not a dvc-level thing, this is a dvc-data/fs level logic fault, there is no simple good test for that.

**Comment by shcheklein** [comment]
> @shcheklein If you are talking about the linked issue then no, this is not a dvc-level thing, this is a dvc-data/fs level logic fault, there is no simple good test for that.

A unit test on the dvc-data/fs side? That we identify / dedup FS instances by specific fields? (id vs protocol + something)?

**Comment by efiop** [comment]
@shcheklein I don't think it is necessary right now.

**Comment by efiop** [comment]
Added tests in https://github.com/iterative/dvc/pull/9934 and caught noscm bug 🤦

**Pull request merged**
