### PR TITLE
add abspath option to Output.is_in_repo

### PR DESCRIPTION
**Pull request by endremborza**
Just a very quick check for a fix for #7118 without downloading, running or linting anything, sorry if this distracting, I just didn't want to set up the environment on my new machine again and hoped the CI will resolve whether this breaks any tests.

* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

### CODE REVIEW

**Comment by endremborza** [comment]
test break seems to be unrelated, and this change solves my problem with the symlinked cache of #7118 , so please indicate possible needed modifications.

**Comment by pared** [comment]
Fixes #7118 
@endremborza what use case this check break? Maybe we need a test for that.

**Comment by endremborza** [comment]
I don'r know what might be broken by this, the CI I'm pretty sure is not failing due to the change.

**Comment by pmrowla** [comment]
I think @pared's point was that this PR should probably add a test case for the original issue (where adding a symlinked file to an alternate cache location caused some problem)

**Comment by karajan1001** [comment]
> I don'r know what might be broken by this, the CI I'm pretty sure is not failing due to the change.

Let me rerun it, the CI is still not very stable 🤔 ?

**Comment by pmrowla** [comment]
Thanks for adding the test @endremborza

This still needs a bit more investigation on our part, but this PR may be an acceptable short-term workaround.

It's clear that resolving the entire output path doesn't work in this case (since the symlink to a file outside the repo should be considered valid), so what we probably need to do is actually adjust the stage/output/dep paths so that they are properly aligned up to the resolved repo path (as described in https://github.com/iterative/dvc/pull/5954)

@skshetry you did the investigation on the original PR, WDYT?

**Comment by pmrowla** [comment]
> @skshetry Pinging about the question above. 🙏

@dberenbaum this was discussed in a sprint meeting and the result was noted in the original issue (this bug will likely be resolved by the DVC data changes)

https://github.com/iterative/dvc/issues/7118#issuecomment-1040269129

**Comment by skshetry** [comment]
I'm sorry to close this one, but it looks like this requires further investigation/research into the issue. Please follow issue #7668 for updates. 🙂

**Comment by dberenbaum** [comment]
@iterative/dvc Is there opposition to revisiting this?

**Pull request closed without merging**
