### PR TITLE
Add AUR package

### PR DESCRIPTION
**Pull request by mroutis**

### CODE REVIEW

**Comment by mroutis** [comment]
thanks, @efiop, missed that one

**Comment by efiop** [comment]
I guess it is worth marking it anyway in both README.rst and on AUR, just to avoid possible confusion, since we can't officially guarantee anything for those packages because we don't support them ourselves. Could you please mark it as "unofficial" in both README.rst and on AUR?

**Comment by mroutis** [comment]
done, @efiop, also, I pinned a comment making it clearer on AUR :)

https://aur.archlinux.org/packages/dvc/

**Comment by mroutis** [comment]
If there's anything wrong with the package, feel free to open an issue/PR in https://github.com/mroutis/pkgbuilds

**Comment by efiop** [comment]
Thank you so much! Merged!

**Comment by efiop** [comment]
Btw, @mroutis would you be willing to have a video call with us? We are very interested in what you do and would love to have an ability to ask you a couple of questions.

**Comment by mroutis** [comment]
sure, @efiop! write me an email: mroutis at protonmail dot com

**Comment by efiop** [comment]
Great! Sent you an email. Thank you!

**Pull request merged**
