### PR TITLE
exp run: add experiment name check.

### LINKED ISSUE #6652: exp run: Results cannot be found if experiment name includes space
# Bug Report

## Description 
When running an experiment with white space in the name, the resulting experiment does not show up in `exp show` later.

### Reproduce

1. `dvc exp run --name "some name": Experiments runs as expected.
2. `dvc exp show`: Experiment is not listed.

### Expected

I would expect that either

- `dvc exp run` should refuse to assign names with white space in them,
- or `dvc exp show` shows this experiment in the summary regardless of the white space in the name.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.7.2 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-5.14.5-arch1-1-x86_64-with-arch
```

### LINKED ISSUE #6674: exp run -n: check for conflicts before running experiment
`dvc exp run -n` will throw an error if a naming conflict arises, but it won't check until after the experiment has completed. 

I guess someone could re-run the experiment later with a new name and the run-cache should prevent the whole experiment from needing to be executed, but this doesn't seem intuitive, and it would be better to know immediately that the experiment name conflicts with an existing experiment.

Steps to reproduce:

```
$ dvc init
$ echo "p: 0" > params.yaml
$ dvc stage add -p p -n test "echo test"
$ dvc exp run -n test
Running stage 'test':
> echo test
test
Generating lock file 'dvc.lock'
Updating lock file 'dvc.lock'

To track the changes with git, run:

        git add dvc.yaml dvc.lock params.yaml

Reproduced experiment(s): test
Experiment results have been applied to your workspace.

To promote an experiment to a Git branch run:

        dvc exp branch <exp> <branch>
$ dvc exp run -n test -S p=1
Running stage 'test':
> echo test
test
Updating lock file 'dvc.lock'

To track the changes with git, run:

        git add params.yaml dvc.yaml dvc.lock
ERROR: Reproduced experiment conflicts with existing experiment 'refs/exps/d4/5e189b914d70882bd67b041110f3f27a30f941/test'. To overwrite the existing experiment run:

        dvc exp run -f ...

To run this experiment with a different name run:

        dvc exp run -n <new_name> ...
```

### PR DESCRIPTION
**Pull request by karajan1001**
fix #6674 and fix #6652 

1. Add experiment name check (https://git-scm.com/docs/git-check-ref-format)
2. Add duplicate exp name check.
3. Add some unit test for it.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

@pmrowla , in #6819,  exp name with '/' inside are request. And these types of exp names are stored in a subdirectory.  For example in #6843, it is stored in `.git/refs/heads/dependabot/pip/pylint-2.11.1`. The subdirectory here is used for grouping branches. Currently, our `dvc exp` did not support this. It involves not only name checking here, maybe we should reopen #6819 and create a new PR for it?

### CODE REVIEW

**Comment by pmrowla** [comment]
> @pmrowla , in #6819, exp name with '/' inside are request. And these types of exp names are stored in a subdirectory. For example in #6843, it is stored in `.git/refs/heads/dependabot/pip/pylint-2.11.1`. The subdirectory here is used for grouping branches. Currently, our `dvc exp` did not support this. It involves not only name checking here, maybe we should reopen #6819 and create a new PR for it?

We should not support slashes in experiment names. Yes, the full ref can contain slashes, and we already use slashes in exp refs to organize them, but the user-readable (short) name should not contain slashes - the same as git branch (short) names.

**Comment by pmrowla** [comment]
Ah ok, that's my misunderstanding then, I didn't think cgit allowed you to nest anything in `refs/heads`. I guess that could be re-opened as a feature request, but I'm still not sure we should support it, unless it becomes something that is more frequently requested from users. I'd prefer to just keep everything in `refs/exps/...` namespaces completely reserved for DVC use for now.

**Comment by karajan1001** [comment]
> > I'd prefer to just keep everything in `refs/exps/...` namespaces completely reserved for DVC use for now.
> 
> Is it harder to handle nested refs in `refs/exps`? Or is there some other reason not to allow slashes? @karajan1001 makes a good point that this could be a helpful way to organize, plus it would solve #6819.

The `dulwich` backend support `/` in exp name, and actually our full reference is inside the subdirectory named by the `HEAD` revision. But still some problems on the DVC side, for example currently we use `/` to separate refname and the last part as the human-readable one, this should be changed. I don't think it is very difficult to support `/` in ref name, but still need some effort.

**Comment by jorgeorpinel** [comment]
From what I understand this fixes bugs so no docs changes are needed (I checked the box).

**Comment by karajan1001** [comment]
> > From what I understand this fixes bugs so no docs changes are needed (I checked the box).

This PR forbids the duplicate name and name with some illegal character (space, asterisk, etc), in my opinion, better to make an error msg if someone wants to use an illegal name.

**Comment by jorgeorpinel** [comment]
OK I created https://github.com/iterative/dvc.org/pull/3065 then.

**Pull request merged**
