### PR TITLE
introduce dataset dependency

### PR DESCRIPTION
**Pull request by skshetry**
#### Example `dvc.yaml`
```yaml
datasets:
  - name: dogs
    type: dvcx
    version: 2

  - name: publaynet
    type: webdataset
    url: "http://storage.googleapis.com/nvdata-publaynet/publaynet-train-{000000..000009}.tar"

  - name: stackoverflow
    type: dvc
    url: git@github.com:iterative/example-get-started.git
    rev: main
    path: data/data.xml
```

```console
echo foo > foo
dvc stage add -n test -d ds://dogs -d foo "cp foo bar"
dvc repro
dvc status
# change version in `datasets` and run `dvc status` and `dvc repro` again.
```

```python
from dql.query import DatasetQuery
from dvc.api.dataset import DVCxDataset, get

resolved = get(DVCxDataset, "dogs")
ds = DatasetQuery(name=resolved.name, version=resolved.version)
```

```python
from dvc.api.dataset import DVCDataset, get
from dvc.fs.dvc import DVCFileSystem

resolved = get(DVCDataset, "stackoverflow")
fs = DVCFileSystem(url=resolved.url, rev=resolved.rev)
with fs.open(resolved.path) as f:
    process_posts(f.readlines())
```

```python
import webdataset as wds
from dvc.api.dataset import WebDataset, get

resolved = get(WebDataset, "publaynet")
dataset = wds.WebDataset(resolved.url)
```

Requires `pydantic>=2` at the moment.

<details><summary>Complete dvc.yaml file</summary>
<p>

```yaml
datasets:
- name: dogs
  type: dvcx
  version: 3

- name: publaynet
  type: webdataset
  url:
    http://storage.googleapis.com/nvdata-publaynet/publaynet-train-{000000..000009}.tar

- name: stackoverflow
  url: git@github.com:iterative/example-get-started.git
  rev: main
  path: data/data.xml

- name: tiny
  type: dvcx
  version: 3

stages:
  test:
    cmd: cp foo bar
    deps:
    - ds://dogs
    - foo
```

</p>
</details> 

<details><summary>Complete dvc.lock file</summary>
<p>

```yaml
schema: '2.0'
stages:
  test:
    cmd: cp foo bar
    deps:
    - path: ds://dogs
      dataset:
        name: dogs
        type: dvcx
        version: 3
    - path: foo
      hash: md5
      md5: d3b07384d113edec49eaa6238ad5ff00
      size: 4
```

</p>
</details> 

### Screenplay

[asciicast](https://asciinema.org/a/0EiH4hfr9XtIF3HGndyyphKRH)
---

#### Note regarding Public API

We can easily change API if needed. I wanted to start with something that is type-safe, and that gives a good completions to the users.

### CODE REVIEW

**Comment by skshetry** [comment]
@dberenbaum, this PR is a very basic implementation. But I wanted to get a feedback if this was something you had in mind in regard to pipelines and datasets. Please have a look and let me know what you think.

**Comment by dberenbaum** [comment]
Looks good and aligns with what we discussed.

I added the `.dql/config` file mentioned in https://github.com/iterative/dvc/pull/10123#issue-2016682918 but so far not able to get the actual API working:

```sh
$ python ds.py
Traceback (most recent call last):
  File "/private/tmp/dvcx/ds.py", line 6, in <module>
    ds = DatasetQuery(name=resolved.name, version=resolved.version)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/dql/query/dataset.py", line 1146, in __init__
    ds = data_storage.get_dataset(name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/dvc/lib/python3.11/site-packages/dql/data_storage/abstract.py", line 1068, in get_dataset
    raise DatasetNotFoundError(f"Dataset {name} not found.")
dql.error.DatasetNotFoundError: Dataset dogs not found.

$ dvcx pull dogs -o dogs
Error: Error when parsing dataset uri
```

I can try to look into it more or ask dvcx team, but let me know if you have ideas on what might be wrong.

I think we will need input from DVCX team on:
1. What version info to store in dvc.lock
2. What the API should return

**Comment by skshetry** [comment]
I think you have to `pull` the index first before using `DatasetQuery`. Also `dql pull` needs `ds://` scheme.

```console
dql pull ds://dogs --no-cp
```

**Comment by shcheklein** [comment]
Cool stuff. Thanks @skshetry  for prototyping and sharing this quickly. Folks, can we add the `dvc.lock` file after running the pipeline, and the complete `dvc.yaml` - just to see how it looks like.

**Comment by skshetry** [comment]
@shcheklein, `dvc.lock` looks something as follows:
```yaml
schema: '2.0'
stages:
  test:
    cmd: cp foo bar
    deps:
    - path: ds://dogs
      dataset:
        name: dogs
        type: dvcx
        version: 3
    - path: foo
      hash: md5
      md5: d3b07384d113edec49eaa6238ad5ff00
      size: 4
```

It is inside `deps`, but we'll likely move it to a separate section as with `params`. `deps` has been used for local/external-filesystems based dependencies, so I'd probably create a separate section (but still thinking about it).

The `dataset` section at the moment contains same information as in `dvc.yaml` top-level datasets section and is compared to know if the stage changed or not, and whether to reproduced or not.

**Comment by dberenbaum** [comment]
> I think you have to `pull` the index first before using `DatasetQuery`.

Yup, that fixed it, thanks!

It seems like this isn't a good UX, and we will need a way to see what dataset versions are available on studio without pulling their indexes locally. Do you know if it's a priority for the DVCX team? Would it make sense to contribute back this functionality?

**Comment by skshetry** [comment]
You can try out with something like following to test: 
```python
from dql.catalog import get_catalog
from dql.dataset import create_dataset_uri
from dql.query import DatasetQuery
from dvc.api.dataset import DVCxDataset, get

resolved = get(DVCxDataset, "dogs")
catalog = get_catalog()
catalog.pull_dataset(create_dataset_uri(resolved.name, version=resolved.version), no_cp=True)
ds = DatasetQuery(name=resolved.name, version=resolved.version, catalog=catalog)
```

`DatasetQuery` feels low-level to create this auto-pull around. Maybe there will be some high-level wrappers around to do this. We were using a different API before, and now we are not even responsible for anything than materializing the metadata that we have. I'd rather prefer someone from dvcx team propose API here. It'd be wrong for me to try to fit what we have here to their API.

**Comment by dmpetrov** [comment]
@skshetry excellent work!

It would be great to know how `datasets:` section is populated. It should help better understand the UI aspects such as --no-cp.

This might be outside of the scope: do we plane to support his `type: webdataset`? Also, how about importing a cloud-versioning file from S3? What type it should be?

**Comment by skshetry** [comment]
> It would be great to know how `datasets:` section is populated. It should help better understand the UI aspects such as --no-cp.

`datasets` section is populated by users themselves (we could provide a CLI command to generate in the future).

> > This might be outside of the scope: do we plane to support his `type: webdataset`? Also, how about importing a cloud-versioning file from S3? What type it should be?

At the moment, we only provide an API to give you the metadata you have in `datasets` section. That's all that it does. (Note `webdataset` is just an example, it could be anything as it's only metadata.)

I have been thinking of what we can do with this metadata, hence my experiment with pydantic.
But I'm not clear if we want to be involved in materializing/streaming of datasets ourselves.
The idea is similar to https://github.com/iterative/dvc/issues/2719.

**Comment by dberenbaum** [comment]
Can/should dvc collect some lightweight info about the `datasets` and save them like stages with their own entries in `dvc.lock`?

For example, assume this `dvc.yaml`:

```yaml
datasets:
  dogs:
    name: dogs
    type: dvcx
    version: 3
  versioned:
    type: url
    url: s3://bucket/name/dir
    version_aware: true
stages:
  test:
    cmd: cp foo bar
    deps:
    - ds://dogs
    - foo
```

The `dvc.lock` could look like:

```yaml
schema: '2.0'
datasets:
  dogs:
    type: dvcx
    name: dogs
    version: 3
  versioned:
    type: url
    url: s3://bucket/name/dir
    files:
      - relpath: file1
        version_id: versionId
      - relpath: file2
        version_id: versionId
stages:
  test:
    cmd: cp foo bar
    deps:
    - path: ds://dogs
      dataset:
        name: dogs
        type: dvcx
        version: 3
    - path: foo
      hash: md5
      md5: d3b07384d113edec49eaa6238ad5ff00
      size: 4
```

This would support:
- cloud-versioned directories
- lightweight checksums - use version IDs or other available info to capture and validate the version without calculating file hashes or caching, although dvc will not be able to recover old versions if they are no longer available
- freezing datasets - if you want to keep using this version of the cloud-versioned directory rather than check for the latest version, set `frozen: true` for that dataset
- CLI:
  - `dvc datasets add dvcx dogs --info name=dogs,version=2` can add the entry to both `dvc.yaml` and `dvc.lock`
  - `dvc update ds://dogs` can update the entry

**Comment by dmpetrov** [comment]
> Can/should dvc collect some lightweight info about the `datasets` and save them 

It shouldn't since a portion of the data is in DB and data can be not materialized locally. If something is needed, it should be requested though a command like dvcx status `ds://cats@v1`.

**Comment by dberenbaum** [comment]
> > Can/should dvc collect some lightweight info about the `datasets` and save them
> 
> It shouldn't since a portion of the data is in DB and data can be not materialized locally. If something is needed, it should be requested though a command like dvcx status `ds://cats@v1`.

Yes, this is what I meant by "lightweight" @dmpetrov. I think we all are clear that DVC should not be calculating md5s etc. It seems like doing something like `dvcx status` would be ideal here. At minimum, it would be helpful to list available versions of datasets by name in dvcx. Are there plans for something like that?

**Comment by skshetry** [comment]
We discussed in the team meeting if we could fit this into the `import-url`/`import` workflow.

```console
$ dvc import-url dvcx://dogs@v3 --virtual
$ cat dogs.dvc
```
```yaml
md5: 43d8c1bfe46a6cf2cb9dfe00a8e431b3
frozen: true
deps:
- path: dvcx://dogs@v3
outs:
- hash: md5
  path: dogs # which is an alias for dvcx
  pull: false # or, virtual: true
```

The `path` will work similar to an alias or a name, but won't be materialized. If user's need to materialize, they can remove `pull: False`/`virtual: true`.

Also, `dvc update` will work automatically. We can add top-level datasets in the future if we need to. @pmrowla mentioned that we have `artifacts` section which is a metadata and has an alias that points to a path to a file, and `datasets` section is similar in that regard.

The `dataset.get()` method will work based on that alias or path.

**Comment by dberenbaum** [comment]
Caveat: This somewhat depends on the discussion in https://github.com/iterative/dql/issues/732 and goes back to https://github.com/iterative/dvc/issues/10114#issuecomment-1847099599, but I'm putting my current thoughts here so I don't lose them.

Does the proposal above mean that some pipeline stage could look like this?

```yaml
stages:
  process_dataset:
    cmd: ...
    deps:
    - dogs # alias to dvcx dataset?
```

Questions:
1. If we support syntax like `path: dvcx://dogs@v3`, can we list that directly as a stage dependency instead of doing an `import`?
2. Does `dvc.lock` look the same as above with info about the dataset version?
3. Does `dataset.get("dogs")` still make sense as an api?
4. What happens if I put some file/dir at path `dogs`?

I think it's more important to handle stage deps first, although it seems possible to support both. Handling datasets as deps could replace or streamline some `import` scenarios, especially when users prefer to stream the data. Maybe we can even combine ideas and call the top-level `dvc.yaml` section `imports`, where they act similar to other imports but don't get materialized anywhere in the workspace (the hash info could go into `dvc.lock` as mentioned above).

**Pull request merged**
