### PR TITLE
gha: allow builds for new 3.9 releases

### PR DESCRIPTION
**Pull request by pared**
Closes: #6975

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Seems like 3.9.9 got released yesterday. So the argparse should be back to previous behavior.

### CODE REVIEW

**Comment by skshetry** [comment]
@Mergifyio rebase

**Comment by skshetry** [comment]
@Mergifyio rebase

**Comment by skshetry** [comment]
@Mergifyio rebase

**Comment by pared** [comment]
@Mergifyio rebase

**Comment by skshetry** [comment]
@Mergifyio rebase

**Comment by pared** [comment]
@skshetry @efiop seems like 3.9.9 is now default 3.9 in `setup-python`.

**Pull request merged**
