### PR TITLE
exp queue: preserve failed exp status

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Initial `queue status` support for https://github.com/iterative/dvc/issues/7854. 
Logs support for completed exps will be done in a separate PR

- Failed exps are saved and visible in `dvc queue status`
- Does not implement remove or retry for failed exps (remove support will be added in a follow up after  https://github.com/iterative/dvc/pull/7841)
- Does not add failed exps to `dvc exp show`

[asciicast](https://asciinema.org/a/znhZ7UQWDgGF7bj0XWKtJMSKj)

forgot to note in the demo, autogenerated exp names for completed `--queue` runs are now also mapped correctly in `queue status`.

```
$ dvc exp run --queue -S featurize.max_features=2200
Queued experiment 'bf4fc8e' for future execution.

$ dvc queue status
Rev                                       Name            Created    Status
bf4fc8ecb50c4c592b898f6a22b58bcfca246b51                  05:36 PM   Queued
e631193c9ce3f64437b91e5441c02d98121b181a  failed-exp      05:28 PM   Failed
68061c96f7e153db1bfeda3be5b05858f64afa43  exp-7b169       05:35 PM   Success
03531a55e6442ee58eb471fb0e3175406fdf5279  successful-exp  05:27 PM   Success

$ dvc queue start
Start 1 queue worker to process the queue tasks

$ dvc queue status
Rev                                       Name            Created    Status
e631193c9ce3f64437b91e5441c02d98121b181a  failed-exp      05:28 PM   Failed
68061c96f7e153db1bfeda3be5b05858f64afa43  exp-7b169       05:35 PM   Success
03531a55e6442ee58eb471fb0e3175406fdf5279  successful-exp  05:27 PM   Success
bf4fc8ecb50c4c592b898f6a22b58bcfca246b51  exp-53b3e       05:36 PM   Success
```

### CODE REVIEW

**Comment by pmrowla** [comment]
demo recording uses `exp run --run-all` to show the output logs, but `queue start` will behave the same way.

**Comment by pmrowla** [comment]
DAG tests failing due to unpinned networkx (already fixed in main, dev branch has not been rebased yet)

**Comment by dberenbaum** [comment]
> * Does not implement remove or retry for failed exps (remove support will be added in a follow up after

Will this also include remove support for successful experiments?

**Comment by pmrowla** [comment]
> > * Does not implement remove or retry for failed exps (remove support will be added in a follow up after
> 
> Will this also include remove support for successful experiments?

responded to this in the main CLI epic issue

**Pull request merged**
