### PR TITLE
push: only collect needed files when updating version_ids

### PR DESCRIPTION
**Pull request by efiop**
We only need particular files within the output directory, not all files.

### CODE REVIEW

**Comment by efiop** [comment]
Have some within-session-state problems with tests, so will introduce them separately, to unblock internal people needing this fix.

Also need to fix ui (unrelated), will look into that as well.

**Comment by indigoviolet** [comment]
Is it possible that this made `dvc push` very slow? It takes forever `Collecting <bucketname> on gs ...`

**Comment by efiop** [comment]
@indigoviolet are you using cloud versioned remotes?

**Comment by skshetry** [comment]
@efiop, this code path is triggered for non-versioned remotes too. Is that unexpected?

**Comment by indigoviolet** [comment]
@efiop No, we are not using cloud versioning currently.

**Comment by efiop** [comment]
That is only needed for cloud versioned remotes and we were skipping it, but later on. And this PR made that slower which highlighted the original problem. Created https://github.com/iterative/dvc/pull/10207

**Comment by efiop** [comment]
@indigoviolet Could you try upstream dvc and see if that helps, please? https://dvc.org/doc/install/pre-release

**Pull request merged**
