### PR TITLE
hdfs: migrate to fsspec

### LINKED ISSUE #6582: hdfs: migrate to fsspec/pyarrow.fs
To complete the fsspec migration, we need to migrate hdfs to the fsspec.

### PR DESCRIPTION
**Pull request by isidentical**
Resolves #6582, waiting https://github.com/intake/filesystem_spec/pull/754

### CODE REVIEW

**Comment by isidentical** [comment]
This is awaiting a new fsspec release

**Review by pared — COMMENTED** [review]
LGTM so far, Windows tests are failing.

**Comment by skshetry** [comment]
@isidentical, please rebase. I have pinned the dvclive to `0.3.0` for now.

**Comment by isidentical** [comment]
@mergify rebase

**Pull request merged**
