### PR TITLE
metrics: Use "metrics.json" as DEFAULT_METRICS_FILE.

### LINKED ISSUE #6168: Default metrics file
Goal: make it easier to use experiment tracking in DVC (especially `exp show`) without worrying about pipelines, data management, etc.

DVC already has a default `params.yaml` that does not need to be specified in any stage for parameters to be tracked. Having similar defaults for metrics (for example, `metrics.json`) could enable DVC to read these artifacts without needing to specify them in `dvc.yaml`.

Example:
```
$ git init
$ dvc init
$ echo '{"acc": 0.5}' > metrics.json
$ git add .
$ git commit -m "adds metrics"
$ echo '{"acc": 0.6}' > metrics.json
$ dvc exp show
┏━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━┓
┃ Experiment ┃ Created  ┃ acc   ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━┩
│ workspace  │ -        │ 0.6   │
│ main       │ 04:43 PM │ 0.5   │
│ 8968a78    │ 04:43 PM │ 0.5   │
└────────────┴──────────┴───────┘
```

This would allow for users to get started quickly with experiment tracking by writing out their metrics to the specified locations without needing any other dvc-specific configuration.

### PR DESCRIPTION
**Pull request by daavoo**
Closes #6168

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
I was thinking about how DEFAULT_PARAMS_FILE affects the `dvc.yaml` definition but I don't think it makes much sense to make `metrics` support a similar "granular" definition.


Feels overkill to implement support for:

```
metrics:
  - metrics.json:
      foo
```

And use the default file to make it equivalent to:

```
metrics:
  - foo
```

**Comment by pmrowla** [comment]
I know we just use `.json` for metrics everywhere already in our examples and tests, but I was wondering if it makes sense that we use different default formats for params and metrics. If we are actually going to define a default metrics file now, should we be using yaml for consistency across DVC instead of json?

**Comment by dberenbaum** [comment]
> I was thinking about how `DEFAULT_PARAMS_FILE` affects the `dvc.yaml` definition but I don't think it makes much sense to change `metrics` to also support a "granular" definition.

Agreed that metrics don't need granular support.

> should we be using yaml for consistency across DVC instead of json?

There's some related discussion in https://github.com/iterative/dvclive/pull/292. I'd vote to keep as is since we already have it implemented that way in dvclive.

---

@daavoo Is this still desirable given the coming changes in https://github.com/iterative/dvc/issues/8371 and https://github.com/iterative/dvclive/issues/311? My concern would be that we are adding defaults that do not match the dvclive outputs.

**Comment by daavoo** [comment]
> @daavoo Is this still desirable given the coming changes in #8371 and [iterative/dvclive#311](https://github.com/iterative/dvclive/issues/311)? My concern would be that we are adding defaults that do not match the dvclive outputs.

I was checking how hard was to do this and then combine it with #7939 in comparison to #8371

**Comment by dberenbaum** [comment]
> > @daavoo Is this still desirable given the coming changes in #8371 and [iterative/dvclive#311](https://github.com/iterative/dvclive/issues/311)? My concern would be that we are adding defaults that do not match the dvclive outputs.
> 
> I was checking how hard was to do this and then combine it with #7939 in comparison to #8371

It's more limited (for example, you can't have mutliple dvclive dirs), but I'm open to it as a first step if it's quicker. cc @skshetry

**Pull request closed without merging**
