### PR TITLE
pull/fetch/push: add stats

### LINKED ISSUE #3485: pull/fetch: show how many files were downloaded
https://github.com/iterative/dvc/pull/3401 is merged. This introduced showing changes during checkout. `pull` is a fetch + checkout, so, the output is a bit mixed. It'd be good to get statistics of what was downloaded during fetch or even better, what files were downloaded.

### PR DESCRIPTION
**Pull request by skshetry**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Closes #3485

1. 
```sh
$ dvc pull
M	bar
A	foo
1 file added, 1 file modified and 2 files fetched
```

2.
```sh
$ dvc push
2 files pushed
```

3.
```sh
$ dvc fetch
1 file fetched
```

### CODE REVIEW

**Comment by skshetry** [comment]
Running manual tests, forgot to try `checkouts`.

**Comment by pared** [comment]
@skshetry seems like you need to modify `test_data_sync` unit command tests. Now we are mocking `fetch` and `push` return value, and logger is unable to parse it.

**Comment by skshetry** [comment]
Thanks @pared, I have adjusted the tests. I have set `return_value`, now the mock should be properly set.

**Comment by efiop** [comment]
@skshetry Are you sure we don't need docs for this PR ?

**Pull request merged**
