### PR TITLE
setup: remove py2 backports

### PR DESCRIPTION
**Pull request by mroutis**

### CODE REVIEW

**Comment by shcheklein** [comment]
just a reminder - don't forget to update conda, apt (?), etc ...

**Comment by mroutis** [comment]
@shcheklein , as far as I know, both `conda` and `debian` uses the source code to build from python, no need to tweak anything specific.

**Comment by efiop** [comment]
@mroutis Both have separate list of requirements, so we do need to update them(e.g. https://github.com/conda-forge/dvc-feedstock/blob/master/recipe/meta.yaml#L29). Only configparser matters though, as mock is just a test requirement. Debian WIP package is having hard times now, as we make a lot of deps changes, so let's not bother with it for now, we will need to revisit it when we actually release it anyways. No need to send a patch for conda too, I will have to update it soon too.

**Comment by efiop** [comment]
@mroutis Tests are failing for some reason though...

**Comment by mroutis** [comment]
@efiop , I'll leave `mock` for now, since I can't tell why it is not working as intended.

**Comment by mroutis** [comment]
would you mind re-reviewing the PR, @efiop ?

**Pull request merged**
