### PR TITLE
move: awareness of cwd when moving files

### LINKED ISSUE #1636: move: When moving a nested file, the output goes to the root
version: `0.28.2`

Steps to replicate it:
```bash
dvc init --no-scm --force
mkdir directory
cd directory
echo "foo" > foo
dvc add foo
dvc move foo bar
file bar
# bar: cannot open `bar' (No such file or directory)
file ../bar
# ../bar: ASCII text
```

### PR DESCRIPTION
**Pull request by mroutis**
Fix #1636

### CODE REVIEW

**Comment by shcheklein** [comment]
@mroutis @efiop should we also add an `if e.errno == errno.EEXIST:` to the very end of the function where we have the last try/catch?

**Comment by mroutis** [comment]
@shcheklein , from the original source:

> Cannot rely on checking for EEXIST, since the operating system could give priority to other errors like EACCES or EROFS

On the first case it is inevitable, as `FileExistsError` doesn't exist in py2.

Btw. thanks for reviewing the PR :smile:

**Comment by shcheklein** [comment]
@mroutis sure! :) but, I still don't quite understand what's happening to be honest. 

First off all, what is the desired contract of the `_makedirs` when `exist_ok` is `True`. It should never throw `OSError` with `EEXIST` (analog of `FileExistsError`), right?

Then why don't we just call `_makedirs(head, True)` instead of wrapping it in the internal try/catch?

```
        try:
            _makedirs(head, exist_ok=exist_ok)
        except FileExistsError:
            pass
        except OSError as e:
            if e.errno == errno.EEXIST:
                pass
```

**Comment by mroutis** [comment]
> First off all, what is the desired contract of the `_makedirs` when `exist_ok` is `True`. It should never throw `OSError` with `EEXIST` (analog of `FileExistsError`), right?

Yes, as long as the `path` is not a file, for example:

```python
from dvc.utils.compat import makedirs

with open("hello", "w") as fobj:
    fobj.write("hello\n")

makedirs("hello", exist_ok=True)
# OSError: [Errno 17] File exists: 'hello'

makedirs("directory")
makedirs("directory", exist_ok=True)
# No error right here
```

> Then why don't we just call `_makedirs(head, True)` instead of wrapping it in the internal try/catch?

Wrapping it on a `try/except` would catch race conditions (or at least, that's my understanding of the following comment: https://github.com/python/cpython/blob/3ce3dea60646d8a5a1c952469a2eb65f937875b3/Lib/os.py#L213)

**Comment by shcheklein** [comment]
@mroutis kk, don't want to go too deep into that implementation now (though it looks like that this internal try/catch is not necessary). Two things I would change though:

1. Most likely a bug. It should be: ```except OSError as e:
            if e.errno != errno.EEXIST:
                raise```
2. Please, please, let's put a comment when we borrow the code from somewhere and let's keep initial comments in that code, it saves a lot of time.
3. (optional, for the future) I would also pull unit tests for these functions

**Comment by efiop** [comment]
@mroutis @shcheklein ivan is right about that except. So imagine some other OSError (not EEXIST) being risen. In our current implementation, we would simply ignore it, but in cPython's case it won't be caught by try/except and so it will be automatically propagated upwards. 

> 2\. Please, please, let's put a comment when we borrow the code from somewhere and let's keep initial comments in that code, it saves a lot of time.

There is a comment about where it is from, but it is a little too high https://github.com/iterative/dvc/blob/master/dvc/utils/compat.py#L18 and ideally would be closer to the _makedirs implementation.

> 3\. (optional, for the future) I would also pull unit tests for these functions

It is py2-only, so it is not worth bothering with this time, especially since we used to not have it at all :)

**Pull request merged**
