### PR TITLE
repo: add head_commit_info property for studio live experiments monorepo support

### PR DESCRIPTION
**Pull request by mattseddon**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

----

Follow up to #10283. Related to https://github.com/iterative/studio/issues/8848.

This PR adds a `head_commit_info` property to the `Repo` object. This property provides the information required to correctly display live experiments generated from monorepos in Studio. The information is sent via `dvc_studio_client.post_live_metrics` as `dvc_experiment_parent_data`.

Notes:

- This data collection doesn't fit intuitively/easily anywhere within the DVC ecosystem
- The property will be used by both `dvc` and `dvclive`
- I considered adding the collection to `dvc-studio-client` but that would involve making `dvc-studio-client` aware of `scmrepo` and/or `GitCommit`s.

Is there a better place to put this functionality?

### CODE REVIEW

**Comment by skshetry** [comment]
Could you share an example how this will be used?

**Comment by mattseddon** [comment]
> Could you share an example how this will be used?

@skshetry see https://github.com/iterative/dvclive/pull/774 & https://github.com/iterative/dvc/pull/10285

**Comment by skshetry** [comment]
@mattseddon, `Repo` has a large API surface. So, we don't usually add any API directly to it as possible.
We have split up the parts of `Repo` into smaller APIs, like `repo.scm` for example, that houses all git-related procedures and functions.

`repo.scm` has APIs that gives you all required information, as you have used in the PR already. What you have in `head_commit_info` is a very specific serialization of `GitCommit` for Studio, so I don't think it should a `Repo` property.

Either this should be handled in appropriate places, in `dvclive` and in `dvc` separately, or at best, it should be a utility function somewhere in `dvc.scm`/`dvc.utils.studio`.

I'd prefer the former, as they are independent clients and can have independent implementations, but I have nothing against the latter. 

> I considered adding the collection to dvc-studio-client but that would involve making dvc-studio-client aware of scmrepo and/or GitCommits.

In medium/long-term, I'd like to move away from `dvc-studio-client`. It tries to be independent of dvc, but it has to try to re-implement parts of dvc. 
`dvclive` already depends on `dvc` and I see no point in maintaining `dvc-studio-client` at the moment. It just creates issues like this.

**Comment by mattseddon** [comment]
I'll move everything around.

**Comment by mattseddon** [comment]
> `dvclive` already depends on `dvc` and I see no point in maintaining `dvc-studio-client` at the moment. It just creates issues like this.

@skshetry is the suggestion here to move `dvc-studio-client` into `dvc`? I can take that if that's what you want to do.

**Pull request closed without merging**
