### PR TITLE
Move fs utilities to fs.py from __init__.py

### LINKED ISSUE #2137: dvc: update file utilities
Some file utilities live in `dvc.utils.fs` while some other in `dvc.utils.__init__`. I suggest grouping them in a single place.

Also, some of them accept Path-like objects, i.e. `Path`, `PurePath`, `PathInfo`, etc and some do not. This makes people guess at the call site whether they need to wrap arguments into `fspath()`, `fspath_py35()` or none. So I propose that our file utilities will always accept that, this way we will concentrate those wrapper call in one place and remove the guessing part, at least for our own functions, calling `os.path.*()` will still need wrapping as long as we use Python 3.5-.

- [ ] move to `dvc.utils.fs` (Fixed by #3093 )
- [x] make Path-like objects aware (Fixed by #2673 #2698 #2740 #2746 #2752 #2757 #2769 #2795 #2808 #3035 #3037 )

### PR DESCRIPTION
**Pull request by algomaster99**
* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [ ] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

This pull request moves all fs utilities to `fs.py` from `__init__.py`.

Fixes #2137

### CODE REVIEW

**Comment by algomaster99** [comment]
@efiop I have initiated the shifting of filesystem utilities from `__init__.py` to `fs.py`. Tell me if there are more.

**Comment by efiop** [comment]
@algomaster99 Thank you for the PR! :pray: I think the only one that is left to move is `walk_files` and that should be it :slightly_smiling_face:

**Comment by algomaster99** [comment]
@efiop PR has been updated. Please see. Thanks!

**Comment by efiop** [comment]
Thank you @algomaster99 ! 🙏 

For the record: tests failing for unrelated reasons.

**Pull request merged**
