### PR TITLE
exp: Drop `init`.

### LINKED ISSUE #9267: Deprecate or change `dvc exp init` (it's outdated relative to the current recommended way to onboard to experiments)

### PR DESCRIPTION
**Pull request by daavoo**
Closes #9267

- Docs: https://github.com/iterative/dvc.org/pull/4415

### CODE REVIEW

**Comment by skshetry** [comment]
> @daavoo WDYT of merging these into a 3.0 branch? It would clean up our open PRs and make it easier to manage 3.0 deprecations IMO.

We have discussed this before, no? The consensus was to not maintain a 3.0 branch, but create a 2.0 branch instead and just merge this to main, and work on it actively when we can.

**Comment by dberenbaum** [comment]
Yup, we discussed in refinement and @daavoo reminded me we decided against a 3.0 branch. No strong opinion, sorry for the noise.

**Comment by dberenbaum** [comment]
Pushed a 2.x branch. Can we merge this into main then? Will the idea be to merge things into 2.x if they are non-breaking and then merge that into main as needed? Feels like we need to primarily merge into 2.x since it's easier to merge 2.x->3.x (breaking changes stay downstream) than 3.x->2.x (need to separate breaking and non-breaking changes to merge).

**Comment by skshetry** [comment]
> Pushed a 2.x branch. Can we merge this into main then? Will the idea be to merge things into 2.x if they are non-breaking and then merge that into main as needed? Feels like we need to primarily merge into 2.x since it's easier to merge 2.x->3.x (breaking changes stay downstream) than 3.x->2.x (need to separate breaking and non-breaking changes to merge).

Unless the team starts actively working on 3.x, I don't think we should merge this. We'd need to backport stuffs into 2.x, which creates a lot of work. But something to discuss in the team meeting.

**Comment by skshetry** [comment]
@daavoo, also make sure to remove [`./dvc/ui/prompt.py`](https://github.com/iterative/dvc/blob/e69deaa1323cdb4f9c180cd48d54edd5d1d19e27/dvc/ui/prompt.py). I don't think it's used elsewhere.

**Pull request merged**
