### PR TITLE
Add integration tests for Azure Remote

### PR DESCRIPTION
**Pull request by c-w**
This is a follow-up to https://github.com/iterative/dvc/pull/868.

The main change of this pull request is to set up the Azure Storage emulator [Azurite](https://github.com/Azure/Azurite) on the Travis CI machine via Docker and runs the Azure integration tests against the emulator (fcd0e34). An example of a successful build with this configuration on Travis can be found [here](https://travis-ci.org/CatalystCode/dvc/builds/402397620).

The pull request also contains a number of related functional fixes:
- Make the Azure remote compatible with Python 2 (8a32292).
- Switch the exists implementation of the Azure remote to the same list-then-check logic as S3 (a438f77).
- Make the Azure environment variables consistent between test and prod (581132b).
- Add the Azure remote to an additional test suite (fcbc6d1).

Additionally, the pull request also includes some related refactoring:
- Fix lint warnings in the data cloud tests file (1b1ca68).
- Replace `os.system` and make should-run cloud test checks more robust (9724bd9).
- Mark non-executed cloud tests explicitly as skipped (97dfc88).
- Increase test runner verbosity (7897dd8).

### CODE REVIEW

**Comment by efiop** [comment]
Hi @c-w !

Thank you for the follow up! Looks great! I see that our appveyor test is failing on Azure test, is there any chance you could also setup azurite for it?

Thanks,
Ruslan

**Comment by c-w** [comment]
Working on it. Might be pushing a bunch of odd updates to the PR to re-trigger the build while I figure this out. Will ping you when this is ready to be reviewed again.

**Comment by c-w** [comment]
Hi @efiop. Happy to report that the AppVeyor build now runs the Azure remote integration tests via Azurite.

At first, I tried to run Azurite in Docker just like we do on Travis CI (via `image: Visual Studio 2017`), but by default the Docker install is set up to run Windows containers so the Azurite container wouldn't run. Switching to Linux containers (via `docker-switch-linux`) failed when spinning up the MobyLinuxVM, likely because the AppVeyor worker ran out of memory. I then tried to install and auto-start Azurite via Nuget (via `Install-Package Azurite`) but this didn't actually launch the process. Installing Node and the Azurite NPM package onto the AppVeyor worker and launching/stopping the Azurite process via Powershell worked fine, so that's the solution implemented in 8f36587.

**Comment by efiop** [comment]
Hi @c-w !

Thank so much for the amazing work! Merged! I will release 0.10.3 with Azure support until tomorrow.

**Comment by c-w** [comment]
Thanks for the merge! Looking forward to the package being released :)

**Pull request merged**
