### PR TITLE
build_deb: Debian directory appended. Issue #2800

### PR DESCRIPTION
**Pull request by Abrosimov-a-a**
Debian packaging system. #2800

* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [x] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by efiop** [comment]
Sorry, I'm a bit confused by this one, why is this one needed after https://github.com/iterative/dvc/pull/2923 ? Also, should it be a part of dvc-s3-repo?

**Comment by Abrosimov-a-a** [comment]
@efiop Yes, it's needed for building DVC package. No, it's not a part of dvc-s3-repo. It's part of code native Debian package (like setup.py for Python).

**Comment by efiop** [comment]
@Abrosimov-a-a Hm, I'm still confused then. Would really appreciate if you could help make https://github.com/iterative/dvc-s3-repo build those packages on travis builds.

**Comment by efiop** [comment]
@Abrosimov-a-a Though, just helping understand is good too :) So the scripts that are already in `dvc-s3-repo`, do they download the tar ball for dvc and then build from it?

**Comment by Abrosimov-a-a** [comment]
1. This PR content information about package: `debian/`. Name, description, dependencies, requirements... It's a part of code, like `setup.py`. Keep up to date: dependencies in `control` and `changelog`. It's all you need.
2. Scripts in `dvc-s3-repo` make environment in Docker, clonning all the dependencies via GIT, build the packages in automatic mode and installing them. After that clone DVC repository, and build packages using instructions from `debian/`. Versions of DVC and dependencies can be set in `build_deb/src/build.sh`
3. Scripts can be modify for using Travis and tar archves instead GIT.

**Comment by Abrosimov-a-a** [comment]
I can make an RPM building system. Problem is more dependencies for building, more time to prepare.

**Comment by efiop** [comment]
@Abrosimov-a-a Git works too 🙂  Maybe it would make sense to keep these files in dvc-s3-repo and just copy them into the cloned project when we are building? The changelog is unlikely to get updated here, as we push a lot of releases and writing them manually is too much work. We do have a bot that is generating them for us on github releases, so we would have to look into auto-generating them for deb package too at some point. 🙂

**Comment by Abrosimov-a-a** [comment]
> Maybe it would make sense to keep these files in dvc-s3-repo and just copy them into the cloned project when we are building?

Usually don't. What if someone wants to build their package?

> The changelog is unlikely to get updated here, as we push a lot of releases and writing them manually is too much work.

While you are not in Debian, you can simply change the version number in a single message. :)

**Comment by efiop** [comment]
@Abrosimov-a-a Ok, makes sense 🙂Thank you!

**Pull request merged**
