### PR TITLE
commit: support virtual operation

### PR DESCRIPTION
**Pull request by skshetry**
See https://github.com/iterative/dvc/pull/9389#issuecomment-1543266064.

### CODE REVIEW

**Comment by skshetry** [comment]
I'm not really convinced that `dvc commit` should only commit if it matches with the hashes by default. It feels quite unintuitive to me and feels like it should change.

Also, as I have said, it's not good that we have different behaviour for `add` and `commit`.

`dvc add` is a two-step operation: first where we build the object/hashes, and second where we `commit` them.

These two following scenarios now have different results:
```console
dvc add data --no-commit
dvc add data/granular/file
```

```console
dvc add data --no-commit
dvc commit data/granular/file
```

**Comment by dberenbaum** [comment]
@skshetry I agree with your interpretation, but it doesn't really answer what kind of use case you need granular virtual `commit` instead of `add`. Maybe if you made some manual changes to a stage output and want to force commit, which seems like a valid but pretty niche scenario that I wouldn't see as a priority. So I'd be fine with or without this PR since I don't see it as a major need.

@efiop If you think all this belongs in `dvc add`, would you also expect `add` to cover stages as targets?

**Comment by skshetry** [comment]
> I agree with your interpretation, but it doesn't really answer what kind of use case you need granular virtual commit instead of add.

Yeah, I don't think there is a compelling argument, as we already have support for in `dvc add`. And we could extend `dvc add` in the future to support stage outputs.

But to me, it's about parity, and the `commit`'s default behaviour being unintuitive which is the reason why we are not able to support virtual operation. So I am looking at from that ideal state, where I see no reason not to have virtual operation. I don't intend to merge this PR, but I did not want to lose my change, and wanted to have some discussions regarding the commit's behaviour. We are gearing for 3.0 release, it might be a good time to reconsider commit. :)

> Maybe if you made some manual changes to a stage output and want to force commit, which seems like a valid but pretty niche scenario that I wouldn't see as a priority. 

If you go by docs, I would not say this is a niche scenario. Although this scenario is already support. Stage outputs are unlikely to require virtual operation. Granular updates are supported already.

> If you think all this belongs in dvc add, would you also expect add to cover stages as targets?

It does not have to, it could support target to stage output.

**Comment by dberenbaum** [comment]
> It does not have to, it could support target to stage output.

I was thinking the goal in that case would be to deprecate `dvc commit`, but I would still want a way to commit all changes to a stage, so it seems like we would need to keep both commands.

---

Overall, as I said, I'm fine with any outcome for this PR: merging, waiting for 3.0 or closing.

**Comment by efiop** [comment]
> @efiop If you think all this belongs in dvc add, would you also expect add to cover stages as targets?

Yep, I would.

Seems like there is no strong need to do anything with `commit`, so maybe we could avoid touching it for now.

**Comment by skshetry** [comment]
I don't think it makes sense. `dvc add` is a data-centric command, what does `add stage` mean?

We do have a good scenario for `commit` which means sync cache/dvcfiles with the current workspace. 

Also, what's the equivalent of `dvc commit` (without any argument)?

**Comment by skshetry** [comment]
I'm closing this temporarily, let's think about this for 3.0.

**Pull request closed without merging**
