### PR TITLE
dvc: batch push/pull/fetch/status

### LINKED ISSUE #2308: Pull with masked targets is slow
`dvc pull` with specifying targets by shell-expanded glob mask (e.g. `dvc pull */*.dvc`) works significantly slower then global `dvc pull`. This is especially hurtful when pulling large number of small files. At the same time, passing glob mask to dvc via `dvc pull '*/*.dvc'` does not seem to be supported.

Should this be optimized?

As mentioned in chat, workaround is `dvc pull -R dir`.

DVC version: 0.50.1
Platform: Ubuntu 18.04, installation via pip

### PR DESCRIPTION
**Pull request by Suor**
This will speed up cache collection and then run single cloud op for all
collected cache.

Fixes #2308.

### CODE REVIEW

**Comment by Suor** [comment]
Tests fail because of homebrew.

**Comment by efiop** [comment]
Btw, sorry for the delay, I've missed this PR.

**Comment by Suor** [comment]
Pushing 1k 1MB files to local ssh:
```
master
    real    2m49.723s
    user    2m27.693s
    sys 0m13.085s

mass-ops
    real    1m36.193s
    user    1m33.640s
    sys 0m12.927s
```
And better UI.

**Comment by Suor** [comment]
There is also a noticeable - several seconds - delay at the start, this is due to #2344 I guess.

**Comment by efiop** [comment]
@Suor Thanks! Looks amazing!

For the record, travis is failing due to homebrew again(now in another place), all other tests are passing fine. Will send another patch for travis ASAP.

**Pull request merged**
