### PR TITLE
packages: build binary pkgs with Python 3.9

### PR DESCRIPTION
**Pull request by skshetry**

### CODE REVIEW

**Comment by skshetry** [comment]
Package builds running at https://github.com/iterative/dvc/actions/runs/1489796368.

**Comment by efiop** [comment]
@skshetry Did 3.9.8 get a rerelease?

**Comment by skshetry** [comment]
> @skshetry Did 3.9.8 get a rerelease? #6975

yeah, there is a 3.9.9 release: https://www.python.org/downloads/release/python-399.

**Comment by skshetry** [comment]
Looks like setup-python is still using `3.9.8`.

**Comment by pared** [comment]
So we probably need to wait for them now?

**Comment by skshetry** [comment]
> So we probably need to wait for them now?

From https://github.com/actions/virtual-environments:

> Regular Weekly Rhythm can be followed by watching Releases. Pre-release is created when deployment is started. As soon as deployment is finished, it is converted to release. You can also track upcoming changes using the awaiting-deployment label.

I already see pre-releases with `Python 3.9.9`, so we need to wait till they turn to `release`.

**Review by pared — APPROVED** [review]
Seems like the new 3.9 is on now.

**Pull request merged**
