### PR TITLE
version: show when the release version is dirty

### LINKED ISSUE #1866: Logging: stderr not being catched when using subprocess
DVC version: 0.35.6+d766d3, 
Platform: Linux
Installation: pip -e .

It prints to stdout this kind of message with any command: `fatal: no tag exactly matches 'd766d32d6e82c6952571eeb7ef76d48e8eec5f98'`

### PR DESCRIPTION
**Pull request by mroutis**
Fix #1866

### CODE REVIEW

**Comment by efiop** [comment]
@mroutis Are you trying to solve https://github.com/iterative/dvc/issues/1866 ?

**Comment by mroutis** [comment]
ohh, no, @efiop , it was totally unrelated, I was running a development version but noticed no change on `dvc --version`.

**Comment by mroutis** [comment]
@efiop , the problem described on the issue is because running the `git describe --tags --exact-match` outputs to stderr. We should capture stderr. I'll send a commit with this in mind

**Comment by mroutis** [comment]
@efiop , ready, please give it a check ^

**Pull request merged**
