### PR TITLE
imp_url: support dvcx datasets

### PR DESCRIPTION
**Pull request by skshetry**
```
dvc import-url ds://dogs@v5
```

[asciicast](https://asciinema.org/a/U7yPPHOfIWrnOa7gQD9Ro1BW4)

### Setup

- Get a studio token and save it to `.dql/config`. The `.dql` directory should be at the same location where you'll be using dvc.
  ```ini
  [core]
  default-remote = "dql-team"

  [remote]

  [remote.dql-team]
  type = "http"
  url = "https://studio.iterative.ai/api/dvcx"
  username = "iterative"
  token = "isat_ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  ```

- Make sure to setup AWS credentials properly, especially the `iterative-mfa` and set `AWS_PROFILE` envvar to it.

### CODE REVIEW

**Comment by dberenbaum** [comment]
Thanks for opening @skshetry! I think it helps make it more concrete. I had a bit of a different idea of how it would work. I would expect `dvc import-url` to do the dql pull operation and use the remote/saas dql versions as dependencies.

**Comment by skshetry** [comment]
Could. you elaborate more? Maybe I am missing something, but at this time, I don't see a difference between the CLI datasets and the SaaS.

In the future, we might be able to track the origin of the index, but that's on dvcx side than dvc to implement. UUID might also help in tracking whether it exists in Studio or not.

**Comment by dberenbaum** [comment]
I missed [this comment](https://github.com/iterative/dvc/pull/10123#discussion_r1413824960) explaining that you can't get the available version from SaaS without pulling first. It seems like a major limitation to me for the intended use case:

> Let's focus on the simple SaaS use case when we just pull a dataset.

_Originally posted by @dmpetrov in https://github.com/iterative/dql/issues/987#issuecomment-1837243582_

**Comment by skshetry** [comment]
> use the remote/saas dql versions as dependencies


Just to be clear, with above, did you mean about being able to pull dataset without doing `dql pull` manually? 

If yes, then yeah. That'd be fixed by that. Until then, we have "just imagine" that it does. 😅

**Comment by skshetry** [comment]
Not sure if you meant anything more by that statement.

**Comment by dberenbaum** [comment]
> Just to be clear, with above, did you mean about being able to pull dataset without doing `dql pull` manually?

Yes. Is there ongoing work or an issue at least to support this?

**Comment by skshetry** [comment]
> > Just to be clear, with above, did you mean about being able to pull dataset without doing `dql pull` manually?
> 
> Yes. Is there ongoing work or an issue at least to support this?

There is an open issue: https://github.com/iterative/dql/issues/989. But I haven't asked it to be prioritized, as I wanted to get feedback here first.

Also, it did not seem very important here to me for the first phase, as `dvc import-url` works without any issues for SaaS. It's only `dvc update` that needs to have `dql pull` first for the index.

**Comment by skshetry** [comment]
@dberenbaum, do you have any other concerns regarding the approach? Is it sound?

I am thinking of merging this by tomorrow (will discuss with Dmitry). I'll discuss the iterative/dql#989 with him. 
Do you see that blocking the PR?

**Comment by skshetry** [comment]
Discussed with @dmpetrov about this. He does not want dvc to compute md5 hashes for pipeline checksums, and wants that to be handled by dql itself, as in ask `dql` for workspace status.
His point was that there is: database, support for returning different formats of data like json pairs/coco and the actual _files_ in "dvcx datasets", that only dql has a good knowledge about.

This would require us to decouple checksums that we use for pipelines and md5 hash that we use for data management.

There is also an open question of how `dvc pull`/`dvc checkout`, etc would work. And we also need to support non-instantiated/non-materialized datasets as checkout/pull is not always possible and training might happen on streaming datasets. So we also want to have a support for a dependency in your stage for pipelines.

This would be a matter of figuring out how the API will work, and how we'll translation works.

```console
dvc stage add -d ds://dogs@v1 ...
```

(For this, we'll need to figure out how the hypothetical `get_dataset()` api in dvc will work and how we'll pass the data inside - likely with envvars).

I think we should do a single integration (or start with just one). Given the challenges with former, maybe it's better to start with the latter one.

**Comment by skshetry** [comment]
Closing this PR as we are not implementing this as a part of DVCx integrations. See #10164.

If directions change, we can reopen this.

**Pull request closed without merging**
