### PR TITLE
Adding remote Argument

### PR DESCRIPTION
**Pull request by PietrassykFP**
* [ X] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

This PR fixes issues: https://github.com/iterative/dvc/issues/7341

### CODE REVIEW

**Comment by dtrifiro** [comment]
Hi @PietrassykFP thanks a lot for the PR!

Would you be interested in taking a shot at adding a test for this PR?

**Comment by PietrassykFP** [comment]
@dtrifiro I have absolutely no experience in testing your framework and writing this test would take me ages. But I would really love to have this problem solved. Because dvc is awesome, but we cant use it due to this bug.

**Comment by dtrifiro** [comment]
No, worries, we'll have a look at it!

**Comment by efiop** [comment]
Hey @PietrassykFP The issue should be fixed by https://github.com/iterative/dvc/pull/7353 , could you please give upstream dvc a try?

**Comment by efiop** [comment]
Thanks to @skshetry for pointing out that we still have a related issue in https://github.com/iterative/dvc/pull/7363 🙏  Looking into it.

**Comment by efiop** [comment]
@PietrassykFP Thanks for the feedback! We'll be looking further into it in https://github.com/iterative/dvc/pull/7363

**Pull request closed without merging**
