### PR TITLE
ui: don't show working tree if it is clean

### LINKED ISSUE #2386: brancher: yields working tree on clean state
On the description of `brancher` it reads the following:
```
    Yields:
        str: the display name for the currently selected tree, it could be:
            - a git revision identifier
            - empty string it there is no branches to iterate over
            - "Working Tree" if there are uncommited changes in the SCM repo
```

The relevant part is the last one, it should `yield` the "working tree" only if the repository is dirty.
It would be fixed with the following (under `brancher.py`):

```python
    if repo.scm.is_dirty():
        yield "working tree"
```

I think this make sense, because for `dvc metrics show` it is annoying to see the "working tree" when there's no difference from the current branch.

### PR DESCRIPTION
**Pull request by Suor**
Fixes #2386

### CODE REVIEW

**Comment by Suor** [comment]
Actually this is still wrong. Working tree might be clean but some .gitignored files changed.

**Comment by Suor** [comment]
So we can't know whether working tree is clean unless we check both `git status` and `dvc status`, which might make `dvc metrics show <some-metric>` considerably slower. The solution might be:
- perform the collection for both working tree and everything, then don't show if it's the same as current branch/head (will need to dup this in `dvc status`/`dvc metrics show`)
- let brancher know what we are looking for to limit `dvc status` to specific file(s)
- pass `dirty=...` to brancher by some code, which knows what we are looking for

All of those don't look too nice. Ideas?

**Comment by efiop** [comment]
> So we can't know whether working tree is clean unless we check both git status and dvc status

@Suor Not sure I follow. If git is clean, then it means that there are no new files (untracked too, right?) in the repo. I don't quite understand why `dvc status` would matter there?

**Comment by Suor** [comment]
If metric is handled by dvc then it is in `.gitignore`, git will be clean, but metric might be changed, need to check that it corresponds to checksum.

**Comment by efiop** [comment]
@Suor Got it. Good one. And with `dvc status`, it would only need to be checked for the current branch once, right? Seems like it is not that bad, but it indeed might take some time for big directories. Limiting it to specific files (e.g. metrics) would only complicate it, and I'm not sure if it is worth it. Maybe the smartest thing here is to not overcomplicate this and leave it as is. Showing `working tree` is not that bad after all.

**Comment by Suor** [comment]
@efiop I am considering filtering output for `metrics show`, people usually have issue with that.

**Comment by efiop** [comment]
@Suor Feels weird to make brancher know about specific files that we want to check. Maybe 

> perform the collection for both working tree and everything, then don't show if it's the same as current branch/head (will need to dup this in dvc status/dvc metrics show)

Would be better? Btw, not sure why we need it for `dvc status`, as it doesn't care about branches really.

**Comment by Suor** [comment]
@efiop I thought `dvc status --all-branches` will show status for all branches or whatever. Looked at the code and realized those flags are simply ignored.

**Comment by Suor** [comment]
Closing in favor of #3025.

**Pull request closed without merging**
