### PR TITLE
add/run/import-url: don't use -f as --file

### PR DESCRIPTION
**Pull request by efiop**
If anything, `-f` is closer to `--force` than to `--file`. So let's set
this straight.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).

https://github.com/iterative/dvc.org/issues/1255

* [x] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hi. I see a checkbox was added for this in iterative/dvc.org/issues/1255, thanks. But that's not really a catch all epic for every change from now on 😋

I may be wrong but this doesn't sound like a 1.0-specific change to me, can we open a separate issue or PR instead, please?

**Comment by efiop** [comment]
@jorgeorpinel it is used all over the docs and I have no idea what to change there because of all of the 1.0 PRs hanging that affect all of the docs that I need to change. So I've added it to the epic.

**Comment by jorgeorpinel** [comment]
Please open an issue and link to the core PR when submitting a PR is not possible. That's totally fine. Done: iterative/dvc.org/issues/1426

**Comment by efiop** [comment]
@jorgeorpinel It was added to the epic ` get rid of -f in add/run/import(-url) per iterative/dvc#4004 and iterative/dvc#4011`, you can see it in the history of changes, but you've deleted it in the past two days.

**Comment by jorgeorpinel** [comment]
I extracted it into iterative/dvc.org#1426 like I just mentioned. Thanks

**Pull request merged**
