### PR TITLE
proc: remove dvc.proc

### PR DESCRIPTION
**Pull request by pmrowla**
`dvc.proc` is no longer used (it's been replaced by `dvc_task.proc` in the experiments queue). The original `proc` implementation was left in DVC when we split `dvc-task` since there was some potential dvc-machine/ssh executor related use cases that may have differed from what `dvc-task` was doing.

But at this point the DVC version is longer needed, and we can always re-introduce it if/when we get back to dvc-machine.

### CODE REVIEW

**Comment by skshetry** [comment]
@pmrowla, what about tpi? Can we drop it? Just got into https://github.com/iterative/tpi/issues/22 with tpi.

**Comment by pmrowla** [comment]
I'd be fine with removing tpi and dvc.machine stuff from DVC. Maintenance for `iterative/tpi` was handled by the CML team before, but I'm not sure if there's any actual need for us to keep it around at this point

cc @dberenbaum

**Comment by dberenbaum** [comment]
Feel free to drop tpi/machine stuff.

**Comment by dberenbaum** [comment]
@dacbd Is https://github.com/iterative/tpi still an actively maintained project?

**Comment by dacbd** [comment]
@dberenbaum no

**Pull request merged**
