### PR TITLE
Remove outdated SSH default jobs.

### PR DESCRIPTION
**Pull request by daavoo**
* [X] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [X] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

`dvc.org` P.R. https://github.com/iterative/dvc.org/pull/3255

### CODE REVIEW

**Comment by mistermult** [comment]
Obviously, you know what you are doing and I am probably wrong. 

But if this is removed and the files are pushed/pulled with "4 * cpu_count(). " instead of 4 jobs. This might not work with many SSH/SFTP endpoints. Even lower-tier PCs/laptop have 4 cores and 16 jobs are already too much for some endpoints. Running this on are better laptop (16 cores, 64 jobs) will be too much, let alone on a server with more cores. See bugs in #7319, #6856.

**Comment by dtrifiro** [comment]
Hey @mistermult, thanks! You are right, but this PR only changes documentation

**Review by dtrifiro — APPROVED** [review]
We'll have to spend some time reviewing defaults. For now users experiencing issues will have to set up defaults using the `--jobs/-j` flag

**Comment by dtrifiro** [comment]
Hey @jorgeorpinel default is 4 x CPUs like all other remotes

**Pull request merged**
