### PR TITLE
Feature/http ssl verify configuration

### PR DESCRIPTION
**Pull request by MetalBlueberry**
I need to disable ssl verification in some cases. This feature allows to put this into dvc configuration.

Thank you!

### CODE REVIEW

**Comment by MetalBlueberry** [comment]
I do not understand why is not building on 12853.2 3.7 on Windows. Looks like it was interrupted for some reason.

how should I proceed?

**Review by efiop — APPROVED** [review]
Looks great! Thanks! :pray: 

Could you please add it to HTTP section in https://dvc.org/doc/command-reference/remote/modify too? There is an edit button on the right.

Btw, are you present on our discord? If you are not, check out https://dvc.org/chat , we have a #dev-talk channel there specifically for dev-related things. Also, if you wish, let us know your discord nickname, so we could add you to the contributors group :slightly_smiling_face: Thank you so much for contributing! :pray:

**Comment by MetalBlueberry** [comment]
Documented!

https://github.com/iterative/dvc.org/pull/1767

**Review by efiop — APPROVED** [review]
Thank you! :pray:

**Comment by efiop** [comment]
For the record: We will be releasing 1.7.0 later today.

**Comment by jorgeorpinel** [comment]
> I do not understand why is not building on 12853.2 3.7 on Windows. Looks like it was interrupted for some reason.

Hi @MetalBlueberry , is this still happening to you? Does `pip install` crash for you too (that started happening to me recently)? Can you share the error if so? Thanks

**Comment by MetalBlueberry** [comment]
> > I do not understand why is not building on 12853.2 3.7 on Windows. Looks like it was interrupted for some reason.
> 
> Hi @MetalBlueberry , is this still happening to you? Does `pip install` crash for you too (that started happening to me recently)? Can you share the error if so? Thanks

Hi @jorgeorpinel , I just saw it in the Github pipeline. I'm a linux user so I cannot guide you in how to fix this error. You can always switch to linux `¯\_(ツ)_/¯ `

**Pull request merged**
