### PR TITLE
testing: add initial basic cloud versioning tests

### PR DESCRIPTION
**Pull request by pmrowla**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

- adds the required dvc.testing fixtures and basic push/pull tests for version_aware and worktree remotes

Related: https://github.com/iterative/dvc/issues/8850

### CODE REVIEW

**Comment by pmrowla** [comment]
Merging this for now since lack of any tests at all is blocking some things, and since the dvc-gs/dvc-s3 CI can't run without having some minimum fixture+test configuration in dvc@main. Any required changes can be done in follow up PRs

**Comment by skshetry** [comment]
I would suggest also running those tests in dvc, either via s3 fixtures or some custom magical fixtures.

**Comment by daavoo** [comment]
> I would suggest also running those tests in dvc, either via s3 fixtures or some custom magical fixtures.

Coming full circle from `dvc-{x}` plugin repos?

**Comment by skshetry** [comment]
yeah, because a) this is in active development, and b) feedback time is very long for plugins.

**Comment by pmrowla** [comment]
> @pmrowla Are you planning on expanding the tests yourself in this sprint?

Yes

**Pull request merged**
