### PR TITLE
dvc: use ' to mark dynamic command output, et al.

### PR DESCRIPTION
**Pull request by jorgeorpinel**
> Follow-up of #2644 and #2644

~~@efiop it seems to me we still have dynamic output without `'` around it, am I right or have I not completely understood the criteria you use yet? Thanks~~

UPDATE: The criteria I have kind of deduced at this point is to only wrap with `'` dynamic output (logger.info/warning mainly) in larger messages, not when the entire (or almost) string or line is dynamic, when it's the last part of the string/line/sentence? after `:` (e.g. like in `dvc version`), or when it wouldn't make sense for some other reason (like in involved formatted strings). Also noting that these dynamic parts of the output typically come from variable user input (e.g. file names), not necessarily predefined variables (e.g. remote types).

---

* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [ ] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [ ] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
The changes so far are just a sample of the first instances I found/fixed.

Note to self: using grep regex `/["]{1}.*([^']\{)/`

**Comment by efiop** [comment]
@jorgeorpinel Looks good! Please install our hooks and fix the tests that depend on the messages that you've changed.

**Comment by jorgeorpinel** [comment]
Ah yeah sorry I should've checked that. I'll fix them, finish wrapping dynamic output with `'`, and re-request your reviews. Thanks!

**Comment by jorgeorpinel** [comment]
Interesting @efiop @shcheklein so Restyled can't always make a PR into the original PR branch. Have you found this problematic Ruslan? Seems a bit confusing:

> Since the original Pull Request was opened as a fork in a contributor's
> repository, we are unable to create a Pull Request branching from it with only
> the style fixes.

From https://github.com/iterative/dvc/pull/2987

**Comment by jorgeorpinel** [comment]
OK guys I fixed the formatting (and fixed the pre-hook) and continued down with this down to all commands, but still have many places in the rest of the code to double check. Probably won't find many more instances but maybe you want to review my latest changes so each review is small? Note that this is still WIP please, please don't merge it yet.

**Comment by jorgeorpinel** [comment]
OK well I'm done here now actually 😬 Pending your reviews, of course.

**Comment by efiop** [comment]
Thank you @jorgeorpinel ! 🙏

**Pull request merged**
