### PR TITLE
bump dvc-data to 0.0.3

### PR DESCRIPTION
**Pull request by dtrifiro**
fix imports for `dvc-data==0.0.3` and `dvc-objects==0.0.3`

~~**NOTE:** this will have to wait for `dvc-objects==0.0.3` to be released and for iterative/dvc-data/pull/39 to be merged~~

### CODE REVIEW

**Comment by skshetry** [comment]
`dvc-data==0.0.3` is released. Please rebase/drop last PR.

**Review by skshetry — APPROVED** [review]

**Comment by efiop** [comment]
@skshetry There are some changes in dvc-data that will degrade the perfomance (there was a bug in raw dir PR). I'll revert for now, and will update later.

**Comment by skshetry** [comment]
Wouldn't it be easier to release `dvc-data` and update it here? We can slap a https://github.com/iterative/dvc/labels/release-blocker label for now.

**Comment by efiop** [comment]
@skshetry Yes, but I'm worried that we might need some quickish releases for vscode this week. Working on dvc-data to right now to see if we can mitigate that perf issue before upgrading.

**Pull request merged**
