### PR TITLE
stage.save: Set `merge_versioned` default to `True`.

### LINKED ISSUE #8828: cloud versioning: Using `dvc commit` to track updates doesn't work as expected
## Setup

I am ttracking a dictionary with cloud versioning enabled:

```bash
$ dvc remote modify myremote version_aware true
$ dvc remote modify myremote worktree true
$ mkdir data
$ echo foo > data/foo
$ echo bar > data/bar
$ dvc add data
$ dvc push
$ cat data.dvc
outs:                                                                                                             
- md5: 168fd6761b9c3f2c081085b51fd7bf15.dir
  size: 8
  nfiles: 2
  path: data
  files:
  - size: 4
    etag: 08deb086f8d8ccfc021001
    md5: c157a79031e1c40f85931829bc5fc552
    relpath: bar
  - size: 4
    etag: 08a48b8df8d8ccfc021001
    md5: d3b07384d113edec49eaa6238ad5ff00
    relpath: foo
```

And performing an update:

## Working as expected with `dvc add`

If I run `dvc add data`, it works as expected: The .dvc file preserves "cloud-versioning" format and `dvc push` only uploads and creates a new version for the modified file:

```console
$ echo bar2 > data
$ dvc add data
$ cat data.dvc
outs:
- md5: 43f06a6517d71d0267bed23cfb1a53fb.dir
  size: 9
  nfiles: 2
  path: data
  files:
  - size: 5
    md5: 042967ff088f7f436015fbebdcad1f28
    relpath: bar
  - size: 4
    etag: 08a48b8df8d8ccfc021001
    md5: d3b07384d113edec49eaa6238ad5ff00
    relpath: foo
$ dvc push
1 file pushed                                                                                                     
$ cat data.dvc
outs:
- md5: 43f06a6517d71d0267bed23cfb1a53fb.dir
  size: 9
  nfiles: 2
  path: data
  files:
  - size: 5
    md5: 042967ff088f7f436015fbebdcad1f28
    relpath: bar
    etag: 08eca3ebfddaccfc021001
  - size: 4
    etag: 08f0f286fcdaccfc021001
    md5: d3b07384d113edec49eaa6238ad5ff00
    relpath: foo
```

## Unexpected behavior with `dvc commit`

However, If I instead run `dvc commit` to track the updates, first the `.dvc` file loses the "cloud versioning" format and then all files are uploaded and redundant versions are created on the remote:

```console
$ bar3 > data/bar
$ dvc commit
outputs ['data'] of stage: 'data.dvc' changed. Are you sure you want to commit it? [y/n] y 
$ cat data.dvc 
outs:                                                                                                             
- md5: a41477be72fa9617d877592a0b22542a.dir                                                                       
  size: 9
  nfiles: 2
  path: data
$ dvc push
2 files pushed 
$ cat data.dvc
outs:                                                                                                             
- md5: a41477be72fa9617d877592a0b22542a.dir
  size: 9
  nfiles: 2
  path: data
  files:
  - size: 5
    etag: 0898e6edffdaccfc021001
    md5: f19345bd4a711b82a13e55c61cad54e3
    relpath: bar
  - size: 4
    etag: 08bfe9e5ffdaccfc021001
    md5: d3b07384d113edec49eaa6238ad5ff00
    relpath: foo
```

### PR DESCRIPTION
**Pull request by daavoo**
Closes #8828

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
We are not testing cloud versioning on DVC side at all?

**Review by daavoo — COMMENTED** [review]
If it's ok with having this always `True` we might as well just drop the option.
If it's not ok, we have to pass the flag in `commit` and `move` to make them work with cloud versioning stages

**Comment by pmrowla** [comment]
@daavoo It's safe but it makes save slower since it forces us to reload the existing .dvc/dvc.lock file each time. It'd be better to explicitly pass the flag in commit and move IMO

**Comment by daavoo** [comment]
> @daavoo It's safe but it makes save slower since it forces us to reload/reparse the existing .dvc/dvc.lock file each time. It'd be better to explicitly pass the flag in commit and move IMO

It looks like those are all the places where `stage.save` is actually used so it would be the same as defaulting to `True` or not having the flag

**Comment by pmrowla** [comment]
We can probably just remove the flag then. This issue is more a side effect of our current `add/commit/move` behavior, where we always create a new stage from scratch, and then load the previous version if it exists later and try to merge the two, (as opposed to loading the stage if it exists first and then modifying it)

**Pull request closed without merging**
