### PR TITLE
Fix for #4773 support for @ instead of HEAD

### PR DESCRIPTION
**Pull request by dineshkumarsarangapani**
* [ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by skshetry** [comment]
@dineshkumarsarangapani, what do you think of @efiop's comment on https://github.com/iterative/dvc/issues/4773#issuecomment-714770153:
> Another (much better) option is to fix it on gitpython's side https://github.com/gitpython-developers/GitPython/blob/master/git/repo/fun.py#L325 . Likely just need to add this special case to the logic. And we could also add that special case to our codebase while we are waiting for gitpython's release with the fix.

**Comment by dineshkumarsarangapani** [comment]
> https://github.com/gitpython-developers/GitPython/blob/master/git/repo/fun.py#L325

@skshetry I am not sure. If we are waiting for GitPython's fix then fine, we can close this PR.

**Comment by skshetry** [comment]
@dineshkumarsarangapani, we don't have any issues with the fix. As you have looked into it, I was just trying to understand where does it fit: upstream or here?

**Comment by dineshkumarsarangapani** [comment]
> @dineshkumarsarangapani, we don't have any issues with the fix. As you have looked into it, I was just trying to understand where does it fit: upstream or here?

@skshetry I am new to this repo. I will leave it to the maintainers 👍

**Comment by dineshkumarsarangapani** [comment]
Team, is there any direction or help for me in this pull request?

**Comment by pmrowla** [comment]
@dineshkumarsarangapani The test issues are unrelated to your fix, so you don't need to worry about that.

On whether this fix belongs in DVC or upstream in gitpython, we have an internal team meeting later today and will discuss it then, someone will get back to you after that regarding where to go from here

**Comment by pmrowla** [comment]
@dineshkumarsarangapani after discussion with the rest of the team, we feel that this fix really belongs in upstream git-python, since it looks like the issue is actually a git-python bug.

If you are interested in looking into the issue in upstream git-python we would be happy to accept this kind of PR in DVC as a placeholder until the issue is actually resolved in git-python.

**Comment by dineshkumarsarangapani** [comment]
@pmrowla Thank you. I will look in to the fix in upstream Git python. 👍

**Comment by efiop** [comment]
Closing as stale. Please feel free to reopen. Thank you for your PR! :pray:

**Pull request closed without merging**
