### PR TITLE
codeclimate: turn all the checks on

### PR DESCRIPTION
**Pull request by efiop**
Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

### CODE REVIEW

**Comment by shcheklein** [comment]
Ruslan, what is the motivation behind this?

**Comment by shcheklein** [comment]
From my previous projects experience, these requirements make sense in most cases and help writing cleaner code. Otherwise it's safer to just mark specific occurrences as ignored in CC interface.

**Comment by efiop** [comment]
@shcheklein some of the requirements are too strict and often stimulate over-unification that harms readability. Disabling some of the checks for now. Note that we still have all the other checks and we also check for 100% PEP8 compliance as well as generally no PR is merged without my review.

**Comment by shcheklein** [comment]
can we just ignore them on a per case basis? it's useful to see some recommendations and warnings about code complexity, as well some warnings about code duplication. Let's just agree to consider them recommendations.

**Comment by shcheklein** [comment]
it just feels that it's not fair to say that we have maintability A when it's only PEP 8 compliance :)

**Pull request merged**
