### PR TITLE
Renamed git property to repo object in dvc/scm/git

### LINKED ISSUE #1993: rename `git` property (a Repo object) in class `dvc.scm.Git`?
`class Git(Base)` property [`self.git`](https://github.com/iterative/dvc/blob/master/dvc/scm/git/__init__.py#L45), while named `git`, is not a **Git** object but rather a **Repo** object, which comes with a `git` property itself (which is the actual Git object); So using the latter (which we do a lot in tests) makes the code a little confusing, like: `self.git.git` and `dvc.scm.git.git`.
> It could even be `self.git.git.git` [in `class GitTree`](https://github.com/iterative/dvc/blob/master/dvc/scm/git/tree.py#L25)!

I think ideally the property name should be `self.repo`, except that name its already in use [by `class Base`](https://github.com/iterative/dvc/blob/master/dvc/scm/base.py#L35) (parent of `class Git`) so renaming `dvc.scm.Git.git` to `dvc.scm.Git.repo` would overwrite `dvc.scm.Base.repo`. I don't know whether this is an immediate problem since I don't see the current `dvc.scm.Git.repo` property being used anywhere in the code, but we probably want to avoid that overwrite anyway.

The options I see are:
a) Don't mind the overwrite and just rename `dvc.scm.Git.git` to `dvc.scm.Git.repo`
b) Rename `dvc.scm.Base.repo` to something else (e.g. `dvc.scm.Base._repo`) and then rename `dvc.scm.Git.git` to `dvc.scm.Git.repo`
c) Rename `dvc.scm.Git.git` to something else, e.g. `dvc.scm.Git.repository`

### PR DESCRIPTION
**Pull request by RahulR19**
* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?     

* [ ] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

I have renamed git to repo in dvc/scm/git 

I'm unable to run tests (Import error of some files)

Fixes #1993

### CODE REVIEW

**Comment by efiop** [comment]
@RahulR19 What error did you get when running tests?

You also need to remove repo from https://github.com/iterative/dvc/blob/master/dvc/scm/base.py#L35 . Both `self.repo = repo` line and ``, repo=None` part from above.

**Comment by RahulR19** [comment]
Import error.

Import error while mockssh module in conftest.

"No module named mockssh"

**Comment by RahulR19** [comment]
I'll look into it.

**Comment by efiop** [comment]
>  Import error.Import error while mockssh module in conftest."No module named mockssh"

@RahulR19 Did you follow our contribution guide? Looks like you didn't install test dependencies as specified in that doc.

**Comment by shcheklein** [comment]
@RahulR19 @kurianbenoy hey, guys, any update for this? do you plan to continue working on this?

**Comment by RahulR19** [comment]
Yeah, I'm working on this, but I'm having some problems with the tests.

**Comment by RahulR19** [comment]
@efiop @shcheklein  How to fix **self.dvc.scm.git.close()** in tests

**Comment by efiop** [comment]
@RahulR19 

> @efiop @shcheklein How to fix self.dvc.scm.git.close() in tests

I've described the process in the comment above. Maybe you have some specific questions?

> Also after changing git to repo, I'm getting the following error while running tests.
> TypeError: init() got an unexpected keyword argument 'repo'

Take a look at the traceback and fix it. Looks like the cause is SCM from from dvc/scm/__init__.py, which is passing `repo=` to Git. You need to remove `repo` from there too.

**Comment by RahulR19** [comment]
Is it alright to change the tests

self.dvc.scm.git.close() to self.dvc.scm.close() is done offline

What happens after I do a PR and travis CI runs online

**Comment by efiop** [comment]
@RahulR19 It is encouraged to change the tests in this case :slightly_smiling_face: Your changes will be a part of this PR, so travis will run tests again.

**Comment by RahulR19** [comment]
I have changed some tests and finally made all the test cases pass (Some test cases were skipped).
Should I make a PR.

**Comment by efiop** [comment]
Thank you so much @RahulR19 ! 🎉

**Comment by RahulR19** [comment]
Thank you for being helpful 😄 @efiop

**Pull request merged**
