### PR TITLE
lint: isort pre-commit & misc improvements

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] consistently order `import`s
- [x] add `pre-commit` hook
- [x] fix minor deepsource issues
- [x] move `.flake8` root clutter to `setup.cfg`
- [x] add `isort` to `restyled`
- [x] ~~fix or~~ ignore CI & restyled failing for `isort` (maybe only an issue for this first PR adding config?)
- [x] ~~maybe~~ open issue for DVC pre-commit failing for more files than hyperthreads? -> #3751
- closes #3750

### CODE REVIEW

**Comment by casperdcl** [comment]
good point @skshetry - just added a commit

**Comment by casperdcl** [comment]
not sure why travis fails... Works fine locally:

```
$ git clone --single-branch --branch test-isort casperdcl/dvc
Cloning into 'dvc'...
done.
$ cd dvc
dvc (test-isort)$ pre-commit run --all-files
black....................................................................Passed
isort....................................................................Passed
```

**Comment by skshetry** [comment]
It's because of `dvc`'s pre-commit hook. Not sure, why it's broken. /cc @efiop

**Comment by efiop** [comment]
@skshetry Not because of dvc hook at all, you can see isort pre-commit hook failing. It reformats tests. Not sure what's up.

**Comment by efiop** [comment]
@casperdcl Probably should also add isort to restyled config.

**Comment by casperdcl** [comment]
> It's because of `dvc`'s pre-commit hook. Not sure, why it's broken. /cc @efiop

No, that only fails locally on mutli-core machines and adding `require_serial: true` in the pre-commit config doesn't seem to help.

> @skshetry Not because of dvc hook at all, you can see isort pre-commit hook failing. It reformats the code. Not sure what's up.

exactly

> Maybe sort version or something.

I pinned it though (to `4.3.21`)

> Probably should also add isort to restyled config.

will do.

**Comment by casperdcl** [comment]
well @efiop's restyled suggestion + @skshetry's note regarding third party equals #3750 equals ea7c52fe192f31df4f3a273143c2d92a61024f12 - clearly not picking up the config for `dvc` being a first-party lib. Maybe this is because the config isn't in master yet?

**Comment by efiop** [comment]
@casperdcl Yeah, sounds likely. Could merge as is (even if it fails) and deal with it on top.

**Comment by casperdcl** [comment]
@efiop based on https://github.com/iterative/dvc/runs/650806804 this is good to merge

**Pull request merged**
