### PR TITLE
[WIP] cmd: diff: don't load dir cache for diff

### LINKED ISSUE #3392: diff: does not behave properly when cache is not available
## Version

```
DVC version: 0.86.5+f67314.mod
Python version: 3.7.6
Platform: Darwin-18.2.0-x86_64-i386-64bit
Binary: False
Package: None
Cache: reflink - supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('apfs', '/dev/disk1s1')
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

## Reproduce

```
git clone git@github.com:iterative/example-get-started.git
cd example-get-started
dvc pull
dvc diff baseline-experiment bigrams-experiment
```

## Output

```
Added:
    data/features/test.pkl
    data/features/train.pkl

Modified:
    auc.metric
    data/features/
    model.pkl

files summary: 2 added, 0 deleted, 2 modified
```

which is wrong. Files `data/features/test.pkl` and `data/features/train.pkl` actually exist in both experiments. The only difference is that one of them cached, one is not.

### PR DESCRIPTION
**Pull request by pared**
* [x] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?

* [x] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does **and** you have created a separate PR in [dvc.org](https://github.com/iterative/dvc.org) with such updates (or at least opened an issue about it in that repo). Please link below to your PR (or issue) in the [dvc.org](https://github.com/iterative/dvc.org) repo.

* [x] ❌ Have you checked DeepSource, CodeClimate, and other sanity checks below? We consider their findings recommendatory and don't expect everything to be addressed. Please review them carefully and fix those that actually improve code or fix bugs.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Fixes #3392

### CODE REVIEW

**Comment by efiop** [comment]
Sorry for a late question, but does this mean that we lose support for dirs from now on? The issue was that when one version has .dir cache file and the other one doesn't, then the output is weird, right?

**Comment by pared** [comment]
@efiop Yes, in a way. After this change, `dir` out will have the same behavior as `non-dir` one:
it will be displayed as `added/deleted/modified` as a whole.

**Comment by pared** [comment]
After discussing with @efiop, its probably the best to apply a hybrid approach:
when the cache is available, list differences, if not, treat dir as if they were not dirs.

**Comment by shcheklein** [comment]
@pared @efiop I have some doubts about this - hybrid approach means that users will see different results in different situations, and will be happening silently for them. 

Or am I missing something about this hybrid approach? Can we highlight those dirs somehow, for example?

cc @dmpetrov .

**Comment by dmpetrov** [comment]
> @pared @efiop I have some doubts about this - hybrid approach means that users will see different results in different situations, and will be happening silently for them.

Totally agree with @shcheklein It will lead to unstable diffs.

I'd suggest ignoring all dirs content (option 3 from #3392). This option has additional advantages:
1. No need in the cache and no need in data-remote credentials which is important for some CI/CD scenarios.
2. Easy to implement.

**Comment by efiop** [comment]
Ok, I thought that dir cache support was desirable, but if it is not, then indeed let's just drop it. Thanks for clarifying. :pray: 

@pared Sorry for this back and forth, please revert the hybrid changes.

**Comment by shcheklein** [comment]
@efiop my 2cs - it's desirable, but it should be done along with support for `dvc list` and other commands that require it (what about `gc` for example?).

**Comment by efiop** [comment]
> it's desirable, but it should be done along with support for dvc list and other commands that require it 

In that case, I'm not sure why can't we start with diff here, since it is on the surface already. And then proceed with `dvc list` and others.

> what about gc for example?

Gc will attempt to pull .dir to analyze it, unlike diff/list/etc.

**Comment by shcheklein** [comment]
> In that case, I'm not sure why can't we start with diff here, since it is on the surface already

I guess there is some misalignment on what do we think can be considered as a start? There were a few different suggestions that @pared brought - from very simple (never do for dirs) to the actual implementation (try and pull dir file). I personally fine to start with either. The only one I had concerns about is the hybrid one - when we silently behave in a different way depending on cache availability.

**Comment by dmpetrov** [comment]
> I'm not sure why can't we start with diff here

First, because here a hybrid approach is proposed which does not give a reliable result.
Second, diff without cache is a required feature #2998 (closed due to this issue). It would be great to have asap because ci/cd needs it.

A good strategy might be - implement quickly the simple strategy (and make sure it does not require cache) and then prioritize the full solution with data dir check.

**Comment by efiop** [comment]
Ok, thanks for clarifying. Sure, let's start with the simplest one first to unblock ci/cd. :+1:

**Pull request merged**
