### PR TITLE
progress: add main bars

### LINKED ISSUE #3452: progress: inconsistent nested format when no main bar
## Overview
When storage is local (copy_file) on `dvc pull` first pbar is displayed as normal one ([self.pos = 0](https://github.com/iterative/dvc/blob/f05e6e0529ae147e82e3c392951f03c01b6b0c64/dvc/progress.py#L96)) and all others are nested

## Description
When we do remote.download for all scheme [except local](https://github.com/iterative/dvc/blob/f05e6e0529ae147e82e3c392951f03c01b6b0c64/dvc/remote/base.py#L585) there are [main bar](https://github.com/iterative/dvc/blob/f05e6e0529ae147e82e3c392951f03c01b6b0c64/dvc/remote/base.py#L619)
So only first pbar is normal, and all others are nested
```
$ dvc push grand_files
 51% grand_files/1/file-1|█████████████████████████████████████████████                                           |164M/320M [00:14<00:07,    21.1MB/s]
 38%|███▊      |grand_files/1/another-file-1                                                                       122M/320M [00:14<00:18,    11.3MB/s]
 66%|██████▋   |grand_files/1/second-file-1                                                                        212M/320M [00:14<00:08,    13.0MB/s]
 35%|███▌      |grand_files/1/third-file
```

but expects that all pbars are as 1-pbar

Relates other commands as well:
```
$ dvc import ../repo grand_files
Importing 'grand_files (../repo)' -> 'grand_files'                      
 56% grand_files.9vFFJ8yBMA9QLmwq5PL7xj.tmp/1/second-file-1|██████████████████████████████                        |178M/320M [00:03<00:06,    23.8MB/s]
 54%|█████▍    |grand_files.9vFFJ8yBMA9QLmwq5PL7xj.tmp/1/another-file-1                                            174M/320M [00:03<00:06,    23.1MB/s]
 57%|█████▋    |grand_files.9vFFJ8yBMA9QLmwq5PL7xj.tmp/1/file-1                                                    181M/320M [00:03<00:06,    23.0MB/s]
 54%|█████▍    |grand_files.9vFFJ8yBMA9QLmwq5PL7xj.tmp/1/third-file-1     
```
```
$ dvc pull -j3 grand_files
 78% ../../../../../../../tmp/tmp3zld67wsdvc-erepo/grand_files/1/another-file-1|██████████████████████████▍       |249M/320M [00:04<00:03,    21.7MB/s]
 80%|████████  |../../../../../../../tmp/tmp3zld67wsdvc-erepo/grand_files/1/file-1                                 256M/320M [00:05<00:04,    15.2MB/s]
 93%|█████████▎|../../../../../../../tmp/tmp3zld67wsdvc-erepo/grand_files/1/second-file-1                          297M/320M [00:04<00:01,    21.5MB/s]
```
Relates: 
 - https://github.com/iterative/dvc/issues/2905

**Please provide information about your setup**
```
$ dvc --version
0.87.0+f05e6e
```

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] add `push`/`pull` main bar
- [x] ~~add `import`/`get` main bar~~ awaiting @efiop changes
- [x] ~~append to rather than remove initial `desc` (perhaps even in other places in a different issue)?~~ moved to #3681
- fixes #3452
- related #1840
- related #3565
- related #3597
- related #528

### CODE REVIEW

**Comment by shcheklein** [comment]
Example: https://asciinema.org/a/YEsnExZypmhtq6k2aDSYi5nvr (start at 20th s)

Main progress bar looks great.

UI/UX comments, some possible optimizations (not sure if some of them are related this PR particularly cc @efiop @pmrowla):

1. Querying cache happens two times, second time it blinks at some progress and moves on - quite confusing. This it probably related to the changes discussed with @pmrowla.
2. Downloads. It's expected no progress bars for them yet. But they still blink. I would still try an option when we just don't clean the line for a while.
3. Downloads - the last large file takes time to download, meaning that we see static blank lines at the end, sometimes 20 lines. 
4. **Possible optimization**. Btw, we should be sorting files we download/upload by their size before pass them into the queue - it can speedup pull/push significantly in some cases.
5. Checkout - it's a total mess - I just don't understand it - sometimes two progress bars (one is at 0%), then one progress bar without description (?)
6. I agree with one of the tickets that `1 added` is very confusing. At the end.

**Comment by casperdcl** [comment]
Was just about to post a recording; thanks.

> 2. Downloads. It's expected no progress bars for them yet. But they still blink. I would still try an option when we just don't clean the line for a while.

There's no way to do this automatically - what if the last 50 jobs finish at exactly the same time? All will leave these messages behind. The only solution in that case would be to manually clear `TERM_HEIGHT` lines at the end of the `ThreadPool`. If you think that would be fine to do everywhere then let me know/open a new issue.

> 3. Downloads - the last large file takes time to download, meaning that we see static blank lines at the end, sometimes 20 lines.

Same problem as before. Either we move running bars upwards when other things finish (old `tqdm` behaviour, lots of flickering), or we never move a displaying bar (current `tqdm` behaviour, no flickering but some blank spaces near the end when there are a few jobs left). The current state is not improvable for the same reason as above.

> 4. **Possible optimization**. Btw, we should be sorting files we download/upload by their size before pass them into the queue - it can speedup pull/push significantly in some cases.

Yes, this should be a separate issue.

> 5. Checkout - it's a total mess - I just don't understand it - sometimes two progress bars (one is at 0%), then one progress bar without description (?)

There's one main bar (initial description "Checkout") which updates its description based on the last successfully checked out file. If item to be checked out is large, a nested bar appears showing its progress.

> 6. I agree with one of the tickets that `1 added` is very confusing. At the end.

#1838 <- This one? (Also related: #2869; #1622.)

**Comment by shcheklein** [comment]
Thanks for the explanation, @casperdcl !

Ok, I see. We can create a ticker to try to remove blank lines.

> There's one main bar (initial description "Checkout") which updates its description based on the last successfully checked out file. If item to be checked out is large, a nested bar appears showing its progress.

Probably the most confusing part here is this switch from Checkout 0% to some file name. (similar to the ticket with Git). My 2cs on this - I would try keep the Checkout message stable (above, below, or in the progress bar itself). File names should appear somewhere (e.g. below) "Processing: <file-name>". So, it's similar to the nested case - always show the file below the main progress bar. In some cases with progress on its own, in some cases w/o.

**Comment by casperdcl** [comment]
@efiop why was #528 closed? Seems like we need to re-open it.

**Comment by efiop** [comment]
> @efiop why was #528 closed? Seems like we need to re-open it.

Was no longer relevant. Please feel free to reopen.

**Comment by shcheklein** [comment]
> Was no longer relevant. Please feel free to reopen.

I think it was not clear why was it not relevant anymore :)

**Comment by efiop** [comment]
@shcheklein Because it had had questionable effectiveness, that wasn't worth the effort. At least that is what our consensus was back then, IIRC. I am still not sure if it is worth it, so have to trust @casperdcl 's research :slightly_smiling_face:

**Comment by casperdcl** [comment]
Ok, it seems like there should have been a slight speed improvement. Anyway I think a secondary gain here is reducing whitespace between bars by ordering them in advance.

**Comment by shcheklein** [comment]
Yeah, but if we have file sizes it's (for pull we don't have them yet, might need them for other  tickets #3568 ) we can improve pretty significantly in certain cases for free. And indeed improve UI along the way.

**Comment by efiop** [comment]
Well, we might just use 1 progress bar as we've discussed earlier. Doing the sorting to compensate for flickery pbar sounds strange to me, I would probably reconsider single progress bar again.

**Comment by efiop** [comment]
@casperdcl Any progress on this?

**Comment by casperdcl** [comment]
@efiop Updated description just to be clear: a lot of discussion is probably for other issues. I think this can me merged as-is. Maybe need a new issue to collate things blocked on the `import`/`get` refactoring?

**Comment by casperdcl** [comment]
ah srry didn't notice the merge conflicts :)

**Comment by efiop** [comment]
@casperdcl No worries :) Btw, this indeed greatly improves the experience for `pull/push/fetch`. Thanks again!

**Pull request merged**
