### PR TITLE
Added 'doctor' as an alias for 'version'

### LINKED ISSUE #3185: rename or alias `dvc version` to `dvc doctor`
Just tired of explaining that `dvc version` is not the same as `dvc --version`. `doctor` seems pretty common and is self-explanatory. What do you guys think?

### PR DESCRIPTION
**Pull request by browningjp**
Fix #3185

Documentation PR [here](https://github.com/iterative/dvc.org/pull/1866)

This PR will also form part of a forthcoming job application

* [X] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [X] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Review by pared — APPROVED** [review]
Looks, good! Thank you for contribution @browningjp!

**Comment by jorgeorpinel** [comment]
Interesting! (Noticed this per iterative/dvc.org/pull/1866.) We don't have any other aliases like this so far, do we? Are we going to keep both or is this a temporary change?

**Comment by jorgeorpinel** [comment]
E.g. when we changed pipeline -> dag we didn't keep an alias, or did we? How was that handled (should it be the same as here e.g. keeping a doc for each name)?

**Review by pmrowla — COMMENTED** [review]
This could be simplified to just use
```
version_parser = subparsers.add_parser(
    ...
    aliases=["doctor"],
)
```

so that we can avoid needing the entire extra subparser

**Comment by browningjp** [comment]
Thanks Peter! Didn't know about the alias option, that's much neater. I've pushed the change to my branch now.

**Comment by efiop** [comment]
Thank you @browningjp ! :pray:

**Pull request merged**
