### PR TITLE
plots: collect: provide callable for data resolution

### PR DESCRIPTION
**Pull request by pared**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by Suor** [comment]
Do we still need a generator in `.plot.collect()` after we return callables anyway?

**Comment by pared** [comment]
@Suor up to you, I translate it to "old" format down the line anyway. Shall I revert it?

**Comment by Suor** [comment]
If talking about Studio then that never needed that. We only parse one rev at a time, and it's always workspace.

**Comment by pared** [comment]
@Suor I am leaving this change as is let's merge it, and I will create a new one about investigating why the partial methods do not fail if the branch has been changed.

Also 
> @Suor up to you, I translate it to "old" format down the line anyway. Shall I revert it?

I was wrong here, as I need the generator behavior to not jump on other revisions before resolving `data_source`

**Comment by pared** [comment]
@Mergifyo rebase

**Comment by pared** [comment]
@Mergifyio rebase

**Comment by pared** [comment]
@Mergifyio rebase

**Review by efiop — APPROVED** [review]

**Pull request merged**
