### PR TITLE
install: fix archives

### PR DESCRIPTION
**Pull request by pared**
* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏
Fixes: #7124

### CODE REVIEW

**Review by efiop — APPROVED** [review]
Thank you!

**Comment by skshetry** [comment]
Could this have been fixed in chocolatey-dvc package? Since no packager have requested us for this.

**Comment by pared** [comment]
It could be, but zip and tar releases could not be installed.

**Comment by skshetry** [comment]
Right, but we never claimed support for that installation mechanism. It should be installed through proper channels.

**Pull request merged**
