### PR TITLE
non-blocking intermediate progress IO

### LINKED ISSUE #2766: use non-blocking multithreaded progress I/O
continuing discussion from #2697

- use the old non-blocking approach
  + https://github.com/iterative/dvc/blob/0.35.6/dvc/progress.py#L51
- use blocking upon completion
  + https://github.com/iterative/dvc/blob/0.35.6/dvc/progress.py#L70
- depends on https://github.com/tqdm/tqdm/issues/838 -> https://github.com/tqdm/tqdm/pull/839

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] non-blocking for intermediate progress (creation, iteration, update)
- [x] block only upon completion (printing 100%, stats, etc)
- fixes #2766 (from #2697)
- depends on https://github.com/tqdm/tqdm/issues/838 -> https://github.com/tqdm/tqdm/pull/839

### CODE REVIEW

**Comment by casperdcl** [comment]
@shcheklein from https://github.com/iterative/dvc/issues/2697#issuecomment-550399107

can you try this PR and re-post the results?

**Comment by shcheklein** [comment]
@casperdcl works great for me (was not watching if progress itself is in tack):

https://gist.github.com/shcheklein/1113cab8d976453814e7e65a376f3a0c

this is linux, xfs, hadlinks, the same dataset 50G, 0.5M images - imagenet.

And this the previous result from the same machine:

```
 1117645  506.966    0.000  506.966    0.000 {method 'acquire' of '_thread.lock' objects}
   338417    1.645    0.000  509.674    0.002 /usr/lib/python3.6/threading.py:263(wait)
   440796    2.846    0.000  513.793    0.001 /usr/lib/python3.6/concurrent/futures/_base.py:405(result)
   440796    1.827    0.000  515.756    0.001 /usr/lib/python3.6/concurrent/futures/_base.py:579(result_iterator)
   440797    0.864    0.000  520.677    0.001 /mnt/ivan/dvc/.env/lib/python3.6/site-packages/tqdm/std.py:1057(__iter__)
        1    1.045    1.045  536.154  536.154 /mnt/ivan/dvc/dvc/remote/base.py:180(_calculate_checksums)
        1    0.430    0.430  612.398  612.398 /mnt/ivan/dvc/dvc/remote/base.py:193(_collect_dir)
        1    0.493    0.493  632.768  632.768 /mnt/ivan/dvc/dvc/remote/base.py:230(get_dir_checksum)
        1    0.000    0.000  643.798  643.798 /mnt/ivan/dvc/dvc/output/base.py:173(changed_checksum)
        1    0.000    0.000  643.799  643.799 /mnt/ivan/dvc/dvc/output/base.py:187(status)
        1    0.000    0.000  643.799  643.799 /mnt/ivan/dvc/dvc/output/base.py:202(changed)
        2    0.000    0.000  649.328  324.664 /mnt/ivan/dvc/dvc/remote/base.py:324(save_info)
        1    0.000    0.000  649.329  649.329 /mnt/ivan/dvc/dvc/output/base.py:217(save)
        1    0.000    0.000  649.330  649.330 /mnt/ivan/dvc/dvc/stage.py:711(save)
440801/440800    0.680    0.000  660.204    0.001 /mnt/ivan/dvc/dvc/remote/base.py:295(get_checksum)
        1    0.000    0.000 1084.849 1084.849 /mnt/ivan/dvc/dvc/repo/add.py:20(add)
        1    0.000    0.000 1084.850 1084.850 /mnt/ivan/dvc/dvc/repo/scm_context.py:2(run)
        1    0.000    0.000 1084.877 1084.877 /mnt/ivan/dvc/dvc/repo/__init__.py:32(wrapper)
        1    0.000    0.000 1084.877 1084.877 /mnt/ivan/dvc/dvc/command/add.py:16(run)
        1    0.000    0.000 1085.132 1085.132 /mnt/ivan/dvc/dvc/main.py:21(main)
        1    0.000    0.000 1085.414 1085.414 /mnt/ivan/dvc/.env/bin/dvc:4(<module>)
   1800/1    0.027    0.000 1085.414 1085.414 {built-in method builtins.exec}
```

500s for thread locking.

**Comment by shcheklein** [comment]
QQ - are there any implications of the change? Some minor inconsistencies on updates?

**Comment by casperdcl** [comment]
@shcheklein there's https://tqdm.github.io/releases/ - the only code changes which may affect users are:

- fix `colorama` on win
- potential future `pandas` fix
- better unicode widechar support
- add `stacklevel=2` to warnings

Though when I say "affect" it means there'll only be breaking changes if I accidentally introduced a bug. Unlikely given the high unit test coverage and several hundred thousand downloads sans complaints :)

**Comment by casperdcl** [comment]
If you mean local implications (i.e. not related to upstream `tqdm` version update) then there should be no real difference to `dvc` users. Potentially if there are 10 simultaneous bars on the screen then it may take up to a second for one of them to update (before it would've been 0.1 sec).

**Comment by shcheklein** [comment]
> Potentially if there are 10 simultaneous bars on the screen then it may take up to a second for one of them to update (before it would've been 0.1 sec).

yep, that's what I was asking mostly about :) thanks 🙏

**Pull request merged**
