### PR TITLE
status: add OSS as a cache

### PR DESCRIPTION
**Pull request by mroutis**
* [x] Have you followed the guidelines in our
      [Contributing document](https://dvc.org/doc/user-guide/contributing)?

* [x] Does your PR affect documented changes or does it add new functionality
      that should be documented? If yes, have you created a PR for
      [dvc.org](https://github.com/iterative/dvc.org) documenting it or at
      least opened an issue for it? If so, please add a link to it.

-----

### CODE REVIEW

**Comment by efiop** [comment]
@mroutis Could you provide some context? Why did you have to add it? Was something raising an exception?

**Comment by mroutis** [comment]
@efiop , Sure! So, I was reading the source code and then noticed that it iterates over every stage output and use its scheme to `expand` an array:
```python
for out in stage.outs:
    scheme = out.path_info.scheme
    cache[scheme].extend(
        self._collect_used_cache(
            out,
            branch=branch,
            remote=remote,
            force=force,
            jobs=jobs,
        )
    )
```

The problem is that `oss` wasn't defined as part of the dictionary, so it will raise a `KeyError`.

Maybe I'm reading it wrong, @efiop

**Comment by efiop** [comment]
@mroutis But we don't support external OSS outputs.

**Comment by mroutis** [comment]
Got it :+1:

**Pull request closed without merging**
