### PR TITLE
exp show: throws an error with -n -1

### PR DESCRIPTION
**Pull request by karajan1001**
fix: #7434
exp show -n -1 will throw error on any repo with a remote repo setted.

1. Update new version of `scmrepo`
2. Update the unit test add a remote repo to the test case.

* [x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.

* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by karajan1001** [comment]
Looks like scmrepo is not compatible with current version of DVC. After PR
```
commit 29d834163ca6c5aa60be6f0f68785e3c2f6f2f87 (HEAD)
Author: Ruslan Kuprieiev <kupruser@gmail.com>
Date:   Tue Dec 28 02:49:14 2021 +0200

    fs: detach from local filesystem (#24)

    This PR makes our fs accept paths relative to the root of the repo and using / as a separator.
    Previous behaviour was a legacy from old dvc.

    Pre-requisite for making dvcfs/repofs/etc switch to the same relative repo paths and / separators.
```

Guess it arrise from the relative path and abs path change in recent `DVC` project.

**Comment by skshetry** [comment]
See https://github.com/iterative/dvc/pull/7359#issuecomment-1032671631.

**Comment by skshetry** [comment]
@karajan1001, I don't understand the change here. Do we need this?

**Comment by karajan1001** [comment]
> @karajan1001, I don't understand the change here. Do we need this? Tests pass fine on master with `scmrepo==0.0.10`.

I used to update `scmrepo` to 0.0.9 and change the test environment in it. But for now the `scmrepo` had already been updated to a newer version. The remained line of test environment changing will ensure #7434 would be passed. I

**Comment by karajan1001** [comment]
@dberenbaum so I guess for now, after updating the `scmrepo` to 0.0.10 the original #7434 had already been solved, do we still this tests or maybe we could close #7434 directly.

**Comment by pmrowla** [comment]
If the underlying issue was in scmrepo, #7434 should just be closed with a link to the scmrepo fix/PR (and the appropriate test should have been added in scmrepo)

**Comment by skshetry** [comment]
The fix in https://github.com/iterative/scmrepo/pull/32 was about supporting `~n` references from the title and is tested for that. The description and the change here points to some issue with git repos having remotes set, which is not tested.

**Comment by karajan1001** [comment]
> The fix in [iterative/scmrepo#32](https://github.com/iterative/scmrepo/pull/32) was about supporting `~n` references from the title and is tested for that. The description and the change here points to some issue with git repos having remotes set, which is not tested.

The test here influence the line below 
```python
gen = iter_revs(scm, ["other"], -1)
```
which will test `1,2,3,...n` util receive a `ScmError`. And going back to https://github.com/iterative/dvc/pull/7204#issuecomment-1023057609,
This problem only arises in a repo with a remote repo being set.

**Comment by pmrowla** [comment]
Ok, so the remote being set causes us to manually try `refs/remotes/<name>` on the DVC side. This would lead to us testing trying to resolve relative commits that may not exist in `refs/remotes`  (like `refs/remotes/origin/HEAD~6`).

The actual underlying problem was that trying to resolve relative commits that did not exist would lead to the unhandled pygit exception. This is not actually related to whether or not remotes are set at all, the same behavior would occur if we tried a non-remote ref like `refs/HEAD~999999` where that relative commit does not exist. It's just coincidental that the bug was identified by setting a remote.

So we probably do not actually need this test/change on the DVC side, since we now have an actual test for resolving non-existent commits now on the scmrepo side.

https://github.com/iterative/scmrepo/blob/330bce52c922009e608c6e3dcc16f23e5f09ff18/tests/test_git.py#L582-L583

**Pull request closed without merging**
